ancillary_list = {
	troy_main_anc_armour_achilles_helm = 2,
	troy_main_anc_armour_ajax_belt = 2,
	troy_main_anc_armour_ajax_lesser_armour = 2,
	troy_main_anc_armour_ajax_tower = 2,
	troy_main_anc_armour_amphiaraus_shield = 2,
	troy_main_anc_armour_bronze_zoster_belt = 2,
	troy_main_anc_armour_capaneus_shield = 2,
	troy_main_anc_armour_celestial_iron_graves = 1,
	troy_main_anc_armour_eteoclus_shield = 2,
	troy_main_anc_armour_heavy_shield = 1,
	troy_main_anc_armour_heavy_helmet = 2,
	troy_main_anc_armour_hippomedon_shield = 2,
	troy_main_anc_armour_legendary_shield = 2,
	troy_main_anc_armour_memnon_armour = 2,
	troy_main_anc_armour_nestor_shield = 2,
	troy_main_anc_armour_parthenopeus_shield = 2,
	troy_main_anc_armour_polynices_shield = 2,
	troy_main_anc_armour_reinforced_shield = 2,
	troy_main_anc_armour_rhesus_armour = 2,
	troy_main_anc_armour_tydeus_shield = 2,
	troy_main_anc_armour_zone_belt = 1,
	troy_main_anc_armour_zoster_belt = 2,
	troy_main_anc_follower_briseis = 2,
	troy_main_anc_follower_cassandra = 2,
	troy_main_anc_follower_chryseis = 2,
	troy_main_anc_follower_clymene = 2,
	troy_main_anc_follower_deinome = 2,
	troy_main_anc_follower_hecamede = 2,
	troy_main_anc_follower_mimas = 2,
	troy_main_anc_follower_ucalegon = 2,
	troy_main_anc_follower_xenodice = 2,
	troy_main_anc_item_achaean_himation = 2,
	troy_main_anc_item_achaean_kithon = 1,
	troy_main_anc_item_aegeus_sandals = 2,
	troy_main_anc_item_aeolian_himation = 2,
	troy_main_anc_item_aeolian_kithon = 1,
	troy_main_anc_item_aeolus_bag = 2,
	troy_main_anc_item_amphion_lyre = 2,
	troy_main_anc_item_apple_discord = 2,
	troy_main_anc_item_bronze_mirror = 2,
	troy_main_anc_item_castor_pilos = 2,
	troy_main_anc_item_cithaeronian_pelt = 2,
	troy_main_anc_item_cretan_hat = 2,
	troy_main_anc_item_cretan_hat_feather = 2,
	troy_main_anc_item_cup_nestor = 2,
	troy_main_anc_item_dorian_himation = 2,
	troy_main_anc_item_dorian_kithon = 1,
	troy_main_anc_item_golden_cup = 2,
	troy_main_anc_item_golden_grapevine = 2,
	troy_main_anc_item_golden_mirror = 2,
	troy_main_anc_item_hephestus_hammer = 2,
	troy_main_anc_item_hermes_sceptre = 2,
	troy_main_anc_item_ino_veil = 2,
	troy_main_anc_item_ionian_himation = 2,
	troy_main_anc_item_ionian_kithon = 1,
	troy_main_anc_item_lelegan_kithon = 1,
	troy_main_anc_item_lelgan_himation = 2,
	troy_main_anc_item_maeonian_himation = 2,
	troy_main_anc_item_maeonian_kithon = 1,
	troy_main_anc_item_minoan_necklace = 1,
	troy_main_anc_item_minos_tablet = 1,
	troy_main_anc_item_pan_syrinx = 2,
	troy_main_anc_item_pelasgian_himation = 2,
	troy_main_anc_item_pelasgian_kithon = 1,
	troy_main_anc_item_petasos_hat = 2,
	troy_main_anc_item_poseidon_sceptre = 2,
	troy_main_anc_item_prometheus_ring = 2,
	troy_main_anc_item_seal_knidos = 2,
	troy_main_anc_item_seal_miletus = 2,
	troy_main_anc_item_seal_mycenae = 2,
	troy_main_anc_item_seal_thebes = 2,
	troy_main_anc_item_seal_troy = 2,
	troy_main_anc_item_silver_cup = 1,
	troy_main_anc_item_silver_mirror = 2,
	troy_main_anc_item_statue_aphrodite = 1,
	troy_main_anc_item_statue_apollo = 1,
	troy_main_anc_item_statue_ares = 1,
	troy_main_anc_item_statue_athena = 1,
	troy_main_anc_item_statue_hera = 1,
	troy_main_anc_item_statue_poseidon = 1,
	troy_main_anc_item_statue_zeus = 1,
	troy_main_anc_item_thracian_himation = 2,
	troy_main_anc_item_thracian_kithon = 1,
	troy_main_anc_item_tydeus_boarskin = 2,
	troy_main_anc_item_white_granite_amulet = 1,
	troy_main_anc_item_white_granite_ring = 4,
	troy_main_anc_item_white_granite_mosaic = 1,
	troy_main_anc_weapon_arethous_club = 2,
	troy_main_anc_weapon_bellerophon_bow = 2,
	troy_main_anc_weapon_celestial_iron_dagger = 1,
	troy_main_anc_weapon_iron_ash_club = 2,
	troy_main_anc_weapon_periphetes_club = 2,
	troy_main_anc_weapon_teucros_bow = 2,
	troy_main_anc_weapon_thanatos_sword = 2,
	troy_main_anc_weapon_white_granite_club = 1,
	troy_main_anc_jason_gemstone = 2,
	troy_main_anc_item_bronze_diploma = 2,
	troy_main_anc_item_silver_diploma = 3,
	troy_main_anc_item_golden_diploma = 4,
	troy_dlc2_anc_item_statue_artemis = 1,
	troy_rem_rhesus_ring_of_thrax = 2,
	troy_main_anc_item_seal_argos =2,
	troy_rem_anc_item_horn_thrace = 2,
	troy_hep_anc_item_statue_hephaestus = 1
}


function add_loyalty_ancillary_listeners()
	out("add_loyalty_ancillary_listeners")
	
core:add_listener(
		"GiveLoyaltyForAncillary",
		"CharacterAncillaryGained",
		function(context)
			return ancillary_list[context:ancillary()]	  
		end,
		function(context)
			cm:apply_character_loyalty_change(context:character():command_queue_index(), ancillary_list[context:ancillary()])
		end,
		true
	)

core:add_listener(
		"RemoveLoyaltyForAncillary",
		"CharacterAncillaryLost",
		function(context)
			return ancillary_list[context:ancillary()]	  
		end,
		function(context)
			cm:apply_character_loyalty_change(context:character():command_queue_index(), -ancillary_list[context:ancillary()])
		end,
		true
	)

end