eminence = 
{
	-- TODO: We should be able to hide the entire mechanic until it is selected as a path during the campaign.
	-- See http://helix-swarm.ca.sega.internal/reviews/2928055

	-- NOTE: Change Allegiance (pre-battle) and Raze and Exterminate (post-battle) are implemented in C++ and configured via the database.
	config = {
		resource = {
			name = "phar_eminence",
			battles_factor = "phar_eminence_battles",
			ers_raze_factor = "phar_eminence_ers_raze",
			post_battle_factor = "phar_eminence_post_battle",
			pre_battle_factor = "phar_eminence_pre_battle",
			raiding_factor = "phar_eminence_raiding",
			settlement_raze_factor = "phar_eminence_settlement_raze",
		},

		awards = {
			battle_victory = 10,
			raze_settlement = 20,
			raze_ers = 5,
			raiding = 3,
		},

		display_of_power = {
			-- Cost in Eminence for the Display of Power pre-battle option
			cost = 25,

			-- Efect bundle key for Display of Power. The bundle is applied to the opposing military force.
			effect_bundle = "phar_sea_effect_bundle_display_of_power",
		},

		obedience = {
			-- Costs in Eminence for the Obedience pre-battle option, depending on the type of the attacked settlement
			cost = {
				cult_centre = 150,
				major_settlement = 115,
				minor_settlement = 80,
			},

			-- If the army in the settlement has more than this many units, Obedience cannot be used.
			max_enemy_units = 15,
			
			-- Disabling Obedience for faction capitals limits its usefulnes too much, so by default it is enabled. Nevertheless, leaving this for easy toggling in mods.
			can_use_on_faction_capitals = true,

			-- A list of army templates used to spawn different armies depending on the type and realm of the attacked settlement
			spawned_armies = {
				hittite_lowlands_realm = {
					cult_centre = "phar_main_nat_isu_heavy_anatolian_chariots,phar_main_nat_isu_heavy_anatolian_chariots,phar_main_nat_isu_armoured_anatolian_swordsmen,phar_main_nat_isu_armoured_anatolian_swordsmen,phar_main_nat_isu_armoured_anatolian_swordsmen,phar_main_nat_isu_armoured_anatolian_spears,phar_main_nat_isu_armoured_anatolian_spears,phar_main_nat_isu_armoured_anatolian_spears,phar_main_nat_isu_armoured_hittite_skirmishers,phar_main_nat_isu_armoured_hittite_skirmishers,phar_main_nat_isu_armoured_hittite_skirmishers,phar_main_nat_isu_luwian_swordsmen,phar_main_nat_isu_luwian_swordsmen,phar_main_nat_isu_luwian_swordsmen,phar_main_nat_isu_luwian_swordsmen,phar_main_nat_isu_isuwan_slingers,phar_main_nat_isu_isuwan_slingers,phar_main_nat_isu_isuwan_slingers,phar_main_nat_isu_isuwan_slingers",
					major_settlement = "phar_main_nat_isu_heavy_anatolian_chariots,phar_main_nat_isu_armoured_anatolian_swordsmen,phar_main_nat_isu_armoured_anatolian_spears,phar_main_nat_isu_armoured_anatolian_spears,phar_main_nat_isu_armoured_anatolian_spears,phar_main_nat_isu_armoured_hittite_skirmishers,phar_main_nat_isu_armoured_hittite_skirmishers,phar_main_nat_isu_luwian_swordsmen,phar_main_nat_isu_luwian_swordsmen,phar_main_nat_isu_luwian_swordsmen,phar_main_nat_isu_luwian_swordsmen,phar_main_nat_isu_luwian_swordsmen,phar_main_nat_isu_luwian_swordsmen,phar_main_nat_isu_isuwan_slingers,phar_main_nat_isu_isuwan_slingers,phar_main_nat_isu_isuwan_slingers,phar_main_nat_isu_isuwan_slingers,phar_main_nat_isu_isuwan_slingers,phar_main_nat_isu_isuwan_slingers",
					minor_settlement = "phar_main_nat_isu_armoured_hittite_skirmishers,phar_main_nat_isu_armoured_hittite_skirmishers,phar_main_nat_isu_armoured_hittite_skirmishers,phar_main_nat_isu_armoured_anatolian_spears,phar_main_nat_isu_armoured_anatolian_spears,phar_main_nat_isu_luwian_swordsmen,phar_main_nat_isu_luwian_swordsmen,phar_main_nat_isu_luwian_swordsmen,phar_main_nat_isu_luwian_swordsmen,phar_main_nat_isu_isuwan_militia,phar_main_nat_isu_isuwan_militia,phar_main_nat_isu_isuwan_militia,phar_main_nat_isu_isuwan_slingers,phar_main_nat_isu_isuwan_slingers",
				},
				hittite_highlands_realm = {
					cult_centre = "phar_main_nat_hig_heavy_anatolian_chariots,phar_main_nat_hig_heavy_anatolian_chariots,phar_main_nat_hig_renowned_phrygian_javelin_throwers,phar_main_nat_hig_renowned_phrygian_javelin_throwers,phar_main_nat_hig_kaskian_raiders,phar_main_nat_hig_kaskian_chargers,phar_main_nat_hig_kaskian_chargers,phar_main_nat_hig_kaskian_chargers,phar_main_nat_hig_kaskian_chargers,phar_main_nat_hig_armoured_anatolian_spears,phar_main_nat_hig_armoured_anatolian_spears,phar_main_nat_hig_phrygian_spearmen,phar_main_nat_hig_phrygian_spearmen,phar_main_nat_hig_kaskian_axemen,phar_main_nat_hig_kaskian_axemen,phar_main_nat_hig_kaskian_javelin_throwers,phar_main_nat_hig_kaskian_javelin_throwers,phar_main_nat_hig_kaskian_javelin_throwers,phar_main_nat_hig_kaskian_javelin_throwers",
					major_settlement = "phar_main_nat_hig_heavy_anatolian_chariots,phar_main_nat_hig_heavy_anatolian_chariots,phar_main_nat_hig_kaskian_chargers,phar_main_nat_hig_kaskian_chargers,phar_main_nat_hig_phrygian_skirmishers,phar_main_nat_hig_phrygian_skirmishers,phar_main_nat_hig_armoured_anatolian_spears,phar_main_nat_hig_phrygian_spearmen,phar_main_nat_hig_phrygian_spearmen,phar_main_nat_hig_phrygian_spearmen,phar_main_nat_hig_kaskian_axemen,phar_main_nat_hig_kaskian_axemen,phar_main_nat_hig_kaskian_axemen,phar_main_nat_hig_kaskian_javelin_throwers,phar_main_nat_hig_kaskian_javelin_throwers,phar_main_nat_hig_kaskian_javelin_throwers,phar_main_nat_hig_kaskian_javelin_throwers,phar_main_nat_hig_kaskian_javelin_throwers,phar_main_nat_hig_anatolian_militia",
					minor_settlement = "phar_main_nat_hig_kaskian_chargers,phar_main_nat_hig_kaskian_chargers,phar_main_nat_hig_kaskian_chargers,phar_main_nat_hig_phrygian_skirmishers,phar_main_nat_hig_phrygian_skirmishers,phar_main_nat_hig_phrygian_spearmen,phar_main_nat_hig_phrygian_spearmen,phar_main_nat_hig_kaskian_axemen,phar_main_nat_hig_kaskian_axemen,phar_main_nat_hig_kaskian_javelin_throwers,phar_main_nat_hig_kaskian_javelin_throwers,phar_main_nat_hig_kaskian_javelin_throwers,phar_main_nat_hig_anatolian_militia,phar_main_nat_hig_anatolian_militia",
				},
				hittite_isuwa_realm = {
					cult_centre = "phar_main_nat_isu_heavy_anatolian_chariots,phar_main_nat_isu_heavy_anatolian_chariots,phar_main_nat_isu_renowned_isuwan_axemen,phar_main_nat_isu_renowned_isuwan_axemen,phar_main_nat_isu_renowned_isuwan_axemen,phar_main_nat_isu_isuwan_axemen,phar_main_nat_isu_isuwan_axemen,phar_main_nat_isu_hittite_archers,phar_main_nat_isu_hittite_archers,phar_main_nat_isu_hittite_archers,phar_main_nat_isu_hittite_archers,phar_main_nat_isu_luwian_spearmen,phar_main_nat_isu_luwian_spearmen,phar_main_nat_isu_luwian_spearmen,phar_main_nat_isu_luwian_spearmen,phar_main_nat_isu_isuwan_slingers,phar_main_nat_isu_isuwan_slingers,phar_main_nat_isu_isuwan_slingers,phar_main_nat_isu_isuwan_slingers",
					major_settlement = "phar_main_nat_isu_renowned_isuwan_axemen,phar_main_nat_isu_renowned_isuwan_axemen,phar_main_nat_isu_isuwan_axemen,phar_main_nat_isu_isuwan_axemen,phar_main_nat_isu_hittite_archers,phar_main_nat_isu_hittite_archers,phar_main_nat_isu_hittite_archers,phar_main_nat_isu_luwian_spearmen,phar_main_nat_isu_luwian_spearmen,phar_main_nat_isu_luwian_spearmen,phar_main_nat_isu_luwian_spearmen,phar_main_nat_isu_luwian_spearmen,phar_main_nat_isu_luwian_spearmen,phar_main_nat_isu_isuwan_slingers,phar_main_nat_isu_isuwan_slingers,phar_main_nat_isu_isuwan_slingers,phar_main_nat_isu_isuwan_slingers,phar_main_nat_isu_isuwan_militia,phar_main_nat_isu_isuwan_militia",
					minor_settlement = "phar_main_nat_isu_isuwan_axemen,phar_main_nat_isu_isuwan_axemen,phar_main_nat_isu_isuwan_axemen,phar_main_nat_isu_hittite_archers,phar_main_nat_isu_hittite_archers,phar_main_nat_isu_luwian_spearmen,phar_main_nat_isu_luwian_spearmen,phar_main_nat_isu_luwian_spearmen,phar_main_nat_isu_luwian_spearmen,phar_main_nat_isu_isuwan_slingers,phar_main_nat_isu_isuwan_slingers,phar_main_nat_isu_isuwan_slingers,phar_main_nat_isu_isuwan_slingers,phar_main_nat_isu_isuwan_militia",
				},
				canaanite_yamhad_realm = {
					cult_centre = "phar_main_nat_fen_armoured_canaanite_chariots,phar_main_nat_fen_armoured_syrian_archers,phar_main_nat_fen_armoured_syrian_archers,phar_main_nat_fen_renowned_canaanite_swordsmen,phar_main_nat_fen_renowned_canaanite_swordsmen,phar_main_nat_fen_light_syrian_archers,phar_main_nat_fen_light_syrian_archers,phar_main_nat_fen_light_syrian_archers,phar_main_nat_fen_light_syrian_archers,phar_main_nat_fen_light_syrian_archers,phar_main_nat_fen_light_syrian_archers,phar_main_nat_fen_canaanite_sellswords,phar_main_nat_fen_canaanite_sellswords,phar_main_nat_fen_canaanite_sellswords,phar_main_nat_fen_canaanite_sellswords,phar_main_nat_fen_canaanite_rock_throwers,phar_main_nat_fen_canaanite_rock_throwers,phar_main_nat_fen_canaanite_rock_throwers,phar_main_nat_fen_canaanite_rock_throwers",
					major_settlement = "phar_main_nat_fen_armoured_syrian_archers,phar_main_nat_fen_armoured_syrian_archers,phar_main_nat_fen_light_syrian_archers,phar_main_nat_fen_light_syrian_archers,phar_main_nat_fen_light_syrian_archers,phar_main_nat_fen_light_syrian_archers,phar_main_nat_fen_light_syrian_archers,phar_main_nat_fen_canaanite_sellswords,phar_main_nat_fen_canaanite_sellswords,phar_main_nat_fen_canaanite_sellswords,phar_main_nat_fen_canaanite_sellswords,phar_main_nat_fen_canaanite_shieldbearers,phar_main_nat_fen_canaanite_shieldbearers,phar_main_nat_fen_canaanite_recruits,phar_main_nat_fen_canaanite_recruits,phar_main_nat_fen_canaanite_recruits,phar_main_nat_fen_canaanite_recruits,phar_main_nat_fen_canaanite_rock_throwers,phar_main_nat_fen_canaanite_rock_throwers",
					minor_settlement = "phar_main_nat_fen_light_syrian_archers,phar_main_nat_fen_light_syrian_archers,phar_main_nat_fen_light_syrian_archers,phar_main_nat_fen_light_syrian_archers,phar_main_nat_fen_light_syrian_archers,phar_main_nat_fen_canaanite_sellswords,phar_main_nat_fen_canaanite_sellswords,phar_main_nat_fen_canaanite_sellswords,phar_main_nat_fen_canaanite_sellswords,phar_main_nat_fen_canaanite_recruits,phar_main_nat_fen_canaanite_recruits,phar_main_nat_fen_canaanite_recruits,phar_main_nat_fen_canaanite_rock_throwers,phar_main_nat_fen_canaanite_rock_throwers",
				},
				canaanite_retjenu_realm = {
					cult_centre = "phar_main_nat_sin_armoured_canaanite_chariots,phar_main_nat_sin_habiru_mercenaries,phar_main_nat_sin_habiru_mercenaries,phar_main_nat_sin_renowned_habiru_slingers,phar_main_nat_sin_renowned_habiru_slingers,phar_main_nat_sin_habiru_skirmishers,phar_main_nat_sin_habiru_skirmishers,phar_main_nat_sin_habiru_skirmishers,phar_main_nat_sin_habiru_skirmishers,phar_main_nat_sin_habiru_skirmishers,phar_main_nat_sin_habiru_skirmishers,phar_main_nat_sin_habiru_raiders,phar_main_nat_sin_habiru_raiders,phar_main_nat_sin_habiru_raiders,phar_main_nat_sin_habiru_raiders,phar_main_nat_sin_habiru_militia,phar_main_nat_sin_habiru_militia,phar_main_nat_sin_habiru_militia,phar_main_nat_sin_habiru_militia",
					major_settlement = "phar_main_nat_sin_habiru_mercenaries,phar_main_nat_sin_habiru_mercenaries,phar_main_nat_sin_habiru_skirmishers,phar_main_nat_sin_habiru_skirmishers,phar_main_nat_sin_habiru_skirmishers,phar_main_nat_sin_habiru_skirmishers,phar_main_nat_sin_habiru_skirmishers,phar_main_nat_sin_habiru_raiders,phar_main_nat_sin_habiru_raiders,phar_main_nat_sin_habiru_raiders,phar_main_nat_sin_habiru_raiders,phar_main_nat_sin_habiru_raiders,phar_main_nat_sin_habiru_raiders,phar_main_nat_sin_habiru_archers,phar_main_nat_sin_habiru_archers,phar_main_nat_sin_habiru_archers,phar_main_nat_sin_habiru_militia,phar_main_nat_sin_habiru_militia,phar_main_nat_sin_habiru_militia",
					minor_settlement = "phar_main_nat_sin_habiru_skirmishers,phar_main_nat_sin_habiru_skirmishers,phar_main_nat_sin_habiru_skirmishers,phar_main_nat_sin_habiru_skirmishers,phar_main_nat_sin_habiru_skirmishers,phar_main_nat_sin_habiru_raiders,phar_main_nat_sin_habiru_raiders,phar_main_nat_sin_habiru_raiders,phar_main_nat_sin_habiru_raiders,phar_main_nat_sin_habiru_militia,phar_main_nat_sin_habiru_militia,phar_main_nat_sin_habiru_militia,phar_main_nat_sin_habiru_archers,phar_main_nat_sin_habiru_archers",
				},
				canaanite_fenkhu_realm = {
					cult_centre = "phar_main_nat_fen_armoured_canaanite_chariots,phar_main_nat_fen_armoured_canaanite_chariots,phar_main_nat_fen_veteran_canaanite_shieldbearers,phar_main_nat_fen_veteran_canaanite_shieldbearers,phar_main_nat_fen_veteran_canaanite_shieldbearers,phar_main_nat_fen_veteran_canaanite_swordsmen,phar_main_nat_fen_veteran_canaanite_swordsmen,phar_main_nat_fen_veteran_canaanite_swordsmen,phar_main_nat_fen_veteran_canaanite_swordsmen,phar_main_nat_fen_veteran_canaanite_swordsmen,phar_main_nat_fen_veteran_canaanite_swordsmen,phar_main_nat_fen_canaanite_skirmishers,phar_main_nat_fen_canaanite_skirmishers,phar_main_nat_fen_canaanite_skirmishers,phar_main_nat_fen_canaanite_skirmishers,phar_main_nat_fen_canaanite_rock_throwers,phar_main_nat_fen_canaanite_rock_throwers,phar_main_nat_fen_canaanite_rock_throwers,phar_main_nat_fen_canaanite_rock_throwers",
					major_settlement = "phar_main_nat_fen_armoured_canaanite_chariots,phar_main_nat_fen_veteran_canaanite_shieldbearers,phar_main_nat_fen_veteran_canaanite_swordsmen,phar_main_nat_fen_veteran_canaanite_swordsmen,phar_main_nat_fen_veteran_canaanite_swordsmen,phar_main_nat_fen_light_syrian_archers,phar_main_nat_fen_light_syrian_archers,phar_main_nat_fen_canaanite_skirmishers,phar_main_nat_fen_canaanite_skirmishers,phar_main_nat_fen_canaanite_skirmishers,phar_main_nat_fen_canaanite_skirmishers,phar_main_nat_fen_veteran_canaanite_shieldbearers,phar_main_nat_fen_veteran_canaanite_shieldbearers,phar_main_nat_fen_canaanite_recruits,phar_main_nat_fen_canaanite_recruits,phar_main_nat_fen_canaanite_recruits,phar_main_nat_fen_canaanite_recruits,phar_main_nat_fen_canaanite_rock_throwers,phar_main_nat_fen_canaanite_rock_throwers",
					minor_settlement = "phar_main_nat_fen_renowned_canaanite_swordsmen,phar_main_nat_fen_renowned_canaanite_swordsmen,phar_main_nat_fen_renowned_canaanite_swordsmen,phar_main_nat_fen_renowned_canaanite_swordsmen,phar_main_nat_fen_renowned_canaanite_swordsmen,phar_main_nat_fen_canaanite_skirmishers,phar_main_nat_fen_canaanite_skirmishers,phar_main_nat_fen_canaanite_skirmishers,phar_main_nat_fen_canaanite_shieldbearers,phar_main_nat_fen_canaanite_recruits,phar_main_nat_fen_canaanite_recruits,phar_main_nat_fen_canaanite_recruits,phar_main_nat_fen_canaanite_rock_throwers,phar_main_nat_fen_canaanite_rock_throwers",
				},
				canaanite_sinai_realm = {
					cult_centre = "phar_main_nat_sin_armoured_canaanite_chariots,phar_main_nat_sin_armoured_canaanite_chariots,phar_main_nat_sin_armoured_canaanite_chariots,phar_main_nat_sin_armoured_canaanite_chariots,phar_main_nat_sin_habiru_mercenaries,phar_main_nat_sin_shasu_warriors,phar_main_nat_sin_shasu_warriors,phar_main_nat_sin_shasu_warriors,phar_main_nat_sin_shasu_warriors,phar_main_nat_sin_shasu_archers,phar_main_nat_sin_shasu_archers,phar_main_nat_sin_shasu_tribesmen,phar_main_nat_sin_shasu_tribesmen,phar_main_nat_sin_shasu_tribesmen,phar_main_nat_sin_shasu_tribesmen,phar_main_nat_sin_habiru_archers,phar_main_nat_sin_habiru_archers,phar_main_nat_sin_habiru_archers,phar_main_nat_sin_habiru_archers",
					major_settlement = "phar_main_nat_sin_armoured_canaanite_chariots,phar_main_nat_sin_armoured_canaanite_chariots,phar_main_nat_sin_shasu_warriors,phar_main_nat_sin_shasu_warriors,phar_main_nat_sin_shasu_warriors,phar_main_nat_sin_shasu_archers,phar_main_nat_sin_shasu_archers,phar_main_nat_sin_shasu_tribesmen,phar_main_nat_sin_shasu_tribesmen,phar_main_nat_sin_shasu_tribesmen,phar_main_nat_sin_shasu_tribesmen,phar_main_nat_sin_shasu_tribesmen,phar_main_nat_sin_shasu_tribesmen,phar_main_nat_sin_habiru_archers,phar_main_nat_sin_habiru_archers,phar_main_nat_sin_habiru_archers,phar_main_nat_sin_habiru_archers,phar_main_nat_sin_habiru_militia,phar_main_nat_sin_habiru_militia",
					minor_settlement = "phar_main_nat_sin_shasu_warriors,phar_main_nat_sin_shasu_warriors,phar_main_nat_sin_shasu_warriors,phar_main_nat_sin_shasu_archers,phar_main_nat_sin_shasu_archers,phar_main_nat_sin_shasu_tribesmen,phar_main_nat_sin_shasu_tribesmen,phar_main_nat_sin_shasu_tribesmen,phar_main_nat_sin_shasu_tribesmen,phar_main_nat_sin_habiru_archers,phar_main_nat_sin_habiru_archers,phar_main_nat_sin_habiru_archers,phar_main_nat_sin_habiru_militia,phar_main_nat_sin_habiru_militia",
				},
				egyptian_lower_egypt_realm = {
					cult_centre = "phar_main_nat_low_egyptian_chariots,phar_main_nat_low_egyptian_chariots,phar_main_nat_low_egyptian_chariots,phar_main_nat_low_egyptian_chariots,phar_main_nat_low_egyptian_chariots,phar_main_nat_low_armoured_lower_egyptian_archers,phar_main_nat_low_armoured_lower_egyptian_archers,phar_main_nat_low_lower_egyptian_veteran_spearmen,phar_main_nat_low_lower_egyptian_veteran_spearmen,phar_main_nat_low_lower_egyptian_veteran_swordsmen,phar_main_nat_low_lower_egyptian_veteran_swordsmen,phar_main_nat_low_lower_egyptian_archers,phar_main_nat_low_lower_egyptian_archers,phar_main_nat_low_lower_egyptian_archers,phar_main_nat_low_lower_egyptian_archers,phar_main_nat_low_lower_egyptian_spear_militia,phar_main_nat_low_lower_egyptian_spear_militia,phar_main_nat_low_lower_egyptian_militia,phar_main_nat_low_lower_egyptian_militia",
					major_settlement = "phar_main_nat_low_egyptian_chariots,phar_main_nat_low_egyptian_chariots,phar_main_nat_low_armoured_lower_egyptian_archers,phar_main_nat_low_armoured_lower_egyptian_archers,phar_main_nat_low_armoured_lower_egyptian_archers,phar_main_nat_low_lower_egyptian_veteran_spearmen,phar_main_nat_low_lower_egyptian_veteran_spearmen,phar_main_nat_low_lower_egyptian_archers,phar_main_nat_low_lower_egyptian_archers,phar_main_nat_low_lower_egyptian_archers,phar_main_nat_low_lower_egyptian_archers,phar_main_nat_low_lower_egyptian_axe_conscripts,phar_main_nat_low_lower_egyptian_axe_conscripts,phar_main_nat_low_lower_egyptian_militia,phar_main_nat_low_lower_egyptian_militia,phar_main_nat_low_lower_egyptian_militia,phar_main_nat_low_lower_egyptian_militia,phar_main_nat_low_lower_egyptian_spear_militia,phar_main_nat_low_lower_egyptian_spear_militia",
					minor_settlement = "phar_main_nat_low_light_egyptian_chariots,phar_main_nat_low_armoured_lower_egyptian_archers,phar_main_nat_low_armoured_lower_egyptian_archers,phar_main_nat_low_lower_egyptian_veteran_spearmen,phar_main_nat_low_lower_egyptian_veteran_spearmen,phar_main_nat_low_lower_egyptian_archers,phar_main_nat_low_lower_egyptian_archers,phar_main_nat_low_lower_egyptian_swordsmen_conscripts,phar_main_nat_low_lower_egyptian_swordsmen_conscripts,phar_main_nat_low_lower_egyptian_militia,phar_main_nat_low_lower_egyptian_militia,phar_main_nat_low_lower_egyptian_militia_slingers,phar_main_nat_low_lower_egyptian_militia_slingers,phar_main_nat_low_lower_egyptian_militia_slingers",
				},
				egyptian_upper_egypt_realm = {
					cult_centre = "phar_main_nat_upp_egyptian_chariots,phar_main_nat_upp_egyptian_chariots,phar_main_nat_upp_upper_egyptian_renowned_archers,phar_main_nat_upp_upper_egyptian_mace_axe_warriors,phar_main_nat_upp_upper_egyptian_khopesh_warriors,phar_main_nat_upp_upper_egyptian_javelin_throwers,phar_main_nat_upp_upper_egyptian_javelin_throwers,phar_main_nat_upp_upper_egyptian_spearmen,phar_main_nat_upp_upper_egyptian_spearmen,phar_main_nat_upp_upper_egyptian_swordsmen,phar_main_nat_upp_upper_egyptian_swordsmen,phar_main_nat_upp_upper_egyptian_archers,phar_main_nat_upp_upper_egyptian_archers,phar_main_nat_upp_upper_egyptian_conscripted_axemen,phar_main_nat_upp_upper_egyptian_conscripted_axemen,phar_main_nat_upp_upper_egyptian_militia_slingers,phar_main_nat_upp_upper_egyptian_militia_slingers,phar_main_nat_upp_upper_egyptian_militia_clubmen,phar_main_nat_upp_upper_egyptian_militia_clubmen",
					major_settlement = "phar_main_nat_upp_egyptian_chariots,phar_main_nat_upp_upper_egyptian_khopesh_warriors,phar_main_nat_upp_upper_egyptian_javelin_throwers,phar_main_nat_upp_upper_egyptian_javelin_throwers,phar_main_nat_upp_upper_egyptian_javelin_throwers,phar_main_nat_upp_upper_egyptian_spearmen,phar_main_nat_upp_upper_egyptian_spearmen,phar_main_nat_upp_upper_egyptian_conscripted_axemen,phar_main_nat_upp_upper_egyptian_conscripted_axemen,phar_main_nat_upp_upper_egyptian_conscripted_axemen,phar_main_nat_upp_upper_egyptian_conscripted_axemen,phar_main_nat_upp_upper_egyptian_archers,phar_main_nat_upp_upper_egyptian_archers,phar_main_nat_upp_upper_egyptian_militia_clubmen,phar_main_nat_upp_upper_egyptian_militia_clubmen,phar_main_nat_upp_upper_egyptian_militia_clubmen,phar_main_nat_upp_upper_egyptian_militia_clubmen,phar_main_nat_upp_upper_egyptian_militia_slingers,phar_main_nat_upp_upper_egyptian_militia_slingers",
					minor_settlement = "phar_main_nat_upp_upper_egyptian_spearmen,phar_main_nat_upp_upper_egyptian_spearmen,phar_main_nat_upp_upper_egyptian_spearmen,phar_main_nat_upp_upper_egyptian_swordsmen,phar_main_nat_upp_upper_egyptian_swordsmen,phar_main_nat_upp_upper_egyptian_archers,phar_main_nat_upp_upper_egyptian_archers,phar_main_nat_upp_upper_egyptian_archers,phar_main_nat_upp_upper_egyptian_archers,phar_main_nat_upp_upper_egyptian_militia_clubmen,phar_main_nat_upp_upper_egyptian_militia_clubmen,phar_main_nat_upp_upper_egyptian_militia_clubmen,phar_main_nat_upp_upper_egyptian_militia_slingers,phar_main_nat_upp_upper_egyptian_militia_slingers",
				},
				egyptian_western_desert_realm = {
					cult_centre = "phar_main_nat_wes_libu_composite_bowmen,phar_main_nat_wes_libu_composite_bowmen,phar_main_nat_wes_libu_desert_swords,phar_main_nat_wes_libu_desert_swords,phar_main_nat_wes_libu_desert_swords,phar_main_nat_wes_libu_tribe_spears,phar_main_nat_wes_libu_tribe_spears,phar_main_nat_wes_libu_warriors,phar_main_nat_wes_libu_warriors,phar_main_nat_wes_libu_desert_skirmishers,phar_main_nat_wes_libu_desert_skirmishers,phar_main_nat_wes_libu_hunters,phar_main_nat_wes_libu_hunters,phar_main_nat_wes_libu_desert_runners,phar_main_nat_wes_libu_desert_runners,phar_main_nat_wes_libu_tribesmen,phar_main_nat_wes_libu_tribesmen,phar_main_nat_wes_libu_tribesmen,phar_main_nat_wes_libu_tribesmen",
					major_settlement = "phar_main_nat_wes_libu_composite_bowmen,phar_main_nat_wes_libu_composite_bowmen,phar_main_nat_wes_libu_tribe_spears,phar_main_nat_wes_libu_tribe_spears,phar_main_nat_wes_libu_tribe_spears,phar_main_nat_wes_libu_warriors,phar_main_nat_wes_libu_warriors,phar_main_nat_wes_libu_hunters,phar_main_nat_wes_libu_hunters,phar_main_nat_wes_libu_hunters,phar_main_nat_wes_libu_raiders,phar_main_nat_wes_libu_raiders,phar_main_nat_wes_libu_raiders,phar_main_nat_wes_libu_tribesmen,phar_main_nat_wes_libu_tribesmen,phar_main_nat_wes_libu_tribesmen,phar_main_nat_wes_libu_tribesmen,phar_main_nat_wes_libu_slingers,phar_main_nat_wes_libu_slingers",
					minor_settlement = "phar_main_nat_wes_libu_tribe_spears,phar_main_nat_wes_libu_tribe_spears,phar_main_nat_wes_libu_tribe_spears,phar_main_nat_wes_libu_desert_skirmishers,phar_main_nat_wes_libu_desert_skirmishers,phar_main_nat_wes_libu_desert_runners,phar_main_nat_wes_libu_desert_runners,phar_main_nat_wes_libu_hunters,phar_main_nat_wes_libu_hunters,phar_main_nat_wes_libu_tribesmen,phar_main_nat_wes_libu_tribesmen,phar_main_nat_wes_libu_tribesmen,phar_main_nat_wes_libu_tribesmen,phar_main_nat_wes_libu_tribesmen",
				},
				egyptian_nubia_realm = {
					cult_centre = "phar_main_nat_nub_renowned_nubian_longbowmen,phar_main_nat_nub_renowned_nubian_longbowmen,phar_main_nat_nub_renowned_nubian_longbowmen,phar_main_nat_nub_renowned_nubian_longbowmen,phar_main_nat_nub_renowned_nubian_longbowmen,phar_main_nat_nub_nubian_clubmen,phar_main_nat_nub_nubian_clubmen,phar_main_nat_nub_nubian_clubmen,phar_main_nat_nub_nubian_clubmen,phar_main_nat_nub_nubian_clubmen,phar_main_nat_nub_nubian_clubmen,phar_main_nat_nub_kushite_spearmen_recruits,phar_main_nat_nub_kushite_spearmen_recruits,phar_main_nat_nub_kushite_archers,phar_main_nat_nub_kushite_archers,phar_main_nat_nub_nubian_bowmen,phar_main_nat_nub_nubian_bowmen,phar_main_nat_nub_nubian_recruits,phar_main_nat_nub_nubian_recruits",
					major_settlement = "phar_main_nat_nub_renowned_nubian_longbowmen,phar_main_nat_nub_renowned_nubian_longbowmen,phar_main_nat_nub_nubian_clubmen,phar_main_nat_nub_nubian_clubmen,phar_main_nat_nub_nubian_clubmen,phar_main_nat_nub_nubian_longbowmen,phar_main_nat_nub_nubian_longbowmen,phar_main_nat_nub_kushite_spearmen_recruits,phar_main_nat_nub_kushite_spearmen_recruits,phar_main_nat_nub_kushite_spearmen_recruits,phar_main_nat_nub_kushite_spearmen_recruits,phar_main_nat_nub_kushite_archers,phar_main_nat_nub_kushite_archers,phar_main_nat_nub_nubian_bowmen,phar_main_nat_nub_nubian_bowmen,phar_main_nat_nub_nubian_bowmen,phar_main_nat_nub_nubian_recruits,phar_main_nat_nub_nubian_recruits,phar_main_nat_nub_nubian_recruits",
					minor_settlement = "phar_main_nat_nub_nubian_clubmen,phar_main_nat_nub_nubian_clubmen,phar_main_nat_nub_nubian_clubmen,phar_main_nat_nub_nubian_longbowmen,phar_main_nat_nub_nubian_longbowmen,phar_main_nat_nub_kushite_spearmen_recruits,phar_main_nat_nub_kushite_spearmen_recruits,phar_main_nat_nub_kushite_archers,phar_main_nat_nub_kushite_archers,phar_main_nat_nub_nubian_bowmen,phar_main_nat_nub_nubian_bowmen,phar_main_nat_nub_nubian_bowmen,phar_main_nat_nub_nubian_recruits,phar_main_nat_nub_nubian_recruits",
				},
				egyptian_kush_realm = {
					cult_centre = "phar_main_nat_nub_renowned_kushite_archers,phar_main_nat_nub_renowned_kushite_archers,phar_main_nat_nub_renowned_kushite_archers,phar_main_nat_nub_renowned_kushite_archers,phar_main_nat_nub_renowned_kushite_archers,phar_main_nat_nub_kushite_spearmen,phar_main_nat_nub_kushite_spearmen,phar_main_nat_nub_kushite_spearmen,phar_main_nat_nub_kushite_spearmen,phar_main_nat_nub_kushite_spearmen,phar_main_nat_nub_kushite_spearmen,phar_main_nat_nub_kushite_archers,phar_main_nat_nub_kushite_archers,phar_main_nat_nub_kushite_spearmen_recruits,phar_main_nat_nub_kushite_spearmen_recruits,phar_main_nat_nub_nubian_recruits,phar_main_nat_nub_nubian_recruits,phar_main_nat_nub_nubian_recruits,phar_main_nat_nub_nubian_recruits",
					major_settlement = "phar_main_nat_nub_renowned_kushite_archers,phar_main_nat_nub_renowned_kushite_archers,phar_main_nat_nub_kushite_spearmen,phar_main_nat_nub_kushite_spearmen,phar_main_nat_nub_kushite_spearmen,phar_main_nat_nub_kushite_spearmen,phar_main_nat_nub_kushite_spearmen,phar_main_nat_nub_kushite_archers,phar_main_nat_nub_kushite_archers,phar_main_nat_nub_kushite_archers,phar_main_nat_nub_kushite_archers,phar_main_nat_nub_kushite_spearmen_recruits,phar_main_nat_nub_kushite_spearmen_recruits,phar_main_nat_nub_nubian_hunters,phar_main_nat_nub_nubian_hunters,phar_main_nat_nub_nubian_recruits,phar_main_nat_nub_nubian_recruits,phar_main_nat_nub_nubian_recruits,phar_main_nat_nub_nubian_recruits",
					minor_settlement = "phar_main_nat_nub_kushite_spearmen,phar_main_nat_nub_kushite_spearmen,phar_main_nat_nub_kushite_spearmen,phar_main_nat_nub_kushite_spearmen,phar_main_nat_nub_kushite_spearmen,phar_main_nat_nub_kushite_archers,phar_main_nat_nub_kushite_archers,phar_main_nat_nub_kushite_archers,phar_main_nat_nub_kushite_spearmen_recruits,phar_main_nat_nub_nubian_hunters,phar_main_nat_nub_nubian_hunters,phar_main_nat_nub_nubian_recruits,phar_main_nat_nub_nubian_recruits,phar_main_nat_nub_nubian_recruits",
				},
				aegean_achaea_realm = {
					cult_centre = "phar_map_nat_ach_veteran_achaean_slingers,phar_map_nat_ach_veteran_achaean_slingers,phar_map_nat_ach_veteran_achaean_slingers,phar_map_nat_ach_argive_axemen,phar_map_nat_ach_argive_axemen,phar_map_nat_ach_shielded_spearmen,phar_map_nat_ach_shielded_spearmen,phar_map_nat_ach_shielded_spearmen,phar_map_nat_ach_shielded_spearmen,phar_map_nat_ach_laconian_hillmen,phar_map_nat_ach_laconian_hillmen,phar_map_nat_ach_laconian_hillmen,phar_map_nat_ach_achaean_bowmen,phar_map_nat_ach_achaean_bowmen,phar_map_nat_ach_aeginian_runners,phar_map_nat_ach_aeginian_runners,phar_map_nat_ach_aeginian_runners,phar_map_nat_ach_achaean_spearmen,phar_map_nat_ach_achaean_spearmen",
					major_settlement = "phar_map_nat_ach_achaean_chariots,phar_map_nat_ach_achaean_chariots,phar_map_nat_ach_achaean_spearmen,phar_map_nat_ach_achaean_spearmen,phar_map_nat_ach_achaean_spearmen,phar_map_nat_ach_achaean_spearmen,phar_map_nat_ach_achaean_spearmen,phar_map_nat_ach_aeginian_runners,phar_map_nat_ach_aeginian_runners,phar_map_nat_ach_aeginian_runners,phar_map_nat_ach_achaean_bowmen,phar_map_nat_ach_achaean_bowmen,phar_map_nat_ach_achaean_stoneslingers,phar_map_nat_ach_achaean_stoneslingers,phar_map_nat_ach_shielded_spearmen,phar_map_nat_ach_shielded_spearmen,phar_map_nat_ach_shielded_spearmen,phar_map_nat_ach_laconian_hillmen,phar_map_nat_ach_laconian_hillmen",
					minor_settlement = "phar_map_nat_ach_achaean_bowmen,phar_map_nat_ach_achaean_bowmen,phar_map_nat_ach_achaean_bowmen,phar_map_nat_ach_achaean_stoneslingers,phar_map_nat_ach_achaean_stoneslingers,phar_map_nat_ach_aeginian_runners,phar_map_nat_ach_aeginian_runners,phar_map_nat_ach_aeginian_runners,phar_map_nat_ach_achaean_spearmen,phar_map_nat_ach_achaean_spearmen,phar_map_nat_ach_achaean_spearmen,phar_map_nat_ach_achaean_spearmen,phar_map_nat_ach_laconian_hillmen,phar_map_nat_ach_laconian_hillmen",
				},
				aegean_assuwa_realm = {
					cult_centre = "phar_map_nat_wil_armoured_lycian_archers,phar_map_nat_wil_armoured_lycian_archers,phar_map_nat_wil_veteran_trojan_slingers,phar_map_nat_wil_veteran_trojan_slingers,phar_map_nat_wil_veteran_trojan_slingers,phar_map_nat_wil_heavy_shock_spears,phar_map_nat_wil_heavy_shock_spears,phar_map_nat_wil_heavy_shock_spears,phar_map_nat_wil_anatolian_swords,phar_map_nat_wil_anatolian_swords,phar_map_nat_wil_anatolian_swords,phar_map_nat_wil_anatolian_swords,phar_map_nat_wil_coastal_club_fighters,phar_map_nat_wil_coastal_club_fighters,phar_map_nat_wil_coastal_club_fighters,phar_map_nat_wil_coastal_club_fighters,phar_map_nat_wil_coastal_club_fighters,phar_map_nat_wil_heavy_trojan_spearmen,phar_map_nat_wil_heavy_trojan_spearmen",
					major_settlement = "phar_map_nat_wil_trojan_warriors,phar_map_nat_wil_trojan_warriors,phar_map_nat_wil_trojan_archers,phar_map_nat_wil_trojan_archers,phar_map_nat_wil_veteran_trojan_slingers,phar_map_nat_wil_veteran_trojan_slingers,phar_map_nat_wil_veteran_trojan_slingers,phar_map_nat_wil_trojan_chariots,phar_map_nat_wil_trojan_chariots,phar_map_nat_wil_coastal_club_fighters,phar_map_nat_wil_coastal_club_fighters,phar_map_nat_wil_coastal_club_fighters,phar_map_nat_wil_coastal_club_fighters,phar_map_nat_wil_heavy_shock_spears,phar_map_nat_wil_heavy_shock_spears,phar_map_nat_wil_eastern_spearmen,phar_map_nat_wil_eastern_spearmen,phar_map_nat_wil_eastern_spearmen,phar_map_nat_wil_eastern_spearmen",
					minor_settlement = "phar_map_nat_wil_eastern_spearmen,phar_map_nat_wil_eastern_spearmen,phar_map_nat_wil_eastern_spearmen,phar_map_nat_wil_eastern_spearmen,phar_map_nat_wil_heavy_trojan_spearmen,phar_map_nat_wil_trojan_archers,phar_map_nat_wil_trojan_archers,phar_map_nat_wil_veteran_trojan_slingers,phar_map_nat_wil_veteran_trojan_slingers,phar_map_nat_wil_veteran_trojan_slingers,phar_map_nat_wil_anatolian_swords,phar_map_nat_wil_anatolian_swords,phar_map_nat_wil_anatolian_swords,phar_map_nat_wil_anatolian_swords",
				},
				aegean_thrace_realm = {
					cult_centre = "phar_map_nat_thr_plainsmen,phar_map_nat_thr_plainsmen,phar_map_nat_thr_plainsmen,phar_map_nat_thr_plainsmen,phar_map_nat_thr_thracian_spearmen,phar_map_nat_thr_thracian_spearmen,phar_map_nat_thr_thracian_spearmen,phar_map_nat_thr_thracian_spearmen,phar_map_nat_thr_worshippers_of_pan,phar_map_nat_thr_worshippers_of_pan,phar_map_nat_thr_thracian_guard,phar_map_nat_thr_thracian_guard,phar_map_nat_thr_thracian_guard,phar_map_nat_thr_forest_skirmishers,phar_map_nat_thr_forest_skirmishers,phar_map_nat_thr_thracian_hunters,phar_map_nat_thr_thracian_hunters,phar_map_nat_thr_thracian_archers,phar_map_nat_thr_thracian_archers",
					major_settlement = "phar_map_nat_thr_thracian_archers,phar_map_nat_thr_forest_skirmishers,phar_map_nat_thr_forest_skirmishers,phar_map_nat_thr_forest_skirmishers,phar_map_nat_thr_forest_skirmishers,phar_map_nat_thr_forest_skirmishers,phar_map_nat_thr_thracian_chariots,phar_map_nat_thr_worshippers_of_pan,phar_map_nat_thr_worshippers_of_pan,phar_map_nat_thr_thracian_guard,phar_map_nat_thr_thracian_guard,phar_map_nat_thr_plainsmen,phar_map_nat_thr_plainsmen,phar_map_nat_thr_plainsmen,phar_map_nat_thr_plainsmen,phar_map_nat_thr_plainsmen,phar_map_nat_thr_thracian_spearmen,phar_map_nat_thr_thracian_spearmen,phar_map_nat_thr_thracian_spearmen",
					minor_settlement = "phar_map_nat_thr_thracian_spearmen,phar_map_nat_thr_thracian_spearmen,phar_map_nat_thr_plainsmen,phar_map_nat_thr_plainsmen,phar_map_nat_thr_plainsmen,phar_map_nat_thr_plainsmen,phar_map_nat_thr_plainsmen,phar_map_nat_thr_plainsmen,phar_map_nat_thr_thracian_hunters,phar_map_nat_thr_thracian_hunters,phar_map_nat_thr_thracian_hunters,phar_map_nat_thr_worshippers_of_pan,phar_map_nat_thr_worshippers_of_pan,phar_map_nat_thr_thracian_guard",
				},
				mesopotamia_aber_nahra_realm = {
					cult_centre = "phar_map_nat_aber_ahlamu_heavy_camelry,phar_map_nat_aber_ahlamu_heavy_camelry,phar_map_nat_aber_ahlamu_camel_riders,phar_map_nat_aber_ahlamu_camel_riders,phar_map_nat_aber_ahlamu_camel_riders,phar_map_nat_aber_ahlamu_heavy_camelry,phar_map_nat_aber_aramean_warriors,phar_map_nat_aber_aramean_warriors,phar_map_nat_aber_aramean_warriors,phar_map_nat_aber_aramean_warriors,phar_map_nat_aber_aramean_warriors,phar_map_nat_aber_aramean_warriors,phar_map_nat_aber_aramean_warriors,phar_map_nat_aber_aramean_warriors,phar_map_nat_aber_aramean_tribesmen,phar_map_nat_aber_aramean_tribesmen,phar_map_nat_aber_ahlamu_archers,phar_map_nat_aber_ahlamu_archers,phar_map_nat_aber_ahlamu_archers",
					major_settlement = "phar_map_nat_aber_ahlamu_heavy_camelry,phar_map_nat_aber_ahlamu_heavy_camelry,phar_map_nat_aber_ahlamu_camel_riders,phar_map_nat_aber_ahlamu_camel_riders,phar_map_nat_aber_ahlamu_camel_riders,phar_map_nat_aber_ahlamu_pack_camels,phar_map_nat_aber_aramean_warriors,phar_map_nat_aber_aramean_warriors,phar_map_nat_aber_aramean_warriors,phar_map_nat_aber_aramean_tribesmen,phar_map_nat_aber_aramean_tribesmen,phar_map_nat_aber_aramean_tribesmen,phar_map_nat_aber_aramean_tribesmen,phar_map_nat_aber_aramean_tribesmen,phar_map_nat_aber_aramean_tribesmen,phar_map_nat_aber_aramean_tribesmen,phar_map_nat_aber_aramean_skirmishers,phar_map_nat_aber_aramean_skirmishers,phar_map_nat_aber_aramean_skirmishers",
					minor_settlement = "phar_map_nat_aber_ahlamu_camel_riders,phar_map_nat_aber_ahlamu_camel_riders,phar_map_nat_aber_ahlamu_camel_riders,phar_map_nat_aber_ahlamu_pack_camels,phar_map_nat_aber_ahlamu_raiders,phar_map_nat_aber_aramean_skirmishers,phar_map_nat_aber_aramean_skirmishers,phar_map_nat_aber_aramean_skirmishers,phar_map_nat_aber_aramean_tribesmen,phar_map_nat_aber_aramean_tribesmen,phar_map_nat_aber_aramean_tribesmen,phar_map_nat_aber_aramean_tribesmen,phar_map_nat_aber_aramean_warriors,phar_map_nat_aber_aramean_warriors",
				},
				mesopotamia_haltamti_realm = {
					cult_centre = "phar_map_nat_halt_elamite_veterans,phar_map_nat_halt_elamite_veterans,phar_map_nat_halt_elamite_veterans,phar_map_nat_halt_elamite_vanguard,phar_map_nat_halt_elamite_vanguard,phar_map_nat_halt_elamite_vanguard,phar_map_nat_halt_elamite_vanguard,phar_map_nat_halt_elamite_vanguard,phar_map_nat_halt_elamite_defenders,phar_map_nat_halt_elamite_defenders,phar_map_nat_halt_elamite_defenders,phar_map_nat_halt_elamite_defenders,phar_map_nat_halt_elamite_defenders,phar_map_nat_halt_elamite_slingers,phar_map_nat_halt_elamite_slingers,phar_map_nat_halt_elamite_slingers,phar_map_nat_halt_elamite_veteran_slingers,phar_map_nat_halt_elamite_veteran_slingers,phar_map_nat_halt_elamite_veteran_slingers",
					major_settlement = "phar_map_nat_halt_elamite_veteran_vanguard,phar_map_nat_halt_elamite_veteran_vanguard,phar_map_nat_halt_elamite_veteran_vanguard,phar_map_nat_halt_elamite_veteran_vanguard,phar_map_nat_halt_elamite_defenders,phar_map_nat_halt_elamite_defenders,phar_map_nat_halt_elamite_defenders,phar_map_nat_halt_elamite_defenders,phar_map_nat_halt_elamite_warriors,phar_map_nat_halt_elamite_warriors,phar_map_nat_halt_elamite_warriors,phar_map_nat_halt_elamite_warriors,phar_map_nat_halt_elamite_warriors,phar_map_nat_halt_elamite_bowmen,phar_map_nat_halt_elamite_bowmen,phar_map_nat_halt_elamite_bowmen,phar_map_nat_halt_elamite_veteran_archers,phar_map_nat_halt_elamite_veteran_archers,phar_map_nat_halt_elamite_veteran_archers",
					minor_settlement = "phar_map_nat_halt_elamite_veterans,phar_map_nat_halt_elamite_slingers,phar_map_nat_halt_elamite_slingers,phar_map_nat_halt_elamite_slingers,phar_map_nat_halt_elamite_slingers,phar_map_nat_halt_elamite_slingers,phar_map_nat_halt_elamite_veteran_slingers,phar_map_nat_halt_elamite_vanguard,phar_map_nat_halt_elamite_vanguard,phar_map_nat_halt_elamite_vanguard,phar_map_nat_halt_elamite_vanguard,phar_map_nat_halt_elamite_defenders,phar_map_nat_halt_elamite_defenders,phar_map_nat_halt_elamite_defenders",
				},
				mesopotamia_mat_assur_realm = {
					cult_centre = "phar_map_nat_assur_akkadian_militia,phar_map_nat_assur_akkadian_militia,phar_map_nat_assur_akkadian_militia,phar_map_nat_assur_akkadian_militia,phar_map_nat_assur_akkadian_militia_spearmen,phar_map_nat_assur_akkadian_militia_spearmen,phar_map_nat_assur_akkadian_militia_spearmen,phar_map_nat_assur_akkadian_chargers,phar_map_nat_assur_akkadian_chargers,phar_map_nat_assur_akkadian_defenders,phar_map_nat_assur_akkadian_defenders,phar_map_nat_assur_akkadian_defenders,phar_map_nat_assur_akkadian_defenders,phar_map_nat_assur_akkadian_horsemen,phar_map_nat_assur_akkadian_horsemen,phar_map_nat_assur_akkadian_horsemen,phar_map_nat_assur_akkadian_skirmishers,phar_map_nat_assur_akkadian_skirmishers,phar_map_nat_assur_akkadian_skirmishers",
					major_settlement = "phar_map_nat_assur_akkadian_militia,phar_map_nat_assur_akkadian_militia,phar_map_nat_assur_akkadian_militia,phar_map_nat_assur_akkadian_militia,phar_map_nat_assur_akkadian_militia_spearmen,phar_map_nat_assur_akkadian_militia_spearmen,phar_map_nat_assur_akkadian_militia_spearmen,phar_map_nat_assur_akkadian_militia_spearmen,phar_map_nat_assur_akkadian_chargers,phar_map_nat_assur_akkadian_chargers,phar_map_nat_assur_akkadian_defenders,phar_map_nat_assur_akkadian_defenders,phar_map_nat_assur_akkadian_militia_spearmen,phar_map_nat_assur_akkadian_horsemen,phar_map_nat_assur_akkadian_horsemen,phar_map_nat_assur_akkadian_skirmishers,phar_map_nat_assur_akkadian_skirmishers,phar_map_nat_assur_akkadian_skirmishers,phar_map_nat_assur_akkadian_skirmishers",
					minor_settlement = "phar_map_nat_assur_akkadian_militia,phar_map_nat_assur_akkadian_militia,phar_map_nat_assur_akkadian_militia,phar_map_nat_assur_akkadian_militia,phar_map_nat_assur_akkadian_militia_spearmen,phar_map_nat_assur_akkadian_militia_spearmen,phar_map_nat_assur_akkadian_militia_spearmen,phar_map_nat_assur_akkadian_militia_spearmen,phar_map_nat_assur_akkadian_chargers,phar_map_nat_assur_akkadian_chargers,phar_map_nat_assur_akkadian_defenders,phar_map_nat_assur_akkadian_horsemen,phar_map_nat_assur_akkadian_skirmishers,phar_map_nat_assur_akkadian_skirmishers",
				},
				mesopotamia_mat_tamti_realm = {
					cult_centre = "phar_map_nat_tamti_akkadian_armoured_archers,phar_map_nat_tamti_akkadian_armoured_archers,phar_map_nat_assur_akkadian_militia,phar_map_nat_assur_akkadian_militia,phar_map_nat_assur_akkadian_militia_spearmen,phar_map_nat_assur_akkadian_militia_spearmen,phar_map_nat_assur_akkadian_militia_spearmen,phar_map_nat_tamti_akkadian_warriors,phar_map_nat_tamti_akkadian_warriors,phar_map_nat_tamti_akkadian_warriors,phar_map_nat_tamti_akkadian_warriors,phar_map_nat_tamti_akkadian_warriors,phar_map_nat_tamti_akkadian_archers,phar_map_nat_tamti_akkadian_archers,phar_map_nat_tamti_akkadian_armoured_archers,phar_map_nat_assur_akkadian_horsemen,phar_map_nat_assur_akkadian_horsemen,phar_map_nat_assur_akkadian_horsemen,phar_map_nat_tamti_akkadian_armoured_archers",
					major_settlement = "phar_map_nat_assur_akkadian_militia,phar_map_nat_assur_akkadian_militia,phar_map_nat_assur_akkadian_militia,phar_map_nat_assur_akkadian_militia,phar_map_nat_assur_akkadian_militia_spearmen,phar_map_nat_assur_akkadian_militia_spearmen,phar_map_nat_assur_akkadian_militia_spearmen,phar_map_nat_assur_akkadian_militia,phar_map_nat_assur_akkadian_militia_spearmen,phar_map_nat_tamti_akkadian_warriors,phar_map_nat_tamti_akkadian_warriors,phar_map_nat_tamti_akkadian_warriors,phar_map_nat_tamti_akkadian_archers,phar_map_nat_tamti_akkadian_archers,phar_map_nat_tamti_akkadian_archers,phar_map_nat_assur_akkadian_horsemen,phar_map_nat_assur_akkadian_horsemen,phar_map_nat_assur_akkadian_horsemen,phar_map_nat_tamti_akkadian_armoured_archers",
					minor_settlement = "phar_map_nat_assur_akkadian_militia,phar_map_nat_assur_akkadian_militia,phar_map_nat_assur_akkadian_militia,phar_map_nat_assur_akkadian_militia,phar_map_nat_assur_akkadian_militia_spearmen,phar_map_nat_assur_akkadian_militia_spearmen,phar_map_nat_assur_akkadian_militia_spearmen,phar_map_nat_assur_akkadian_militia_spearmen,phar_map_nat_tamti_akkadian_warriors,phar_map_nat_tamti_akkadian_warriors,phar_map_nat_tamti_akkadian_warriors,phar_map_nat_tamti_akkadian_archers,phar_map_nat_tamti_akkadian_archers,phar_map_nat_assur_akkadian_horsemen",
				},
				mesopotamia_zagros_realm = {
					cult_centre = "phar_map_nat_zag_cimmerian_elite,phar_map_nat_zag_cimmerian_horse_archers,phar_map_nat_zag_cimmerian_horse_archers,phar_map_nat_zag_urartu_warriors,phar_map_nat_zag_urartu_warriors,phar_map_nat_zag_urartu_warriors,phar_map_nat_zag_urartu_warriors,phar_map_nat_zag_urartu_warriors,phar_map_nat_zag_cimmerian_mounted_warriors,phar_map_nat_zag_cimmerian_mounted_warriors,phar_map_nat_zag_cimmerian_scouts,phar_map_nat_zag_cimmerian_scouts,phar_map_nat_zag_urartu_defenders,phar_map_nat_zag_urartu_defenders,phar_map_nat_zag_urartu_defenders,phar_map_nat_zag_urartu_defenders,phar_map_nat_zag_urartu_tribesmen,phar_map_nat_zag_urartu_tribesmen,phar_map_nat_zag_cimmerian_elite",
					major_settlement = "phar_map_nat_zag_cimmerian_elite,phar_map_nat_zag_cimmerian_horse_archers,phar_map_nat_zag_cimmerian_horse_archers,phar_map_nat_zag_cimmerian_horse_archers,phar_map_nat_zag_cimmerian_mounted_warriors,phar_map_nat_zag_cimmerian_mounted_warriors,phar_map_nat_zag_cimmerian_scouts,phar_map_nat_zag_cimmerian_scouts,phar_map_nat_zag_cimmerian_scouts,phar_map_nat_zag_cimmerian_scouts,phar_map_nat_zag_urartu_warriors,phar_map_nat_zag_urartu_warriors,phar_map_nat_zag_urartu_defenders,phar_map_nat_zag_urartu_defenders,phar_map_nat_zag_urartu_defenders,phar_map_nat_zag_urartu_defenders,phar_map_nat_zag_urartu_hunters,phar_map_nat_zag_urartu_hunters,phar_map_nat_zag_urartu_hunters",
					minor_settlement = "phar_map_nat_zag_cimmerian_mounted_warriors,phar_map_nat_zag_cimmerian_scouts,phar_map_nat_zag_cimmerian_scouts,phar_map_nat_zag_cimmerian_scouts,phar_map_nat_zag_cimmerian_horse_archers,phar_map_nat_zag_cimmerian_horse_archers,phar_map_nat_zag_urartu_defenders,phar_map_nat_zag_urartu_defenders,phar_map_nat_zag_urartu_defenders,phar_map_nat_zag_cimmerian_scouts,phar_map_nat_zag_cimmerian_scouts,phar_map_nat_zag_urartu_warriors,phar_map_nat_zag_urartu_warriors,phar_map_nat_zag_cimmerian_scouts",
				},
				default = {
					cult_centre = "phar_main_nat_low_lower_egyptian_veteran_swordsmen,phar_main_nat_low_lower_egyptian_veteran_swordsmen,phar_main_nat_low_lower_egyptian_veteran_swordsmen",
					major_settlement = "phar_main_nat_low_lower_egyptian_veteran_spearmen,phar_main_nat_low_lower_egyptian_veteran_spearmen,phar_main_nat_low_lower_egyptian_veteran_spearmen",
					minor_settlement = "phar_main_nat_low_lower_egyptian_spear_militia,phar_main_nat_low_lower_egyptian_spear_militia,phar_main_nat_low_lower_egyptian_spear_militia",
				},
			},

			-- A list of general subtypes to be used for spawning Obedience armies for the corresponding playable factions
			spawned_general_subtypes = {
				phar_main_ramesses = "phar_sea_general_obedience_kemet",
				phar_main_seti = "phar_sea_general_obedience_kemet",
				phar_main_tausret = "phar_sea_general_obedience_kemet",
				phar_main_amenmesse = "phar_sea_general_obedience_kemet",
				phar_main_irsu = "phar_sea_general_obedience_canaan",
				phar_main_bay = "phar_sea_general_obedience_canaan",
				phar_main_suppiluliuma = "phar_sea_general_obedience_hatti",
				phar_main_kurunta = "phar_sea_general_obedience_hatti",
				phar_sea_peleset = "phar_sea_general_obedience_sea_people",
				phar_sea_sherden = "phar_sea_general_obedience_sea_people",
				phar_map_babylon = "phar_map_general_obedience_babylonian",
				phar_map_ninurta = "phar_map_general_obedience_assyrian",
				troy_main_dan_mycenae = "phar_map_general_obedience_achaean",
				troy_main_trj_troy = "phar_map_general_obedience_trojan",
				phar_main_merneptah = "phar_sea_general_obedience_kemet",
				phar_main_setnakhte = "phar_sea_general_obedience_kemet",
				phar_main_napata = "phar_sea_general_obedience_kemet",
				phar_main_bahariya = "phar_sea_general_obedience_kemet",
				phar_main_dungul = "phar_sea_general_obedience_kemet",
				troy_main_dan_achilles = "phar_map_general_obedience_achaean",
				troy_main_dan_ithaca = "phar_map_general_obedience_achaean",
				troy_main_dan_boeotians = "phar_map_general_obedience_achaean",
				troy_main_trj_lycia = "phar_map_general_obedience_trojan",
				troy_rem_trj_thrace = "phar_map_general_obedience_trojan",
				phar_main_ugarit = "phar_sea_general_obedience_canaan",
				phar_main_emar = "phar_sea_general_obedience_canaan",
				phar_main_byblos = "phar_sea_general_obedience_canaan",
				phar_main_damascus = "phar_sea_general_obedience_canaan",
				phar_main_ashkelon = "phar_sea_general_obedience_canaan",
				troy_amazons_trj_hippolyta = "phar_sea_general_obedience_hatti",
				phar_main_malidiya = "phar_sea_general_obedience_hatti",
				phar_map_sangarian_phrygians = "phar_sea_general_obedience_hatti",
				phar_main_alashiya = "phar_sea_general_obedience_hatti",
				phar_main_carchemish = "phar_sea_general_obedience_hatti",
				phar_map_igihalkid = "phar_map_general_obedience_babylonian",
				phar_map_lullubi = "phar_map_general_obedience_assyrian",
				phar_map_sutu = "phar_sea_general_obedience_canaan",
				phar_map_shubru = "phar_map_general_obedience_assyrian",
				phar_map_assyria = "phar_map_general_obedience_assyrian",
			},

			-- This force type is applied to the spawned army. It should be linked to the desired military force features.
			spawned_army_force_type = "OBEDIENCE_ARMY",

			-- This bundle will be applied to the army on creation and applied/removed at the start of each turn
			-- depending on whether it is currently located in the region it was spawned in.
			spawned_army_native_region_bundle = "phar_sea_effect_bundle_obedience_army",
		},

		raze_and_exterminate = {
			cult_centre = {
				cost = 150,
				--character_bundle_key = "phar_sea_effect_bundle_raze_and_exterminate_character_cult_centre",
				--character_bundle_turns = 5,
				force_bundle_key = "phar_sea_effect_bundle_raze_and_exterminate_force_cult_centre",
				force_bundle_turns = 4,
			},
			major_settlement = {
				cost = 115,
				--character_bundle_key = "phar_sea_effect_bundle_raze_and_exterminate_character_major",
				--character_bundle_turns = 5,
				force_bundle_key = "phar_sea_effect_bundle_raze_and_exterminate_force_major",
				force_bundle_turns = 4,
			},
			minor_settlement = {
				cost = 80,
				--character_bundle_key = "phar_sea_effect_bundle_raze_and_exterminate_character_minor",
				--character_bundle_turns = 5,
				force_bundle_key = "phar_sea_effect_bundle_raze_and_exterminate_force_minor",
				force_bundle_turns = 4,
			},
		},
		
		ui =
		{
			------------------------------------------------------------------------
			-- Display of Power setup 
			display_power_icon = "UI/Campaign UI/Effect_bundles/icon_sea_effect_display_of_power.png",
			display_power_activation_setup = 
			{
				icon = "UI/Campaign UI/Effect_bundles/icon_sea_effect_display_of_power.png",
				title = "random_localisation_strings_string_phar_sea_eminence_display_power_title",
				text = "random_localisation_strings_string_phar_sea_eminence_display_power_notification_text",
			},
			-- this is displayed when the ability is executed targeting the player
			display_power_activation_reversed_setup = 
			{
				icon = "UI/Campaign UI/Effect_bundles/icon_sea_effect_display_of_power.png",
				title = "random_localisation_strings_string_phar_sea_eminence_display_power_title",
				text = "random_localisation_strings_string_phar_sea_eminence_display_of_power_notification_text_enemy",
			},

			display_power_title_key = "phar_sea_eminence_display_power_title",
			display_power_text_key = "phar_sea_eminence_battle_display_power",
			display_power_flavor_key = "phar_sea_eminence_battle_display_power_flavour",
			display_power_action_key = "phar_sea_eminence_battle_action",

			display_power_blocker_already_used_key = "phar_sea_eminence_battle_display_power_blocker_1",
			display_power_blocker_cannot_afford_key = "phar_sea_eminence_battle_display_power_blocker_2",

			------------------------------------------------------------------------
			-- Obedience setup
			obedience_icon = "UI/Campaign UI/Effect_bundles/icon_sea_effect_obedience.png",
			obedience_activation_setup = 
			{
				icon = "UI/Campaign UI/Effect_bundles/icon_sea_effect_obedience.png",
				title = "random_localisation_strings_string_phar_sea_eminence_obedience_overlay_title",
				text = "random_localisation_strings_string_phar_sea_eminence_obedience_notification_text",
			},
			-- this is displayed when the ability is executed targeting the player
			obedience_activation_reversed_setup = 
			{
				icon = "UI/Campaign UI/Effect_bundles/icon_sea_effect_obedience.png",
				title = "random_localisation_strings_string_phar_sea_eminence_obedience_overlay_title",
				text = "random_localisation_strings_string_phar_sea_eminence_obedience_notification_text_enemy",
			},
			obedience_title_key = "phar_sea_eminence_obedience_title",
			obedience_text_key = "phar_sea_eminence_battle_obedience",
			obedience_flavor_key = "phar_sea_eminence_battle_obedience_flavour",
			obedience_action_key = "phar_sea_eminence_battle_action",

			obedience_blocker_only_settlements_key = "phar_sea_eminence_battle_obedience_blocker_1",
			obedience_blocker_not_capitals_key = "phar_sea_eminence_battle_obedience_blocker_2",
			obedience_blocker_army_size_key = "phar_sea_eminence_battle_obedience_blocker_3",
			obedience_blocker_not_self_key = "phar_sea_eminence_battle_obedience_blocker_4",
			obedience_blocker_cannot_afford_key = "phar_sea_eminence_battle_obedience_blocker_5",

			-- Background images used for different playable factions and different amounts of recruitable units
			obedience_backgrounds = {
				phar_main_ramesses = "UI/skins/default/eminence_panel/banners/image_sea_obedience_ramesses_art.png",
				phar_main_seti = "UI/skins/default/eminence_panel/banners/image_sea_obedience_seti_art.png",
				phar_main_tausret = "UI/skins/default/eminence_panel/banners/image_sea_obedience_tausret_art.png",
				phar_main_amenmesse = "UI/skins/default/eminence_panel/banners/image_sea_obedience_amenmesse_art.png",
				phar_main_irsu = "UI/skins/default/eminence_panel/banners/image_sea_obedience_irsu_art.png",
				phar_main_bay = "UI/skins/default/eminence_panel/banners/image_sea_obedience_bay_art.png",
				phar_main_suppiluliuma = "UI/skins/default/eminence_panel/banners/image_sea_obedience_suppiluliuma_art.png",
				phar_main_kurunta = "UI/skins/default/eminence_panel/banners/image_sea_obedience_kurunta_art.png",
				phar_sea_sherden = "UI/skins/default/eminence_panel/banners/image_sea_obedience_iolaus_art.png",
				phar_sea_peleset = "UI/skins/default/eminence_panel/banners/image_sea_obedience_walwetes_art.png",
			},

			------------------------------------------------------------------------
			-- Change Allegiance setup
			change_allegiance_backgrounds = {
				[0] = "UI/skins/default/eminence_panel/banners/art/image_sea_change_allegiance_art_1.png", -- 0-2 units
				[3] = "UI/skins/default/eminence_panel/banners/art/image_sea_change_allegiance_art_2.png", -- 3-5 units
				[6] = "UI/skins/default/eminence_panel/banners/art/image_sea_change_allegiance_art_3.png", -- 6+ units
			},

		},
	},

	-- Local flags showing whether the corresponding action was just initiated locally by the UI, to avoid button spam
	is_executing = {
		-- Eminence_PreBattle_DisplayOfPower = true/false
		-- Eminence_PreBattle_Obedience = true/false
	},

	-- components and data we can cache, but don't have to save
	cache = 
	{
		--display_of_power_button
		--obedience_button
	},
}


function eminence:get_opposing_character(faction, pending_battle)
	if pending_battle:has_attacker() and pending_battle:has_defender() then
		local player_character, is_from_attacking_side = cm:get_pending_battle_general_for_faction(faction, true)
		if is_from_attacking_side then
			return pending_battle:defender()
		else
			return pending_battle:attacker()
		end
	end
	return nil
end


-- Checks whether the Display of Power option should be enabled in the UI (it is always visible) and gives a reason if it should be disabled.
-- Return values: <option is enabled>, <reason for unavailability>
function eminence:can_use_display_of_power(faction, pending_battle)
	local result = ""
	-- If the opposing force already has the effect bundle, we cannot apply it again.
	local opposing_character = self:get_opposing_character(faction, pending_battle)
	if opposing_character and not opposing_character:is_null_interface() then
		local opposing_force = opposing_character:military_force()
		if opposing_force:has_effect_bundle(self.config.display_of_power.effect_bundle) then
			local localized_blocker = get_localised_random_string(eminence.config.ui.display_power_blocker_already_used_key)
			result = eminence:message_append(result, localized_blocker)
		end
	else
		script_error("ERROR: eminence:can_use_display_of_power received a battle with no opponent character.")
		return false, ""
	end

	-- Check whether the faction has enough Eminence to use Display of Power.
	-- Take into account the amount of Eminence currently blocked for bribing units.
	local cost = self.config.display_of_power.cost + pending_battle:bribed_units_eminence_cost_for_faction(faction:name())
	
	if not cm:faction_can_afford_resource_cost(faction, {{self.config.resource.name, cost }}) then
		local localized_blocker = get_localised_random_string(eminence.config.ui.display_power_blocker_cannot_afford_key)
		result = eminence:message_append(result, localized_blocker)
	end	

	if result ~= "" then
		return false, result
	end

	return true, ""
end

function eminence:perform_display_of_power(faction_cqi)
	local faction = cm:model():faction_for_command_queue_index(faction_cqi)
	local pending_battle = cm:model():pending_battle()

	if not self:can_use_display_of_power(faction, pending_battle) then
		return
	end

	-- Expend Eminence
	-- TODO: Later can replace the transaction with the line below if the cost stays eminence only.
	-- cm:faction_add_pooled_resource(faction:name(), self.config.resource.name, self.config.resource.pre_battle_factor, -self.config.display_of_power.cost)
	local cost = cm:create_new_custom_resource_cost()
	cost:add_resource_cost(self.config.resource.name, self.config.resource.pre_battle_factor, -self.config.display_of_power.cost)
	cm:faction_apply_resource_transaction(faction, cost)

	-- Apply an effect bundle to the enemy army
	local opposing_character = self:get_opposing_character(faction, pending_battle)
	if opposing_character then
		cm:apply_effect_bundle_to_characters_force(self.config.display_of_power.effect_bundle, opposing_character:command_queue_index(), 1)
	end

	local event_data =
	{
		faction_key = faction:name(),
	}
	core:trigger_event("ScriptEventEminenceDisplayOfPowerPerformed", event_data)
	cm:notify_display_of_power_used(faction_cqi)

	local local_faction = cm:get_local_faction(true)
	local local_faction_name = local_faction:name()

	if cm:get_campaign_ui_manager():is_panel_open("popup_pre_battle") then
		if local_faction_name == faction:name() then
			campaign_anouncement:display_announcement(eminence.config.ui.display_power_activation_setup)
		elseif local_faction_name == opposing_character:faction():name() then
			campaign_anouncement:display_announcement(eminence.config.ui.display_power_activation_reversed_setup)
		end
	end

	if local_faction_name == faction:name() and eminence.cache.display_of_power_button then
		eminence:display_eminence_buttons(core:get_ui_root())
	end
end

function eminence:remove_display_of_power_bundle(pending_battle)
	-- Called after a battle finishes. Remove any instances of the effect bundle applied by Display of Power before the battle.
	if pending_battle:has_attacker() then
		cm:remove_effect_bundle_from_characters_force(self.config.display_of_power.effect_bundle, pending_battle:attacker():command_queue_index())
	end
	if pending_battle:has_defender() then
		cm:remove_effect_bundle_from_characters_force(self.config.display_of_power.effect_bundle, pending_battle:defender():command_queue_index())
	end
end


function eminence:is_name_of_cult_centre_region(region_name)
	for _, god_data in ipairs(deities.gods) do
		if god_data.cult_centre_region_key == region_name then
			return true
		end
	end
	return false
end


function eminence:get_battle_settlement_type(settlement_battle)
	local garrison = settlement_battle:contested_garrison()
	if (not garrison) 
		or garrison:is_null_interface()
		or (not garrison:is_settlement())
	then
		local battle_type = settlement_battle:battle_type()
		script_error("ERROR: eminence:get_battle_settlement_type called for non-settlement (battle type '" .. battle_type .. "')")
		return nil
	end

	if self:is_name_of_cult_centre_region(garrison:region():name()) then
		return "cult_centre"
	elseif settlement_battle:is_minor_settlement_battle() then
		return "minor_settlement"
	elseif settlement_battle:is_major_settlement_battle() then
		return "major_settlement"
	end

	-- if none of the above are true, we can do a few more checks if the region is a capital
	-- this means its settlement is major
	if garrison:region():is_province_capital() then
		return "major_settlement"
	else
		return "minor_settlement"
	end
end


function eminence:obedience_cost(settlement_battle)
	-- Cost differs depending on the type of the settlement.
	local settlement_type = self:get_battle_settlement_type(settlement_battle)
	return self.config.obedience.cost[settlement_type]
end


-- Checks whether the Obedience option should be visible and enabled in the UI and gives a reason if the option is unavailable.
-- Return values: <option is visible>, <option is enabled>, <reason for unavailability>
function eminence:can_use_obedience(faction, pending_battle)
	local message = ""
	local option_visible = true
	local option_enabled = true
	local opposing_character = self:get_opposing_character(faction, pending_battle)
	if not opposing_character then
		return false
	end
	local opposing_faction = opposing_character:faction()
	local is_opponent_human = opposing_faction:is_human()
	-- The Obedience option is available only against an enemy settlement. Do not show it at all in non-settlement battles.
	local contested_garrison = pending_battle:contested_garrison()
	if contested_garrison:is_null_interface() 
		or contested_garrison:is_slot()
		or is_opponent_human
	then
		local localized_blocker = get_localised_random_string(eminence.config.ui.obedience_blocker_only_settlements_key)
		message = eminence:message_append(message, localized_blocker)
		option_visible = false
		option_enabled = false
		-- if the garrison is not valid there is no point in gathering all the other info
		return option_visible, option_enabled, message
	end
	local battle_type = pending_battle:battle_type()
	local player_character, is_from_attacking_side = cm:get_pending_battle_general_for_faction(faction, true)
	if battle_type == "fort_sally" or battle_type == "settlement_sally" or not is_from_attacking_side then
		option_visible = false
		option_enabled = false
		-- if this is a sally out or a defense, we don't show it and there is no point in gathering all the other info
		return option_visible, option_enabled, message
	end

	-- Cannot use Obedience against a faction capital.
	local contested_region = contested_garrison:region()
	local home_region = contested_garrison:faction():home_region()
	local is_battle_at_home_region = contested_region and home_region and not contested_region:is_null_interface() and not home_region:is_null_interface() and contested_region:name() == home_region:name()
	if not self.config.obedience.can_use_on_faction_capitals and is_battle_at_home_region then
		option_enabled = false
		local localized_blocker = get_localised_random_string(eminence.config.ui.obedience_blocker_not_capitals_key)
		message = eminence:message_append(message, localized_blocker)
	end
	
	-- Cannot use Obedience if the settlement has an army with too many units.
	if contested_garrison:has_army() and contested_garrison:army():unit_list():num_items() > self.config.obedience.max_enemy_units then
		option_enabled = false
		local localized_blocker = get_localised_random_string(eminence.config.ui.obedience_blocker_army_size_key)
		localized_blocker = common.string_safe_format(localized_blocker, self.config.obedience.max_enemy_units)
		message = eminence:message_append(message, localized_blocker)
	end

	-- Cannot use Obedience if the attacking army is itself spawned from an Obedience action.
	if pending_battle:attacker():military_force():force_type() == self.config.obedience.spawned_army_force_type then
		option_enabled = false
		local localized_blocker = get_localised_random_string(eminence.config.ui.obedience_blocker_not_self_key)
		message = eminence:message_append(message, localized_blocker)
	end

	-- Cost differs depending on settlement type. Take into account the amount of Eminence currently blocked for bribing units.
	local obedience_cost = self:obedience_cost(pending_battle)
	local bribed_units_cost = pending_battle:bribed_units_eminence_cost_for_faction(faction:name())
	local cost = obedience_cost + bribed_units_cost

	if not (cost and cm:faction_can_afford_resource_cost(faction, {{self.config.resource.name, cost}}) or false) then
		option_enabled = false
		local localized_blocker = get_localised_random_string(eminence.config.ui.obedience_blocker_cannot_afford_key)
		message = eminence:message_append(message, localized_blocker)
	end

	return option_visible, option_enabled, message
end


function eminence:perform_obedience(faction_cqi)
	local faction = cm:model():faction_for_command_queue_index(faction_cqi)
	local faction_name = faction:name()
	local pending_battle = cm:model():pending_battle()
	local region = pending_battle:region()
	local region_name = region:name()

	local option_visible, option_enabled, reason_for_unavailability = self:can_use_obedience(faction, pending_battle)
	if not (option_visible and option_enabled) then
		script_error("ERROR: eminence:perform_obedience called but Obedience should not be available (" .. reason_for_unavailability .. ")")
		return
	end

	-- Expend Eminence
	-- TODO: Later can replace the transaction with the line below if the cost stays eminence only.
	-- cm:faction_add_pooled_resource(faction:name(), self.config.resource.name, self.config.resource.pre_battle_factor, -self:obedience_cost(pending_battle))
	local cost = cm:create_new_custom_resource_cost()
	cost:add_resource_cost(self.config.resource.name, self.config.resource.pre_battle_factor, -self:obedience_cost(pending_battle))
	cm:faction_apply_resource_transaction(faction, cost)
	
	local local_faction = cm:get_local_faction(true)
	local local_faction_name = local_faction:name()
	if cm:get_campaign_ui_manager():is_panel_open("popup_pre_battle") then
		local opposing_character = self:get_opposing_character(faction, pending_battle)
		if local_faction_name == faction:name() then
			campaign_anouncement:display_announcement(eminence.config.ui.obedience_activation_setup)
		elseif local_faction_name == opposing_character:faction():name() then
			campaign_anouncement:display_announcement(eminence.config.ui.obedience_activation_reversed_setup)
		end
	end

	local attacking_character, _ = cm:get_pending_battle_general_for_faction(faction, false)

	local previous_owner = region:owning_faction()
	local previous_owner_cqi = is_faction(previous_owner) and previous_owner:command_queue_index() or 0

	-- Cancel the battle but first remember what the settlement was, we need that for generating the army below
	local garrison_residence = pending_battle:contested_garrison()
	local settlement_type = self:get_battle_settlement_type(pending_battle)
	cm:force_pending_battle_complete()

	-- Raze the settlement. Any enemy army garrisoned in it is automatically teleported just outside the border of the region.
	cm:set_region_abandoned(region_name)

	-- Spawn an army according to the type of settlement and the realm.
	local x, y = cm:find_valid_spawn_location_for_character_from_settlement(faction_name, region_name, false, true, 5)
	local realm_name = phar_realms.get_realm_for_region(region_name)
	local realm_army_templates = self.config.obedience.spawned_armies[realm_name] or self.config.obedience.spawned_armies.default
	cm:create_force_with_general(
		faction_name,
		realm_army_templates[settlement_type],
		region_name,
		x, y,
		"general",
		self.config.obedience.spawned_general_subtypes[faction_name],
		"", "", "", "", -- No names
		false,
		function(cqi)
			-- The "OBEDIENCE_ARMY" force type has the features "unable_to_exchange_units" and "general_is_irreplaceable".
			local character = cm:get_character_by_cqi(cqi)
			cm:convert_force_to_type(character, self.config.obedience.spawned_army_force_type)
			cm:apply_effect_bundle_to_characters_force(self.config.obedience.spawned_army_native_region_bundle, cqi, 0)
			local military_force = character:military_force()
			cm:set_script_state(military_force, "obedience_bundle_key", self.config.obedience.spawned_army_native_region_bundle)
			cm:set_script_state(military_force, "native_region", region_name)
			
			if pillars_civilization.is_nomad_or_sea_peoples_faction(character:faction():name()) then
				cm:apply_effect_bundle_to_characters_force("phar_sea_effect_bundle_horde_faction_obedience_army", cqi, 0)
			end

			-- when this army is removed, the supply points script will remove the supply score of this army
			-- but since it is spawned, not trained, it will not add the supply score
			-- therefore we need to add the supply manually, so after the army is spawned and destroyed the supply score of the faction remains as it was originally
			if is_supply_points_applicable(character:faction()) then
				local unit_list = military_force:unit_list()
				for i = 0, unit_list:num_items() - 1 do
					local unit = unit_list:item_at(i)
					-- commanders are handled in the supply_points_unit_created listener
					-- the normal units are not
					if not unit:has_unit_commander() then
						supply_points.update_supply_points_for_unit(unit, true, supply_points_factors.units)
					end
				end

				supply_points.apply_effects_for_faction(character:faction():name())
			end

			local event_data =
			{
				faction_key = faction_name,
				settlement_type = settlement_type,
				region_key = region_name,
				character = attacking_character,
			}
			core:trigger_event("ScriptEventEminenceObediencePerformed", event_data)
			cm:notify_obedience_used(faction_cqi, previous_owner_cqi, region:command_queue_index(), settlement_type)
		end
	)

	if local_faction_name == faction:name() and eminence.cache.obedience_button then
		eminence:display_eminence_buttons(core:get_ui_root())
	end
end


function eminence:update_obedience_armies_for_faction(faction)
	cm:iterate_forces(
		function(force)
			if force:force_type() == self.config.obedience.spawned_army_force_type then
				local general = force:general_character()
				local region = general and not general:is_null_interface() and general:region()
				local region_name = region and not region:is_null_interface() and region:name() or ""
				local realm_name = phar_realms.get_realm_for_region(region_name)
				local original_realm_name = phar_realms.get_realm_for_region(cm:get_string_script_state(force, "native_region"))
				if realm_name == original_realm_name then
					cm:apply_effect_bundle_to_force(self.config.obedience.spawned_army_native_region_bundle, force:command_queue_index(), 0)
				else
					cm:remove_effect_bundle_from_force(self.config.obedience.spawned_army_native_region_bundle, force:command_queue_index())
				end
			end
		end,
		faction)
end

function eminence:handle_popup_pre_battle_open(component)
	local pending_battle = cm:model():pending_battle()
	if (not pending_battle) or
		(not pending_battle:has_attacker())
	then
		return
	end

	local local_faction = cm:get_local_faction(true)
	local player_character, _ = cm:get_pending_battle_general_for_faction(local_faction, false)
	if not player_character then
		-- this can happen in MP if the game settings allow one player to fight on the side of the AI vs the other player
		return
	end

	eminence.cache.display_of_power_button = find_uicomponent(component, "button_display_of_power")
	eminence.cache.obedience_button = find_uicomponent(component, "button_obedience")
	eminence.is_executing.Eminence_PreBattle_DisplayOfPower = false
	eminence.is_executing.Eminence_PreBattle_Obedience = false

	eminence:display_eminence_buttons(component)
end

function eminence:display_eminence_buttons(component)
	local local_faction = cm:get_local_faction(true)
	local pending_battle = cm:model():pending_battle()
	-- Determine if the Eminence-related pre-battle options are visible and enabled:
	-- Display of power
	eminence:setup_display_of_power_prebattle_button(eminence.cache.display_of_power_button, local_faction, pending_battle)

	-- Obedience
	eminence:setup_obedience_prebattle_button(eminence.cache.obedience_button, local_faction, pending_battle)

	-- Change allegiance
	-- Change Allegiance is handled in the C++ code and has its dedicated UI in the pre-battle screen.
end

function eminence:setup_display_of_power_prebattle_button(display_of_power_button, local_faction, pending_battle)
	if not display_of_power_button then
		return
	end

	local is_eminence_unlocked = forge_path.is_system_unlocked_by_faction("eminence", local_faction:name())
	local opposing_character = self:get_opposing_character(local_faction, pending_battle)
	if not opposing_character then
		return false
	end
	local opposing_faction = opposing_character:faction()
	local is_opponent_human = opposing_faction:is_human()
	if is_opponent_human or
		not is_eminence_unlocked
	then
		display_of_power_button:SetVisible(false)
		return
	end

	display_of_power_button:SetVisible(true)
	local can_use, failure_reason = self:can_use_display_of_power(local_faction, pending_battle)
	display_of_power_button:SetState(can_use and "active" or "inactive")
	local display_of_power_cco_table = {}

	display_of_power_cco_table.IconPath = eminence.config.ui.display_power_icon

	display_of_power_cco_table.DisplayName = get_localised_random_string(eminence.config.ui.display_power_title_key)
	display_of_power_cco_table.Text = get_localised_random_string(eminence.config.ui.display_power_text_key)

	display_of_power_cco_table.EminenceCost = self.config.display_of_power.cost
	display_of_power_cco_table.EminenceCostString = tostring(display_of_power_cco_table.EminenceCost)
	
	local eminence_script_interface = local_faction:pooled_resource(self.config.resource.name)
	if eminence_script_interface then
		display_of_power_cco_table.EminenceOwned = eminence_script_interface:value() - pending_battle:bribed_units_eminence_cost_for_faction(local_faction:name())
		local eminence_max = eminence_script_interface:maximum_value()
		display_of_power_cco_table.EminenceMax = tostring(eminence_max)
	end
	display_of_power_cco_table.EffectBundleKey = self.config.display_of_power.effect_bundle

	display_of_power_cco_table.Flavor = get_localised_random_string(eminence.config.ui.display_power_flavor_key)

	display_of_power_cco_table.Warning = failure_reason
	-- we only show the action if there is no failure reason
	if failure_reason == "" then
		display_of_power_cco_table.Action = get_localised_random_string(eminence.config.ui.display_power_action_key)
	end

	local display_of_power_script_id = "display_of_power_script_id"
	display_of_power_button:SetProperty("script_id", display_of_power_script_id)
	common.set_context_value(display_of_power_script_id, display_of_power_cco_table)
end

function eminence:setup_obedience_prebattle_button(obedience_button, local_faction, pending_battle)
	if not obedience_button then
		return
	end

	local is_eminence_unlocked = forge_path.is_system_unlocked_by_faction("eminence", local_faction:name())
	if not is_eminence_unlocked then
		obedience_button:SetVisible(false)
		return
	end

	local obedience_visible, obedience_enabled, failure_reason = self:can_use_obedience(local_faction, pending_battle)
	obedience_button:SetVisible(obedience_visible)
	if not obedience_visible then
		return
	end
	obedience_button:SetState(obedience_enabled and "active" or "inactive")
	obedience_button:SetVisible(true)
	local obedience_cco_table = {}

	obedience_cco_table.IconPath = eminence.config.ui.obedience_icon

	obedience_cco_table.DisplayName = get_localised_random_string(eminence.config.ui.obedience_title_key)
	obedience_cco_table.Text = get_localised_random_string(eminence.config.ui.obedience_text_key)

	obedience_cco_table.EminenceCost = self:obedience_cost(pending_battle)
	obedience_cco_table.EminenceCostString = tostring(obedience_cco_table.EminenceCost)
	local eminence_script_interface = local_faction:pooled_resource(self.config.resource.name)
	if eminence_script_interface then
		obedience_cco_table.EminenceOwned = eminence_script_interface:value() - pending_battle:bribed_units_eminence_cost_for_faction(local_faction:name())
		local eminence_max = eminence_script_interface:maximum_value()
		obedience_cco_table.EminenceMax = tostring(eminence_max)
	end

	obedience_cco_table.Flavor = get_localised_random_string(eminence.config.ui.obedience_flavor_key)

	obedience_cco_table.Warning = failure_reason
	if failure_reason == "" then
		obedience_cco_table.Action = get_localised_random_string(eminence.config.ui.obedience_action_key)
	end
	local obedience_script_id = "obedience_script_id"
	obedience_button:SetProperty("script_id", obedience_script_id)
	common.set_context_value(obedience_script_id, obedience_cco_table)
end

function eminence:raze_and_exterminate_details_for_region(region)
	if self:is_name_of_cult_centre_region(region:name()) then
		return self.config.raze_and_exterminate.cult_centre
	elseif region:is_province_capital() then
		return self.config.raze_and_exterminate.major_settlement
	else
		return self.config.raze_and_exterminate.minor_settlement
	end
end


function eminence:setup_garrisons_for_eminence()
	-- Attach eminence-related details to every garrison residence on the map indicating the settings for Raze and Exterminate and the award for normal Raze.
	-- Raze and Exterminate is applicable to settlements only, not ERSes.
	cm:iterate_regions(
		function(region)
			local region_garrison_residence = region:garrison_residence()
			local details = self:raze_and_exterminate_details_for_region(region)
			cm:set_script_state(region_garrison_residence, "eminence_from_raze", self.config.awards.raze_settlement)

			cm:set_script_state(region_garrison_residence, "eminence_for_raze_and_exterminate", details.cost)

			--cm:set_script_state(region_garrison_residence, "character_bundle_from_raze_and_exterminate", details.character_bundle_key)
			--cm:set_script_state(region_garrison_residence, "character_bundle_turns_from_raze_and_exterminate", details.character_bundle_turns)

			cm:set_script_state(region_garrison_residence, "force_bundle_from_raze_and_exterminate", details.force_bundle_key)
			cm:set_script_state(region_garrison_residence, "force_bundle_turns_from_raze_and_exterminate", details.force_bundle_turns)

			local slots = region:slot_list()
			for i = 0, slots:num_items() - 1 do
				cm:set_script_state(slots:item_at(i):garrison_residence(), "eminence_from_raze", self.config.awards.raze_ers)
			end
		end
	)
end

-- small util method to accumulate strings on new lines, without a leading new line
function eminence:message_append(message, addition)
	if message ~= "" then
		message = message .. "\n"
	end
	message = message .. addition
	return message
end

-- On pre-battle panel opened
core:add_listener(
	"Eminence_PreBattleOptions_PanelOpenedCampaign",
	"PanelOpenedCampaign",
	function(context) 
		return cm.game_is_running and context.string == "popup_pre_battle"
	end,
	function(context)
		local component = UIComponent(context.component)
		eminence:handle_popup_pre_battle_open(component)
	end,
	true
)


-- On first tick, update any open pre-battle panel (for pre-battle save files) and update the shared state eminence details for razing and raiding
core:add_listener(
	"Eminence_PreBattleOptions_FirstTickAfterWorldCreated",
	"FirstTickAfterWorldCreated",
	true,
	function(context)
		if cm:has_local_faction() and forge_path.is_system_unlocked_by_faction("eminence", cm:get_local_faction_name(true)) then
			uim:override("hide_resource_phar_eminence"):unlock(true)
		else
			uim:override("hide_resource_phar_eminence"):lock(true)
		end
		if cm:get_campaign_ui_manager():is_panel_open("popup_pre_battle") then
			eminence:handle_popup_pre_battle_open(core:get_ui_root())
		end
		eminence:setup_garrisons_for_eminence()
		cm:set_script_state("eminence_from_raiding", eminence.config.awards.raiding)
		cm:set_script_state("eminence_display_of_power_cost", eminence.config.display_of_power.cost)
		cm:set_script_state("eminence_display_of_power_bundle", eminence.config.display_of_power.effect_bundle)
		cm:set_script_state("eminence_obedience_max_enemy_units", eminence.config.obedience.max_enemy_units)
		cm:set_script_state("eminence_obedience_cost_minor_settlement", eminence.config.obedience.cost.minor_settlement)
		cm:set_script_state("eminence_obedience_cost_major_settlement", eminence.config.obedience.cost.major_settlement)
		cm:set_script_state("eminence_obedience_cost_cult_centre", eminence.config.obedience.cost.cult_centre)
		cm:set_script_state("eminence_raze_and_exterminate_cost_minor_settlement", eminence.config.raze_and_exterminate.minor_settlement.cost)
		cm:set_script_state("eminence_raze_and_exterminate_cost_major_settlement", eminence.config.raze_and_exterminate.major_settlement.cost)
		cm:set_script_state("eminence_raze_and_exterminate_cost_cult_centre", eminence.config.raze_and_exterminate.cult_centre.cost)
	end,
	true
)


eminence.prebattle_triggers ={
	Eminence_PreBattle_DisplayOfPower = eminence.perform_display_of_power,
	Eminence_PreBattle_Obedience = eminence.perform_obedience,
}


-- Synched events for performing Obedience and Display of Power
core:add_listener(
	"Eminence_PreBattleOptions_UITriggerScriptEvent",
	"UITriggerScriptEvent",
	function(context) return eminence.prebattle_triggers[context:trigger()] ~= nil end,
	function(context) return eminence.prebattle_triggers[context:trigger()](eminence, context:faction_cqi()) end,
	true
)


-- Local events from the Obedience and Display of Power buttons, used to check for button spam before activating the synced events
core:add_listener(
	"Eminence_PreBattleOptions_TriggerLocalContextEvent",
	"ContextTriggerEvent",
	function(context) return eminence.prebattle_triggers[context.string] ~= nil and not eminence.is_executing[context.string] end,
	function(context)
		eminence.is_executing[context.string] = true
		local local_faction = cm:get_local_faction(true)
		CampaignUI.TriggerCampaignScriptEvent(local_faction:command_queue_index(), context.string)
	end,
	true
)


core:add_listener(
	"Eminence_PreBattleOptions_UnitBribed",
	"FactionBribesUnit",
	true,
	function(context)
		-- If a unit has been bribed, update the buttons for Obedience and Display of Power
		-- to reflect the reserved amount of Eminence for the bribes. The actual transaction
		-- subtracting the Eminence used for bribes does not happen until after the battle.
		eminence:display_eminence_buttons(core:get_ui_root())
	end,
	true
)


core:add_listener(
	"Eminence_PostBattle_RemoveDisplayOfPowerAndGiveEminence",
	"BattleConflictFinished",
	true,
	function(context)
		local pending_battle = context:pending_battle()
		eminence:remove_display_of_power_bundle(pending_battle)
		cm:faction_add_post_battle_looted_resource(pending_battle:battle_results():winning_faction_key(), eminence.config.resource.name, eminence.config.resource.battles_factor, eminence.config.awards.battle_victory)
	end,
	true
)


core:add_listener(
	"Eminence_FactionTurnStart",
	"FactionTurnStart",
	true,
	function(context)
		eminence:update_obedience_armies_for_faction(context:faction())
	end,
	true
)


-- On main Eminence panel opened/closed
core:add_listener(
	"Eminence_MainPanel_PanelOpenedCampaign",
	"PanelOpenedCampaign",
	function(context) 
		return cm.game_is_running and context.string == "sea_eminence_panel"
	end,
	function(context)
		eminence.panel = UIComponent(context.component)
		
		-- Send the background image configuration to the panel.
		for faction_key, path in pairs(eminence.config.ui.obedience_backgrounds) do
			eminence.panel:InterfaceFunction("configure_obedience_background", faction_key, path)
		end
		for unit_threshold, path in pairs(eminence.config.ui.change_allegiance_backgrounds) do
			eminence.panel:InterfaceFunction("configure_change_allegiance_background", unit_threshold, path)
		end
	end,
	true
)


core:add_listener(
	"Eminence_MainPanel_PanelClosedCampaign",
	"PanelClosedCampaign",
	function(context) 
		return cm.game_is_running and context.string == "sea_eminence_panel"
	end,
	function(context)
		eminence.panel = nil
	end,
	true
)


core:add_listener(
	"Eminence_MainPanel_ComponentLClickUp",
	"ComponentLClickUp",
	function(ctx)
		local comp = UIComponent(ctx.component)
		return eminence.panel and comp and ctx.string == "button_ok" and uicomponent_descended_from(comp, eminence.panel:Id())
	end,
	function(ctx)
		eminence.panel:InterfaceFunction("close_panel")
	end,
	true
)
