
-----------------------------------------------------------------------------------
-----------------------------------------------------------------------------------
--
--	Custom ui listeners
--
-----------------------------------------------------------------------------------
-----------------------------------------------------------------------------------

-- outputs click information to the Lua - UI Script tab
output_uicomponent_on_click();

-- create some campaign helper objects
infotext = get_infotext_manager();
objectives = get_objectives_manager();
uim = cm:get_campaign_ui_manager();

-- attempt to check campaign documentation if we should
if core:is_tweaker_set("CHECK_CAMPAIGN_SCRIPT_DOCGEN") and vfs.exists("script/docgen/content/docgen_campaign_parser.lua") then
	require("script.docgen.content.docgen_campaign_parser");
end;

-- we don't save override states in WH, which means that if an override is locked and
-- the game is saved, it should be unlocked when the game is loaded again
uim:set_should_save_override_state(false);

cm:set_use_cinematic_borders_for_automated_cutscenes(false);

function setup_campaign(exclude_battle_advice)

	out("setup_campaign() called");

	out.inc_tab();

	-- start custom listeners for player actions
	-- these listeners usually trigger further events to notify external scripts (e.g. advice interventions) of player actions
	start_custom_listeners();

	-- load battle script whenever a battle is launched from this campaign (this activates advice)
	if not exclude_battle_advice then
		add_battle_script_override();
	end;

	-- monitor for player confederation taking place
	start_confederation_listeners();

	local local_faction = cm:get_local_faction_name(true);

	if local_faction and cm:get_faction(local_faction) then
		-- enable movement for the player's faction if this is not a new game (just in case the player somehow saved in the middle of an intervention)
		if not cm:is_new_game() then
			cm:enable_movement_for_faction(local_faction);
		end
	end;

	-- monitor rebel armies, and give them siege equipment
	setup_rebel_army_siege_equipment_monitor()

	-- Start listening for player going bankrupt
	start_player_bankrupt_listeners()

	out.dec_tab();
end;

function start_custom_listeners()

	local local_faction = cm:get_local_faction_name(true);

	-- don't start in multiplayer or autorun mode
	if cm:is_multiplayer() or not local_faction then
		return false;
	end;

	--local ui_root = core:get_ui_root();

	-- custom event generators
	-- these listen for events and conditions to occur and then fire custom script events when they do. Doing this greatly
	-- reduces the amount of work that the intervention system has to do (and the amount of output it generates)

	core:start_custom_event_generator("PanelOpenedCampaign", function(context) return context.string == "diplomacy_dropdown" end, "ScriptEventDiplomacyPanelOpened");
	core:start_custom_event_generator("PanelClosedCampaign", function(context) return context.string == "diplomacy_dropdown" end, "ScriptEventDiplomacyPanelClosed");

	-- ScriptEventPreBattlePanelOpened generated by campaign manager
	core:start_custom_event_generator("PanelClosedCampaign", function(context) return context.string == "popup_pre_battle" end, "ScriptEventPreBattlePanelClosed");

	core:start_custom_event_generator("PanelOpenedCampaign", function(context) return context.string == "popup_battle_results" end, "ScriptEventPostBattlePanelOpened");
	core:start_custom_event_generator("PanelClosedCampaign", function(context) return context.string == "popup_battle_results" end, "ScriptEventPostBattlePanelClosed");

	core:start_custom_event_generator("PanelOpenedCampaign", function(context) return context.string == "move_options" end, "ScriptEventMoveOptionsPanelOpened");

	-- core:start_custom_event_generator("PanelOpenedCampaign", function(context) return context.string == "appoint_new_general" end, "ScriptEventAppointNewGeneralPanelOpened");
	core:add_listener(
		"appoint_new_general_listener",
		"PanelOpenedCampaign",
		function(context)
			return context.string == "appoint_new_general";
		end,
		function()
			-- a hack: we trigger this event after a short delay as the panel hasn't been fully built when we get the PanelOpenedCampaign event
			cm:callback(function() core:trigger_event("ScriptEventAppointNewGeneralPanelOpened") end, 0.5);
		end,
		true
	);


	-- diplomacy button clicked
	core:start_custom_event_generator(
		"ComponentLClickUp",
		function(context) return UIComponent(context.component) == find_uicomponent(core:get_ui_root(), "faction_buttons_docker", "button_diplomacy") end,
		"ScriptEventPlayerOpensDiplomacyPanel"
	);

	-- diplomacy button shortcut used
	core:start_custom_event_generator(
		"ShortcutPressed",
		function(context) return context.string == "show_diplomacy" end,
		"ScriptEventPlayerOpensDiplomacyPanel"
	);

	-- diplomacy quick deal button
	core:start_custom_event_generator(
		"ComponentLClickUp",
		function(context)
			if UIComponent(context.component):Parent() then
				local uic_parent = UIComponent(UIComponent(context.component):Parent());
				return uic_parent:IsValid() and uic_parent:Id() == "quick_deal_submenu" and uicomponent_descended_from(uic_parent, "diplomacy_dropdown");
			end;
		end,
		"ScriptEventDiplomacyQuickDealButtonClicked"
	);

	-- raise lord button clicked
	core:start_custom_event_generator(
		"ComponentLClickUp",
		function(context) return UIComponent(context.component) == find_uicomponent(core:get_ui_root(), "character_panel", "raise_forces_options", "button_raise") end,
		"ScriptEventRaiseForceButtonClicked"
	);

	-- player settlement comes under siege
	core:start_custom_event_generator(
		"CharacterBesiegesSettlement",
		function(context) return context:region():owning_faction():name() == local_faction end,
		"ScriptEventPlayerBesieged",
		function(context) return context:region() end
	)

	core:start_custom_event_generator(
		"CharacterCreated",
		function(context) return context:character():faction():name() == local_faction end,
		"ScriptEventPlayerFactionCharacterCreated",
		function(context) return context:character() end
	);

	core:start_custom_event_generator(
		"BuildingCompleted",
		function(context) return context:garrison_residence():faction():name() == local_faction end,
		"ScriptEventPlayerBuildingCompleted",
		function(context) return context:building(), context:garrison_residence() end
	);

	core:start_custom_event_generator(
		"GarrisonOccupiedEvent",
		function(context) return context:character():faction():name() == local_faction end,
		"ScriptEventPlayerCaptureSettlement",
		function(context) return context:garrison_residence(), context:character() end
	);

	core:start_custom_event_generator(
		"RegionGainedDevlopmentPoint",
		function(context) return context:region():owning_faction():name() == local_faction end,
		"ScriptEventPlayerRegionGainedDevelopmentPoint",
		function(context) return context:region() end
	);

	core:start_custom_event_generator(
		"MilitaryForceDevelopmentPointChange",
		function(context) return context:military_force():faction():name() == local_faction and context:point_change() > 0 end,
		"ScriptEventPlayerMilitaryForceGainedDevelopmentPoint",
		function(context) return context:military_force() end
	);

	-- core:start_custom_event_generator(
	-- 	"CharacterSkillPointAvailable",
	-- 	function(context) return context:character():faction():name() == local_faction end,
	-- 	"ScriptEventPlayerCharacterSkillPointAvailable",
	-- 	function(context)
	-- 		return context:character();
	-- 	end
	-- );

	core:start_custom_event_generator(
		"CharacterFinishedMovingEvent",
		function(context) return context:character():faction():name() == local_faction end,
		"ScriptEventPlayerCharacterFinishedMovingEvent",
		function(context)
			return context:character();
		end
	);

	--
	core:add_listener(
		"ScriptEventPlayerCharacterPostFinishedMovingEvent",
		"CharacterFinishedMovingEvent",
		function(context)
			return context:character():faction():name() == local_faction;
		end,
		function(context)
			local char_cqi = context:character():command_queue_index();
			cm:callback(
				function()
					core:trigger_event("ScriptEventPlayerCharacterPostFinishedMovingEvent", cm:get_character_by_cqi(char_cqi));
				end,
				0.2
			);
		end,
		true
	);


	core:start_custom_event_generator(
		"PanelClosedCampaign",
		function(context)
			if context.string == "events" then
				-- test to see if the event_mission component is visible
				local uic = find_uicomponent(core:get_ui_root(), "events", "event_mission");

				if uic and uic:Visible() then
					return true;
				end;
			end;
			return false
		end,
		"ScriptEventPlayerAcceptsMission"
	);

	core:start_custom_event_generator(
		"CharacterRankUp",
		function(context)
			return context:character():faction():name() == local_faction;
		end,
		"ScriptEventPlayerCharacterRankUp",
		function(context)
			return context:character();
		end
	);

	core:start_custom_event_generator(
		"PanelOpenedCampaign",
		function(context)
			if context.string == "character_panel" then

				local uic_settlement = find_uicomponent(core:get_ui_root(), "hud_center", "button_group_settlement", "button_create_army");
				if uic_settlement and (uic_settlement:CurrentState() == "down" or uic_settlement:CurrentState() == "selected") then
					return true;
				end;

				-- horde army
				local uic_horde_army = find_uicomponent(core:get_ui_root(), "hud_center", "button_group_army_settled", "button_create_army");
				if uic_horde_army and (uic_horde_army:CurrentState() == "down" or uic_horde_army:CurrentState() == "selected") then
					return true;
				end;

				return false;
			end;

			return false;
		end,
		"ScriptEventRecruitLordPanelOpened"
	);


	-- post missionsucceeded listener
	-- Fires an additional event a short while after a mission has succeeded, allowing client scripts to know when a
	-- player mission's rewards have definitely* been received
	-- (*unsafe)
	core:add_listener(
		"post_player_missionsucceeded_listener",
		"MissionSucceeded",
		function(context)
			return context:faction():name() == local_faction;
		end,
		function(context)
			local mission_key = context:mission():mission_record_key();

			cm:callback(
				function()
					core:trigger_event("ScriptEventPlayerMissionSucceeded", mission_key);
				end,
				0.2
			);
		end,
		false
	);


	core:start_custom_event_generator(
		"PanelOpenedCampaign",
		function(context)
			if context.string == "character_panel" then

				local uic_settlement = find_uicomponent(core:get_ui_root(), "hud_center", "button_group_settlement", "button_create_army");
				if uic_settlement and (uic_settlement:CurrentState() == "down" or uic_settlement:CurrentState() == "selected") then
					return true;
				end;

				-- horde army
				local uic_horde_army = find_uicomponent(core:get_ui_root(), "hud_center", "button_group_army_settled", "button_create_army");
				if uic_horde_army and (uic_horde_army:CurrentState() == "down" or uic_horde_army:CurrentState() == "selected") then
					return true;
				end;

				return false;
			end;

			return false;
		end,
		"ScriptEventRecruitLordPanelOpened"
	);



	-- campaign interaction monitors
	-- these listen for the player interacting with the UI and store a flag of whether that interaction has occurred which other scripts can query

	-- has player closed unit exchange panel
	uim:add_campaign_panel_closed_interaction_monitor("unit_exchange_panel_closed", "unit_exchange");

	-- has player closed diplomacy panel
	uim:add_campaign_panel_closed_interaction_monitor("diplomacy_panel_closed", "dropdown_diplomacy");

	-- has player researched a technology
	uim:add_interaction_monitor("technology_researched", "ResearchStarted", function(context) return context:faction():name() == local_faction end);

	-- has player recruited a unit
	uim:add_interaction_monitor("unit_recruited", "RecruitmentItemIssuedByPlayer", function() return true end);

	-- has player constructed a building
	uim:add_interaction_monitor("building_constructed", "BuildingConstructionIssuedByPlayer", function() return true end);

	-- has player assigned a character to office
	uim:add_interaction_monitor("office_assigned", "CharacterAssignedToPost", function(context) return context:character():faction():name() == local_faction end);

	-- has player captured a settlement
	uim:add_interaction_monitor("settlement_captured", "GarrisonOccupiedEvent", function(context) return context:character():faction():name() == local_faction end);

	-- has player raised a force
	uim:add_interaction_monitor("force_raised", "ScriptEventRaiseForceButtonClicked");

	-- has player autoresolved
	uim:add_interaction_monitor(
		"autoresolve_selected",
		"ComponentLClickUp",
		function(context)
			local uic = UIComponent(context.component);
			return uic:Id() == "button_autoresolve" and uicomponent_descended_from(uic, "popup_pre_battle");
		end
	);

	-- monitor for player stances
	core:add_listener(
		"player_stance_monitor",
		"ForceAdoptsStance",
		true,
		function(context)
			local mf = context:military_force();
			local stance = tostring(context:stance_adopted());

			-- out("ForceAdoptsStance event triggered, stance is " .. tostring(stance) .. " [" .. mf:active_stance() .. "]");

			if mf:faction():name() == local_faction then
				-- stance "0" is default
				if stance == "1" then
					-- march
					common.set_advice_history_string_seen("has_adopted_stance");
					common.set_advice_history_string_seen("march_stance");
					-- core:trigger_event("ScriptEventPlayerForceAdoptsForcedMarchStance", mf);
				elseif stance == "2" then
					-- ambush
					common.set_advice_history_string_seen("ambush_stance");
					common.set_advice_history_string_seen("has_adopted_stance");
					core:trigger_event("ScriptEventPlayerForceAdoptsAmbushStance", mf);
				elseif stance == "3" then
					-- raiding
					common.set_advice_history_string_seen("raiding_stance");
					common.set_advice_history_string_seen("has_adopted_stance");
					-- core:trigger_event("ScriptEventPlayerForceAdoptsRaidingStance", mf);

				-- elseif stance == "4" then
					-- encamped

				-- elseif stance == "5" then
					-- mustering
					-- common.set_advice_history_string_seen("mustering_stance");
					-- common.set_advice_history_string_seen("has_adopted_stance");	 -- doesn't count
					-- core:trigger_event("ScriptEventPlayerForceAdoptsMusteringStance", mf);
				end;

			else
				-- fire an event if the force is raiding the player's territory
				if stance == "3" or stance == "14" then
					if mf:has_general() then
						local char = mf:general_character();
						if char:has_region() then
							local owning_faction = char:region():owning_faction();
							if not owning_faction:is_null_interface() and owning_faction:name() == local_faction then
								core:trigger_event("ScriptEventForceRaidingPlayerTerritory", mf);
							end;
						end;
					end;
				end;
			end;
		end,
		true
	);

	-- get the campaign manager to send success/failure messages when hero actions are committed against the player faction
	cm:start_hero_action_listener(local_faction);

	-- get the campaign manager to send out a ScriptEventRegionRebels event after the FactionTurnEnd event (the RegionRebels event is sent before)
	cm:generate_region_rebels_event_for_faction(local_faction);

	-- close advisor on turn end if it was opened
	core:add_listener(
		"FactionTurnEnd_CloseAdvisor",
		"FactionTurnEnd",
		function(context) return context:faction():name() == local_faction end,
		function(context)
			local advisor = core:get_ui_root():SequentialFind("advice_interface")
			if advisor and advisor:Visible() then
				advisor:SetVisible(false)
			end
		end,
		true
	);

	-- store a flag per-campaign for the player razing
	if not cm:get_faction(local_faction):is_allowed_to_capture_territory() and not cm:get_saved_value("player_has_razed") then
		core:add_listener(
			"player_has_razed",
			"CharacterRazedSettlement",
			function(context)
				return context:character():faction():name() == local_faction;
			end,
			function()
				cm:set_saved_value("player_has_razed", true);
			end,
			false
		);
	end;

	-- apply debuff to sovereign after successful acquiring of subject
	core:add_listener(
		"FactionBecomesSubject_Bundle_Sovereign",
		"FactionBecomesSubject",
		function(context) return context:faction():get_sovereign():is_human() end,
		function(context)
			local player_fac = context:faction():get_sovereign()
			local effect_bundles = player_fac:effect_bundles()
			for i=0, effect_bundles:num_items() -1 do
				local custom_bundle = cm:clone_or_create_custom_effect_bundle(player_fac:name(), "phar_main_sovereign_debuff_after_vassalization")
				local current_key = effect_bundles:item_at(i):key()
				if  string.find(current_key, "effect_bundle_strategic_threat") then
					local threat_bundle_level = string.sub(current_key, string.len(current_key), -1)
					local debuff_step = -10
					custom_bundle:set_duration(6)
					custom_bundle:add_effect("phar_main_evaluation_add_subjugation","faction_to_faction_own_unseen",(threat_bundle_level * debuff_step))	
					return cm:apply_custom_effect_bundle_to_faction(custom_bundle, player_fac)
				end
			end
		end,
		true
	);
end;

function is_tutorial_mode()
	if not cm:is_game_loaded() then
		script_error("WARNING: is_tutorial_mode() called too early, the game has not yet been created. Returning false, but this may be the wrong value")
		return false
	end
	
	return core:svr_load_bool("sbool_player_selected_first_turn_intro_on_frontend") or cm:get_saved_value("bool_is_tutorial_mode")
end

--	Battle script override
--	Automatically loads a script in any battle launched from campaign. This activates advice in the battle.
function add_battle_script_override()
	cm:add_custom_battlefield(
		"generic",											-- string identifier
		0,													-- x co-ord
		0,													-- y co-ord
		5000,												-- radius around position
		false,												-- will campaign be dumped
		"",													-- loading override
		"script/battle/campaign_battle/battle_start.lua",	-- script override
		"",													-- entire battle override
		0,													-- human alliance when battle override
		false,												-- launch battle immediately
		true,												-- is land battle (only for launch battle immediately)
		false,												-- force application of autoresolver result
		false,												-- force a siege battle to be fought outside the settlement as a land battle
		false												-- disable fortification towers (for siege battles)
	);
end;

function remove_battle_script_override()
	cm:remove_custom_battlefield("generic");
end;

-- restrict confederation for duration of penalty
function start_confederation_listeners()
	core:add_listener(
		"confederation_listener",
		"FactionJoinsConfederation",
		true,
		function(context)
			local faction = context:confederation()
			local faction_name = faction:name()
			local faction_culture = faction:culture()
			local duration = cm:model():get_campaign_variable_by_name(faction:is_human() and "confederation_cooldown_per_culture_player" or "confederation_cooldown_per_culture_ai")

			out("Restricting confederation between [faction:" .. faction_name .. "] and [culture:" .. faction_culture .. "]")
			cm:force_diplomacy("faction:" .. faction_name, "culture:" .. faction_culture, "form confederation", false, true, false)
				
			-- Confederation is possible trough force_confederation() and it is possible to have multiple "ScriptEventConfederationExpired" events for a single faction. This way, it's only one at a time.

			if is_table(cm.turn_countdown_events[faction_name]) then 
				
				for i = 1, #cm.turn_countdown_events[faction_name] do
					if cm.turn_countdown_events[faction_name][i].event_name == "ScriptEventConfederationExpired" then
						table.remove(cm.turn_countdown_events[faction_name], i);
					end;
				end;
			
				cm:add_turn_countdown_event(faction_name, duration, "ScriptEventConfederationExpired", faction_name)
			else
				cm:add_turn_countdown_event(faction_name, duration, "ScriptEventConfederationExpired", faction_name)
			end
		end,
		true
	)

	core:add_listener(
		"confederation_expired",
		"ScriptEventConfederationExpired",
		true,
		function(context)
			local faction_name = context.string
			local faction = cm:get_faction(faction_name)
			local culture = faction:culture()

			out("Unrestricting confederation between [faction:" .. faction_name .. "] and [culture: " .. culture .. "]")
			cm:force_diplomacy("faction:" .. faction_name, "culture:" .. culture, "form confederation", true, true, false)
		end,
		true
	)
end

function setup_rebel_army_siege_equipment_monitor()
	core:add_listener(
		"rebel_army_monitor",
		"FactionTurnStart",
		function(context) return context:faction():name() == "rebels" end,
		function(context)
			local char_list = context:faction():character_list();
			for i = 0, char_list:num_items() - 1 do
				current_char = char_list:item_at(i)
				if current_char:has_military_force() then
					local cqi = current_char:military_force():command_queue_index()
					cm:apply_effect_bundle_to_force("effect_bundle_force_siege_equipment_rebels", cqi, 0)
				end
			end
		end,
		true
	);
end

function show_how_to_play_event(faction_name, end_callback, delay)

	if not is_string(faction_name) then
		script_error("ERROR: show_how_to_play_event() called but supplied faction name [" .. tostring(faction_name) .. "] is not a string")
		return false
	end

	if end_callback and not is_function(end_callback) then
		script_error("ERROR: show_how_to_play_event() called but supplied end callback [" .. tostring(end_callback) .. "] is not a function")
		return false
	end;

	if delay and not is_number(delay) then
		script_error("ERROR: show_how_to_play_event() called but supplied end callback delay [" .. tostring(delay) .. "] is not a number")
		return false;
	end

	local title = "event_feed_strings_text_wh2_scripted_event_how_they_play_title"
	local primary_detail = "factions_screen_name_" .. faction_name
	local faction_to_secondary_detail_and_pic = {
		phar_main_tausret = 	{ secondary_detail = "event_feed_strings_text_troy_main_event_feed_string_scripted_event_intro_phthia_secondary_detail", pic = 1018 },
		phar_main_kurunta = 	{ secondary_detail = "event_feed_strings_text_troy_main_event_feed_string_scripted_event_intro_phthia_secondary_detail", pic = 1018 },
		phar_main_ramesses = 	{ secondary_detail = "event_feed_strings_text_troy_main_event_feed_string_scripted_event_intro_phthia_secondary_detail", pic = 1018 },
		phar_main_seti = 		{ secondary_detail = "event_feed_strings_text_troy_main_event_feed_string_scripted_event_intro_phthia_secondary_detail", pic = 1018 },
		phar_main_suppiluliuma ={ secondary_detail = "event_feed_strings_text_troy_main_event_feed_string_scripted_event_intro_phthia_secondary_detail", pic = 1018 },
		phar_main_amenmesse = 	{ secondary_detail = "event_feed_strings_text_troy_main_event_feed_string_scripted_event_intro_phthia_secondary_detail", pic = 1018 },
		phar_main_mefka_qes = 	{ secondary_detail = "event_feed_strings_text_troy_main_event_feed_string_scripted_event_intro_phthia_secondary_detail", pic = 1018 },
		phar_main_irsu = 		{ secondary_detail = "event_feed_strings_text_troy_main_event_feed_string_scripted_event_intro_phthia_secondary_detail", pic = 1018 },
		phar_main_bay = 		{ secondary_detail = "event_feed_strings_text_troy_main_event_feed_string_scripted_event_intro_phthia_secondary_detail", pic = 1018 },
	}
	local secondary_detail = faction_to_secondary_detail_and_pic[faction_name].secondary_detail or "" 	-- table name, undescore, column (text), underscore, key
	local pic = faction_to_secondary_detail_and_pic[faction_name].pic or nil
	delay = delay or 0

	cm:show_message_event(
		faction_name,
		title,
		primary_detail,
		secondary_detail,
		true,
		pic,
		end_callback,
		delay,
		false
	)
end

function start_player_bankrupt_listeners()
	core:add_listener(
		"Player_Bankrupt",
		"PooledResourceShortageEvent",
		function(context)
			return context:faction():is_human()
		end,
		function(context)
			local faction = context:faction()
			local resource = context:resource()
			local resource_key = resource:key()
			local num_turns = resource:turns_of_shortage()
			local bundle
			if player_bankrupt_bundles[resource_key] and player_bankrupt_bundles[resource_key][num_turns] then
				bundle = player_bankrupt_bundles[resource_key][num_turns]
			elseif player_bankrupt_bundles[resource_key] and num_turns > #player_bankrupt_bundles[resource_key] then
				bundle = player_bankrupt_bundles[resource_key][#player_bankrupt_bundles[resource_key]]
			end
			out(bundle)
			if faction:has_effect_bundle(bundle) then
				return
			else
				cm:apply_effect_bundle(bundle, faction:name(), -1)
			end
		end,
		true
	)
	core:add_listener(
		"Player_Bankruptcy_Ended",
		"PooledResourceShortageEndedEvent",
		function(context)
			return context:faction():is_human()
		end,
		function(context)
			local faction = context:faction()
			local resource = context:resource()
			local resource_key = resource:key()
			local bundles_to_remove = player_bankrupt_bundles[resource_key]
			if is_table(bundles_to_remove) then
				for k,v in pairs(bundles_to_remove) do
					if faction:has_effect_bundle(v) then
						cm:remove_effect_bundle(v,faction:name())
					end
				end
			end
		end,
		true
	)
end


core:add_listener(
	"Give_universal_income",
	"FirstTickAfterNewCampaignStarted",
	true,
	function(context)
		local effect_bundles_config = {
			{
				effect_bundle_key = "phar_main_universal_background_income_people",
				effect_bundle_duration = 31
			},
			{
				effect_bundle_key = "phar_main_universal_background_income_nobles",
				effect_bundle_duration = 21
			},
			{
				effect_bundle_key = "phar_main_universal_background_income_priests",
				effect_bundle_duration = 13
			}

		}


		local factions_list = context:model():world():faction_list()
		for i=0, factions_list:num_items() -1 do
			
			local curr_faction = factions_list:item_at(i)
			local curr_faction_name = curr_faction:name()
			if curr_faction:is_human() then
				for i = 1, #effect_bundles_config do
					cm:apply_effect_bundle(effect_bundles_config[i].effect_bundle_key, curr_faction_name, effect_bundles_config[i].effect_bundle_duration)
				end
			end
			-- This call is necessary because even human factions have an AI faction underneath for evaluation purposes, and this call sets the base GDP for said purposes
			cm:faction_economics_recalculate_background_income(curr_faction_name)

		end
	end,
	true
)

player_bankrupt_bundles = {
	troy_food = {
		[1] = "effect_bundle_bankruptcy_food_1"
	},
	troy_wood = {
		[1] = "effect_bundle_bankruptcy_wood_1"
	},
	troy_stone = {
		[1] = "effect_bundle_bankruptcy_stone_1"
	},
	troy_bronze = {
		[1] = "effect_bundle_bankruptcy_bronze_1"
	},
	troy_gold = {
		[1] = "effect_bundle_bankruptcy_gold_1"
	}
}

start_pos_armies_to_beat = {
	--[[ 
	["troy_main_dan_achilles"] = {
		faction = "troy_main_dan_ellopians",
		--unit_list = "troy_spearmen,troy_spearmen,troy_spearmen,troy_spearmen,troy_achaean_stoneslingers,troy_achaean_spearmen,troy_light_swordsmen,troy_light_swordsmen",
		unit_list = {
			troy_historical = "troy_spearmen,troy_achaean_stoneslingers,troy_achaean_spearmen,troy_light_swordsmen",
			main_troy = "troy_spearmen,troy_achaean_stoneslingers,troy_achaean_spearmen,troy_light_swordsmen",
			troy_mythic = "troy_spearmen,troy_achaean_stoneslingers,troy_light_swordsmen,troy_mth_centaurs_spear_shield",
		},
		region = "troy_main_ellopia_histiaea",
		x_coordinate = 322,
		y_coordinate = 404
	},
	]]
	["phar_main_seti"] = {
		faction = "phar_main_mefka_qes",
		unit_list = {
			phar_main = "phar_main_nat_low_lower_egyptian_spear_militia,phar_main_nat_low_lower_egyptian_spear_militia,phar_main_nat_low_lower_egyptian_militia_slingers,phar_main_nat_low_lower_egyptian_militia_slingers,phar_main_nat_low_lower_egyptian_axe_conscripts"
		},
		traits = {
			"phar_main_background_1"
		},
		ancillaries = {
			"phar_main_common_equipment_spear",
			"phar_main_common_shield_small",
			"phar_main_common_armour_medium",
		},
		region = "phar_main_hardai_ur_gem",
		x_coordinate = 556,
		y_coordinate = 779
	},
	["phar_main_tausret"] = {
		faction = "phar_main_mes",
		unit_list = {
			phar_main = "phar_main_nat_upp_upper_egyptian_militia_slingers,phar_main_nat_upp_upper_egyptian_militia_slingers,phar_main_nat_upp_upper_egyptian_militia_clubmen,phar_main_nat_upp_upper_egyptian_militia_clubmen"
		},
		traits = {
			"phar_main_background_2"
		},
		ancillaries = {
			"phar_main_common_equipment_sword",
			"phar_main_common_shield_small",
			"phar_main_common_armour_light",
		},
		region = "phar_main_elephantine_hierakonpolis",
		x_coordinate = 560,
		y_coordinate = 552
	},
	["phar_main_amenmesse"] = {
		faction = "phar_main_kerma",
		unit_list = {
			phar_main = "phar_main_nat_nub_kushite_spearmen_recruits,phar_main_nat_nub_kushite_spearmen_recruits,phar_main_nat_nub_kushite_spearmen_recruits,phar_main_nat_nub_kushite_archers,phar_main_nat_nub_kushite_archers"
		},
		traits = {
			"phar_main_background_3"
		},
		ancillaries = {
			"phar_main_common_equipment_sword",
			"phar_main_common_shield_small",
			"phar_main_common_armour_light",
		},
		region = "phar_main_kerma_kerma",
		x_coordinate = 470,
		y_coordinate = 276
	},
	["phar_main_bay"] = {
		faction = "phar_main_hazor",
		unit_list = {
			phar_main = "phar_main_nat_fen_canaanite_sellswords,phar_main_nat_fen_canaanite_sellswords,phar_main_nat_fen_canaanite_rock_throwers,phar_main_nat_fen_canaanite_rock_throwers"
		},
		traits = {
			"phar_main_background_4"
		},
		ancillaries = {
			"phar_main_common_equipment_sword",
			"phar_main_common_shield_medium",
			"phar_main_common_armour_medium",
		},
		region = "phar_main_tyre_sidon",
		x_coordinate = 794,
		y_coordinate = 1090
	},
	["phar_main_suppiluliuma"] = {
		faction = "phar_main_kaska",
		unit_list = {
			phar_main = "phar_main_nat_hig_kaskian_tribesmen,phar_main_nat_hig_kaskian_tribesmen,phar_main_nat_hig_kaskian_tribesmen,phar_main_nat_hig_kaskian_axemen,phar_main_nat_hig_kaskian_axemen"
		},
		traits = {
			"phar_main_background_5"
		},
		ancillaries = {
			"phar_main_common_equipment_sword",
			"phar_main_common_shield_medium",
			"phar_main_common_armour_medium",
		},
		region = "phar_main_hattussa_hattussa",
		x_coordinate = 733,
		y_coordinate = 1495
	},
	["phar_main_kurunta"] = {
		faction = "phar_main_cibyra",
		unit_list = {
			phar_main = "phar_main_nat_isu_luwian_swordsmen,phar_main_nat_isu_luwian_swordsmen,phar_main_nat_isu_hittite_archers,phar_main_nat_isu_hittite_archers"
		},
		traits = {
			"phar_main_background_6"
		},
		ancillaries = {
			"phar_main_common_equipment_sword",
			"phar_main_common_shield_medium",
			"phar_main_common_armour_medium",
		},
		region = "phar_main_south_hatti_tarhuntassa",
		x_coordinate = 555,
		y_coordinate = 1271
	},
	["phar_sea_sherden"] = {
		faction = "phar_main_kizzuwatna",
		unit_list = {
			phar_main = "phar_main_nat_isu_luwian_spearmen,phar_main_nat_isu_luwian_spearmen,phar_main_nat_isu_isuwan_militia,phar_main_nat_isu_isuwan_militia,phar_main_nat_isu_isuwan_slingers,phar_main_nat_isu_isuwan_slingers"
		},
		ancillaries = {
			"phar_main_common_equipment_sword",
			"phar_main_common_shield_small",
			"phar_main_common_armour_medium",
		},
		region = "phar_main_tarsus_adana",
		x_coordinate = 771,
		y_coordinate = 1280,
		forename = "names_name_545590631"
	},
	["phar_sea_peleset"] = {
		faction = "phar_main_megiddo",
		unit_list = {
			phar_main = "phar_main_nat_fen_canaanite_sellswords,phar_main_nat_fen_canaanite_recruits,phar_main_nat_fen_canaanite_recruits,phar_main_nat_fen_canaanite_recruits,phar_main_nat_fen_canaanite_rock_throwers,phar_main_nat_fen_canaanite_rock_throwers"
		},
		ancillaries = {
			"phar_main_common_equipment_sword",
			"phar_main_common_shield_small",
			"phar_main_common_armour_medium",
		},
		region = "phar_main_megiddo_yapo",
		x_coordinate = 743,
		y_coordinate = 1030,
		forename = "names_name_5821036"
	},
}

start_pos_armies_to_beat_existing = {
	["phar_main_ramesses"] = {
		character_lookup_str = "faction:phar_main_sukhot,forename:1328216600"
	}
}

core:add_listener(
	"NewCampaignStarted_start_pos_armies_to_beat",
	"NewCampaignStarted",
	function(context)
		return not core:svr_load_bool("sbool_player_selected_first_turn_intro_on_frontend") or cm:is_multiplayer()
	end,
	function(context)
		local faction_list = context:model():world():faction_list()
		for i = 0, faction_list:num_items() - 1 do
			if faction_list:item_at(i):is_human() then
				spawn_start_pos_army_to_beat(faction_list:item_at(i))
			end
		end
	end,
	false
)

core:add_listener(
	"NewCampaignStarted_restrict_sea_people_occupation_decisions",
	"NewCampaignStarted",
	true,
	function(context)
		local affected_sea_people_faction_keys = {
			"phar_sea_denyen",
			"phar_sea_ekwesh",
			"phar_sea_lukka",
			"phar_sea_peleset",
			"phar_sea_shekelesh",
			"phar_sea_sherden",
			"phar_sea_teresh",
			"phar_sea_tjeker",
			"phar_sea_weshesh",
		}

		for _, key in ipairs(affected_sea_people_faction_keys) do
			local faction_interface = cm:get_faction(key)
			cm:disallow_faction_occupation_decision(faction_interface, "occupation_decision_occupy")
			cm:disallow_faction_occupation_decision(faction_interface, "occupation_decision_loot")
			cm:disallow_faction_occupation_decision(faction_interface, "occupation_decision_colonise")
		end
	end,
	false
)


core:add_listener(
	"model_created_query_start_turn_autosaves",
	"ModelCreated",
	true,
	function()
		-- Disable turn-start autosaves in the prologue
		local is_tutorial_mode_from_savegame = cm:get_saved_value("bool_is_tutorial_mode")
		local is_tutorial_mode_from_frontend = core:svr_load_bool("sbool_player_selected_first_turn_intro_on_frontend")

		local enable = not (is_tutorial_mode_from_frontend or is_tutorial_mode_from_savegame)
		cm:enable_start_turn_autosave(enable)
	end,
	false
)



function spawn_start_pos_army_to_beat(faction)
	local faction_name = faction:name()
	local campaign_name = cm:get_campaign_name()
	out("FACTION NAME " .. faction_name)
	if start_pos_armies_to_beat[faction_name] and start_pos_armies_to_beat[faction_name].subtype and start_pos_armies_to_beat[faction_name].forename then
		cm:create_force_with_general(
			start_pos_armies_to_beat[faction_name].faction,
			start_pos_armies_to_beat[faction_name].unit_list[campaign_name],
			start_pos_armies_to_beat[faction_name].region,
			start_pos_armies_to_beat[faction_name].x_coordinate,
			start_pos_armies_to_beat[faction_name].y_coordinate,
			"general",
			start_pos_armies_to_beat[faction_name].subtype,
			start_pos_armies_to_beat[faction_name].forename,
			"",
			"",
			"",
			false,
			function(cqi)
				if cqi then 
					local character = cm:get_character_by_cqi(cqi)
					cm:disable_movement_for_character("character_cqi:" .. tostring(cqi))
					if character and not character:is_null_interface() then
						cm:set_force_has_retreated_this_turn(character)

						if start_pos_armies_to_beat[faction_name].traits then
							for _, trait_key in ipairs(start_pos_armies_to_beat[faction_name].traits) do
								cm:force_add_trait("character_cqi:" .. tostring(cqi), trait_key, false, 1)
							end
						end

						if start_pos_armies_to_beat[faction_name].ancillaries then
							for _, ancillary_key in ipairs(start_pos_armies_to_beat[faction_name].ancillaries) do
								cm:force_add_ancillary("character_cqi:" .. tostring(cqi), ancillary_key, true)
							end
						end
					end
					start_pos_armies_to_beat[faction_name].cqi = cqi
					core:add_listener(
						"enable_movement_start_pos_army", 
						"FactionTurnEnd", 
						function(context)
							return context:faction():name() == faction_name and (cm:model():turn_number() == 1)
						end, 
						function(context)
							cm:enable_movement_for_character("character_cqi:" .. tostring(cqi))
						end, 
						false
					)
				end 
			end
		)
	else

		if start_pos_armies_to_beat[faction_name] then
			cm:create_force(
				start_pos_armies_to_beat[faction_name].faction,
				start_pos_armies_to_beat[faction_name].unit_list[campaign_name],
				start_pos_armies_to_beat[faction_name].region,
				start_pos_armies_to_beat[faction_name].x_coordinate,
				start_pos_armies_to_beat[faction_name].y_coordinate,
				true,
				function(cqi)
					if cqi then 
						local character = cm:get_character_by_cqi(cqi)
						cm:disable_movement_for_character("character_cqi:" .. tostring(cqi))
						if character and not character:is_null_interface() then
							cm:set_force_has_retreated_this_turn(character)
							
							if start_pos_armies_to_beat[faction_name].traits then
								for _, trait_key in ipairs(start_pos_armies_to_beat[faction_name].traits) do
									cm:force_add_trait("character_cqi:" .. tostring(cqi), trait_key, false, 1)
								end
							end
							
							if start_pos_armies_to_beat[faction_name].ancillaries then
								for _, ancillary_key in ipairs(start_pos_armies_to_beat[faction_name].ancillaries) do
									cm:force_add_ancillary("character_cqi:" .. tostring(cqi), ancillary_key, true)
								end
							end
						end
						start_pos_armies_to_beat[faction_name].cqi = cqi
						core:add_listener(
							"enable_movement_start_pos_army", 
							"FactionTurnEnd", 
							function(context)
								return context:faction():name() == faction_name and (cm:model():turn_number() == 1)
							end, 
							function(context)
								cm:enable_movement_for_character("character_cqi:" .. tostring(cqi))
							end, 
							false
						)
					end 
				end,
				false
			)
		end
	end
	
	if start_pos_armies_to_beat_existing and start_pos_armies_to_beat_existing[faction_name] then
		local lookup_str = start_pos_armies_to_beat_existing[faction_name].character_lookup_str
		local character = cm:get_character(lookup_str)
		cm:disable_movement_for_character(lookup_str)
		if character and not character:is_null_interface() then
			cm:set_force_has_retreated_this_turn(character)
		end
		core:add_listener(
			"enable_movement_start_pos_army_existing", 
			"FactionTurnEnd", 
			function(context)
				return context:faction():name() == faction_name and (cm:model():turn_number() == 1)
			end, 
			function(context)
				cm:enable_movement_for_character(lookup_str)
			end, 
			false
		)
	end

end

cm:add_first_tick_callback(
	function()
		setup_campaign()
	end
)