
-----------------------------------------------------------------------------------
-----------------------------------------------------------------------------------
--
--	Custom ui listeners
--
-----------------------------------------------------------------------------------
-----------------------------------------------------------------------------------

prepend_settlement_str = "settlement:";

-- Troy garrison replenishment after every battle. Range from 0.0 to 1.0
troy_city_post_battle_replenishment = 0.8
troy_city_region_key = "troy_main_ilion_troy"

-- outputs click information to the Lua - UI Script tab
output_uicomponent_on_click();

-- create some campaign helper objects
infotext = get_infotext_manager();
objectives = get_objectives_manager();
uim = cm:get_campaign_ui_manager();

-- we don't save override states in WH, which means that if an override is locked and
-- the game is saved, it should be unlocked when the game is loaded again
uim:set_should_save_override_state(false);

cm:set_use_cinematic_borders_for_automated_cutscenes(false);

-- load in export_advice/export_triggers/etc
-- this has to be run on script load as the first tick can be too late to apply
-- experience triggers and some other things post-battle
--[[ cm:add_pre_first_tick_callback(
	function()
		--cm:load_exported_files("export_helpers");
		--cm:load_exported_files("export_triggers");
		--cm:load_exported_files("export_ancillaries");
		--cm:load_exported_files("export_experience");

		-- load the experience triggers
		setup_experience_triggers();
	end
); ]]

intercontinental_diplomacy_turn = 70;
story_dilemma_max_trigger_turn = 40;

function setup_troy_campaign(exclude_battle_advice)

	out("setup_troy_campaign() called");

	out.inc_tab();

	-- start custom listeners for player actions
	-- these listeners usually trigger further events to notify external scripts (e.g. advice interventions) of player actions
	start_custom_listeners();

	-- add scripted building effects
	--Add_Building_Effect_Listeners();

	-- load battle script whenever a battle is launched from this campaign (this activates advice)
	if not exclude_battle_advice then
		add_battle_script_override();
	end;

	-- monitor for player confederation taking place
	start_confederation_listeners();

	local local_faction = cm:get_local_faction_name(true);

	if local_faction and cm:get_faction(local_faction) then
		-- monitor for player recruiting new armies
		--player_army_count_listener();

		-- enable movement for the player's faction if this is not a new game (just in case the player somehow saved in the middle of an intervention)
		if not cm:is_new_game() then
			cm:enable_movement_for_faction(local_faction);
		end;
	else
		out("Autorun running, not applying upkeep penalties for additional armies");
	end;

	-- monitor rebel armies, and give them siege equipment
	setup_rebel_army_siege_equipment_monitor()

	-- Start listening for player going bankrupt
	start_player_bankrupt_listeners()

	-- Start the Wrath of Posseidon related listeners
	start_wrath_of_posseidon_listeners()

	if not cm:is_multiplayer() and cm:get_campaign_name() ~= "phar_main" then
		start_odysseus_ruse_listeners()
		start_story_dilemma_listeners()
	end

	-- intercontinental diplomacy update
	local max_distance = cm:get_saved_value("intercontinental_diplomacy_available");

	if max_distance then
		update_international_diplomacy_listener(max_distance);
	end;

	stealing_the_palladium_listeners()

	out.dec_tab();
end;










function start_custom_listeners()

	local local_faction = cm:get_local_faction_name(true);

	-- don't start in multiplayer or autorun mode
	if cm:is_multiplayer() or not local_faction then
		return false;
	end;

	--local ui_root = core:get_ui_root();

	-- custom event generators
	-- these listen for events and conditions to occur and then fire custom script events when they do. Doing this greatly
	-- reduces the amount of work that the intervention system has to do (and the amount of output it generates)

	core:start_custom_event_generator("PanelOpenedCampaign", function(context) return context.string == "diplomacy_dropdown" end, "ScriptEventDiplomacyPanelOpened");
	core:start_custom_event_generator("PanelClosedCampaign", function(context) return context.string == "diplomacy_dropdown" end, "ScriptEventDiplomacyPanelClosed");

	-- ScriptEventPreBattlePanelOpened generated by campaign manager
	core:start_custom_event_generator("PanelClosedCampaign", function(context) return context.string == "popup_pre_battle" end, "ScriptEventPreBattlePanelClosed");

	core:start_custom_event_generator("PanelOpenedCampaign", function(context) return context.string == "popup_battle_results" end, "ScriptEventPostBattlePanelOpened");
	core:start_custom_event_generator("PanelClosedCampaign", function(context) return context.string == "popup_battle_results" end, "ScriptEventPostBattlePanelClosed");

	core:start_custom_event_generator("PanelOpenedCampaign", function(context) return context.string == "move_options" end, "ScriptEventMoveOptionsPanelOpened");

	-- core:start_custom_event_generator("PanelOpenedCampaign", function(context) return context.string == "appoint_new_general" end, "ScriptEventAppointNewGeneralPanelOpened");
	core:add_listener(
		"appoint_new_general_listener",
		"PanelOpenedCampaign",
		function(context)
			return context.string == "appoint_new_general";
		end,
		function()
			-- a hack: we trigger this event after a short delay as the panel hasn't been fully built when we get the PanelOpenedCampaign event
			cm:callback(function() core:trigger_event("ScriptEventAppointNewGeneralPanelOpened") end, 0.5);
		end,
		true
	);


	-- diplomacy button clicked
	core:start_custom_event_generator(
		"ComponentLClickUp",
		function(context) return UIComponent(context.component) == find_uicomponent(core:get_ui_root(), "faction_buttons_docker", "button_diplomacy") end,
		"ScriptEventPlayerOpensDiplomacyPanel"
	);

	-- diplomacy button shortcut used
	core:start_custom_event_generator(
		"ShortcutPressed",
		function(context) return context.string == "show_diplomacy" end,
		"ScriptEventPlayerOpensDiplomacyPanel"
	);

	-- diplomacy quick deal button
	core:start_custom_event_generator(
		"ComponentLClickUp",
		function(context)
			if UIComponent(context.component):Parent() then
				local uic_parent = UIComponent(UIComponent(context.component):Parent());
				return uic_parent:IsValid() and uic_parent:Id() == "quick_deal_submenu" and uicomponent_descended_from(uic_parent, "diplomacy_dropdown");
			end;
		end,
		"ScriptEventDiplomacyQuickDealButtonClicked"
	);

	-- raise lord button clicked
	core:start_custom_event_generator(
		"ComponentLClickUp",
		function(context) return UIComponent(context.component) == find_uicomponent(core:get_ui_root(), "character_panel", "raise_forces_options", "button_raise") end,
		"ScriptEventRaiseForceButtonClicked"
	);

	-- player settlement comes under siege
	core:start_custom_event_generator(
		"CharacterBesiegesSettlement",
		function(context) return context:region():owning_faction():name() == local_faction end,
		"ScriptEventPlayerBesieged",
		function(context) return context:region() end
	)

	core:start_custom_event_generator(
		"CharacterCreated",
		function(context) return context:character():faction():name() == local_faction end,
		"ScriptEventPlayerFactionCharacterCreated",
		function(context) return context:character() end
	);

	core:start_custom_event_generator(
		"BuildingCompleted",
		function(context) return context:garrison_residence():faction():name() == local_faction end,
		"ScriptEventPlayerBuildingCompleted",
		function(context) return context:building(), context:garrison_residence() end
	);

	core:start_custom_event_generator(
		"GarrisonOccupiedEvent",
		function(context) return context:character():faction():name() == local_faction end,
		"ScriptEventPlayerCaptureSettlement",
		function(context) return context:garrison_residence(), context:character() end
	);

	core:start_custom_event_generator(
		"RegionGainedDevlopmentPoint",
		function(context) return context:region():owning_faction():name() == local_faction end,
		"ScriptEventPlayerRegionGainedDevelopmentPoint",
		function(context) return context:region() end
	);

	core:start_custom_event_generator(
		"MilitaryForceDevelopmentPointChange",
		function(context) return context:military_force():faction():name() == local_faction and context:point_change() > 0 end,
		"ScriptEventPlayerMilitaryForceGainedDevelopmentPoint",
		function(context) return context:military_force() end
	);

	-- core:start_custom_event_generator(
	-- 	"CharacterSkillPointAvailable",
	-- 	function(context) return context:character():faction():name() == local_faction end,
	-- 	"ScriptEventPlayerCharacterSkillPointAvailable",
	-- 	function(context)
	-- 		return context:character();
	-- 	end
	-- );

	core:start_custom_event_generator(
		"CharacterFinishedMovingEvent",
		function(context) return context:character():faction():name() == local_faction end,
		"ScriptEventPlayerCharacterFinishedMovingEvent",
		function(context)
			return context:character();
		end
	);

	--
	core:add_listener(
		"ScriptEventPlayerCharacterPostFinishedMovingEvent",
		"CharacterFinishedMovingEvent",
		function(context)
			return context:character():faction():name() == local_faction;
		end,
		function(context)
			local char_cqi = context:character():command_queue_index();
			cm:callback(
				function()
					core:trigger_event("ScriptEventPlayerCharacterPostFinishedMovingEvent", cm:get_character_by_cqi(char_cqi));
				end,
				0.2
			);
		end,
		true
	);


	core:start_custom_event_generator(
		"PanelClosedCampaign",
		function(context)
			if context.string == "events" then
				-- test to see if the event_mission component is visible
				local uic = find_uicomponent(core:get_ui_root(), "events", "event_mission");

				if uic and uic:Visible() then
					return true;
				end;
			end;
			return false
		end,
		"ScriptEventPlayerAcceptsMission"
	);

	core:start_custom_event_generator(
		"CharacterRankUp",
		function(context)
			return context:character():faction():name() == local_faction;
		end,
		"ScriptEventPlayerCharacterRankUp",
		function(context)
			return context:character();
		end
	);

	core:start_custom_event_generator(
		"PanelOpenedCampaign",
		function(context)
			if context.string == "character_panel" then

				local uic_settlement = find_uicomponent(core:get_ui_root(), "hud_center", "button_group_settlement", "button_create_army");
				if uic_settlement and (uic_settlement:CurrentState() == "down" or uic_settlement:CurrentState() == "selected") then
					return true;
				end;

				-- horde army
				local uic_horde_army = find_uicomponent(core:get_ui_root(), "hud_center", "button_group_army_settled", "button_create_army");
				if uic_horde_army and (uic_horde_army:CurrentState() == "down" or uic_horde_army:CurrentState() == "selected") then
					return true;
				end;

				return false;
			end;

			return false;
		end,
		"ScriptEventRecruitLordPanelOpened"
	);


	-- post missionsucceeded listener
	-- Fires an additional event a short while after a mission has succeeded, allowing client scripts to know when a
	-- player mission's rewards have definitely* been received
	-- (*unsafe)
	core:add_listener(
		"post_player_missionsucceeded_listener",
		"MissionSucceeded",
		function(context)
			return context:faction():name() == local_faction;
		end,
		function(context)
			local mission_key = context:mission():mission_record_key();

			cm:callback(
				function()
					core:trigger_event("ScriptEventPlayerMissionSucceeded", mission_key);
				end,
				0.2
			);
		end,
		false
	);


	core:start_custom_event_generator(
		"PanelOpenedCampaign",
		function(context)
			if context.string == "character_panel" then

				local uic_settlement = find_uicomponent(core:get_ui_root(), "hud_center", "button_group_settlement", "button_create_army");
				if uic_settlement and (uic_settlement:CurrentState() == "down" or uic_settlement:CurrentState() == "selected") then
					return true;
				end;

				-- horde army
				local uic_horde_army = find_uicomponent(core:get_ui_root(), "hud_center", "button_group_army_settled", "button_create_army");
				if uic_horde_army and (uic_horde_army:CurrentState() == "down" or uic_horde_army:CurrentState() == "selected") then
					return true;
				end;

				return false;
			end;

			return false;
		end,
		"ScriptEventRecruitLordPanelOpened"
	);



	-- campaign interaction monitors
	-- these listen for the player interacting with the UI and store a flag of whether that interaction has occurred which other scripts can query

	-- has player closed unit exchange panel
	uim:add_campaign_panel_closed_interaction_monitor("unit_exchange_panel_closed", "unit_exchange");

	-- has player closed diplomacy panel
	uim:add_campaign_panel_closed_interaction_monitor("diplomacy_panel_closed", "dropdown_diplomacy");

	-- has player researched a technology
	uim:add_interaction_monitor("technology_researched", "ResearchStarted", function(context) return context:faction():name() == local_faction end);

	-- has player recruited a unit
	uim:add_interaction_monitor("unit_recruited", "RecruitmentItemIssuedByPlayer", function() return true end);

	-- has player constructed a building
	uim:add_interaction_monitor("building_constructed", "BuildingConstructionIssuedByPlayer", function() return true end);

	-- has player assigned a character to office
	uim:add_interaction_monitor("office_assigned", "CharacterAssignedToPost", function(context) return context:character():faction():name() == local_faction end);

	-- has player captured a settlement
	uim:add_interaction_monitor("settlement_captured", "GarrisonOccupiedEvent", function(context) return context:character():faction():name() == local_faction end);

	-- has player raised a force
	uim:add_interaction_monitor("force_raised", "ScriptEventRaiseForceButtonClicked");

	-- has player autoresolved
	uim:add_interaction_monitor(
		"autoresolve_selected",
		"ComponentLClickUp",
		function(context)
			local uic = UIComponent(context.component);
			return uic:Id() == "button_autoresolve" and uicomponent_descended_from(uic, "popup_pre_battle");
		end
	);

	-- monitor for player stances
	core:add_listener(
		"player_stance_monitor",
		"ForceAdoptsStance",
		true,
		function(context)
			local mf = context:military_force();
			local stance = tostring(context:stance_adopted());

			-- out("ForceAdoptsStance event triggered, stance is " .. tostring(stance) .. " [" .. mf:active_stance() .. "]");

			if mf:faction():name() == local_faction then
				-- stance "0" is default
				if stance == "1" then
					-- march
					common.set_advice_history_string_seen("has_adopted_stance");
					common.set_advice_history_string_seen("march_stance");
					-- core:trigger_event("ScriptEventPlayerForceAdoptsForcedMarchStance", mf);
				elseif stance == "2" then
					-- ambush
					common.set_advice_history_string_seen("ambush_stance");
					common.set_advice_history_string_seen("has_adopted_stance");
					core:trigger_event("ScriptEventPlayerForceAdoptsAmbushStance", mf);
				elseif stance == "3" then
					-- raiding
					common.set_advice_history_string_seen("raiding_stance");
					common.set_advice_history_string_seen("has_adopted_stance");
					-- core:trigger_event("ScriptEventPlayerForceAdoptsRaidingStance", mf);

				-- elseif stance == "4" then
					-- encamped

				-- elseif stance == "5" then
					-- mustering
					-- common.set_advice_history_string_seen("mustering_stance");
					-- common.set_advice_history_string_seen("has_adopted_stance");	 -- doesn't count
					-- core:trigger_event("ScriptEventPlayerForceAdoptsMusteringStance", mf);
				end;

			else
				-- fire an event if the force is raiding the player's territory
				if stance == "3" or stance == "14" then
					if mf:has_general() then
						local char = mf:general_character();
						if char:has_region() then
							local owning_faction = char:region():owning_faction();
							if not owning_faction:is_null_interface() and owning_faction:name() == local_faction then
								core:trigger_event("ScriptEventForceRaidingPlayerTerritory", mf);
							end;
						end;
					end;
				end;
			end;
		end,
		true
	);

	-- get the campaign manager to send success/failure messages when hero actions are committed against the player faction
	cm:start_hero_action_listener(local_faction);

	-- get the campaign manager to send out a ScriptEventRegionRebels event after the FactionTurnEnd event (the RegionRebels event is sent before)
	cm:generate_region_rebels_event_for_faction(local_faction);

	-- close advisor on turn end if it was opened
	core:add_listener(
		"FactionTurnEnd_CloseAdvisor",
		"FactionTurnEnd",
		function(context) return context:faction():name() == local_faction end,
		function(context)
			local advisor = core:get_ui_root():SequentialFind("advice_interface")
			if advisor and advisor:Visible() then
				advisor:SetVisible(false)
			end
		end,
		true
	);

	-- store a flag per-campaign for the player razing
	if not cm:get_faction(local_faction):is_allowed_to_capture_territory() and not cm:get_saved_value("player_has_razed") then
		core:add_listener(
			"player_has_razed",
			"CharacterRazedSettlement",
			function(context)
				return context:character():faction():name() == local_faction;
			end,
			function()
				cm:set_saved_value("player_has_razed", true);
			end,
			false
		);
	end;
end;



































--	Battle script override
--	Automatically loads a script in any battle launched from campaign. This activates advice in the battle.
function add_battle_script_override()
	cm:add_custom_battlefield(
		"generic",											-- string identifier
		0,													-- x co-ord
		0,													-- y co-ord
		5000,												-- radius around position
		false,												-- will campaign be dumped
		"",													-- loading override
		"script/battle/campaign_battle/battle_start.lua",	-- script override
		"",													-- entire battle override
		0,													-- human alliance when battle override
		false,												-- launch battle immediately
		true,												-- is land battle (only for launch battle immediately)
		false,												-- force application of autoresolver result
		false,												-- force a siege battle to be fought outside the settlement as a land battle
		false												-- disable fortification towers (for siege battles)
	);
end;


function remove_battle_script_override()
	cm:remove_custom_battlefield("generic");
end;



-- restrict confederation for duration of penalty
function start_confederation_listeners()
	core:add_listener(
		"confederation_listener",
		"FactionJoinsConfederation",
		true,
		function(context)
			local faction = context:confederation()
			local faction_name = faction:name()
			local faction_culture = faction:culture()
			local duration = 4
			if faction:is_human() then
				duration = 8
			elseif faction:name() == antagonist.current then 
				local player_faction = cm:get_faction(cm:get_local_faction_name(true))
				local player_strength = player_faction:strength()
				local antagonist_strength = faction:strength()

					if antagonist_strength/player_strength > 0.8 then
						duration = 99
					end
			end

			out("Restricting confederation between [faction:" .. faction_name .. "] and [culture:" .. faction_culture .. "]")
			cm:force_diplomacy("faction:" .. faction_name, "culture:" .. faction_culture, "form confederation", false, true, false)
				
			-- Confederation is possible trough force_confederation() and it is possible to have multiple "ScriptEventConfederationExpired" events for a single faction. This way, it's only one at a time.

			if is_table(cm.turn_countdown_events[faction_name]) then 
				
				for i = 1, #cm.turn_countdown_events[faction_name] do
					if cm.turn_countdown_events[faction_name][i].event_name == "ScriptEventConfederationExpired" then
						table.remove(cm.turn_countdown_events[faction_name], i);
					end;
				end;
			
				cm:add_turn_countdown_event(faction_name, duration, "ScriptEventConfederationExpired", faction_name)
			else
				cm:add_turn_countdown_event(faction_name, duration, "ScriptEventConfederationExpired", faction_name)
			end
		end,
		true
	)

	core:add_listener(
		"confederation_expired",
		"ScriptEventConfederationExpired",
		true,
		function(context)
			local faction_name = context.string
			local faction = cm:get_faction(faction_name)
			local culture = faction:culture()

			out("Unrestricting confederation between [faction:" .. faction_name .. "] and [culture: " .. culture .. "]")
			cm:force_diplomacy("faction:" .. faction_name, "culture:" .. culture, "form confederation", true, true, false)

			--Another one of them special cases
			if antagonist.current ~= "" then 
				cm:force_diplomacy("faction:" .. faction_name, "faction:" .. antagonist.current, "form confederation", false, true, false)
			end
		end,
		true
	)
end

-- increase upkeep for each additional army the player recruits or obtains via confederation
function player_army_count_listener()

	-- apply the effect bundles every time the player turn starts
	core:add_listener(
		"player_army_turn_start_listener",
		"FactionTurnStart",
		function(context)
			return upkeep_penalty_condition(context:faction())
		end,
		function(context)
			apply_upkeep_penalty(context:faction())
		end,
		true
	)

	-- apply the effect bundles every time the player creates a new force
	core:add_listener(
		"player_army_created_listener",
		"MilitaryForceCreated",
		function(context)
			return upkeep_penalty_condition(context:military_force_created():faction())
		end,
		function(context)
			apply_upkeep_penalty(context:military_force_created():faction())
		end,
		true
	)

	-- apply the effect bundles every time the player confederates
	core:add_listener(
		"confederation_player_army_count_listener",
		"FactionJoinsConfederation",
		function(context)
			return upkeep_penalty_condition(context:confederation())
		end,
		function(context)
			apply_upkeep_penalty(context:confederation())
		end,
		true
	)
end

function upkeep_penalty_condition(faction)
	return faction:is_human() and faction:is_allowed_to_capture_territory()
end

-- loop through the player's armys and apply
function apply_upkeep_penalty(faction)
	local difficulty = cm:model():combined_difficulty_level()

	local effect_bundle = "effect_bundle_supply_lines_easy"

	if difficulty == 0 then
		effect_bundle = "effect_bundle_supply_lines_normal"
	elseif difficulty == -1 then
		effect_bundle = "effect_bundle_supply_lines_hard"
	elseif difficulty == -2 then
		effect_bundle = "effect_bundle_supply_lines_very_hard"
	elseif difficulty == -3 then 
		effect_bundle = "effect_bundle_supply_lines_legendary"
	end
	
	local mf_list = faction:military_force_list()
	local num_items = mf_list:num_items()

	-- go through every general the player has, ignoring the first, and apply the effect bundles
	for i = 1, mf_list:num_items() - 1 do
		current_mf = mf_list:item_at(i)

		if not current_mf:is_armed_citizenry() and not current_mf:has_effect_bundle(effect_bundle) and current_mf:has_general() then
			--out.design("Adding supply line bundle to Military force with CQI : " .. tostring(current_mf:command_queue_index()))
			cm:apply_effect_bundle_to_characters_force(effect_bundle, current_mf:general_character():command_queue_index(), 0)
		end
	end
end


function setup_rebel_army_siege_equipment_monitor()
	core:add_listener(
		"rebel_army_monitor",
		"FactionTurnStart",
		function(context) return context:faction():name() == "rebels" end,
		function(context)
			local char_list = context:faction():character_list();
			for i = 0, char_list:num_items() - 1 do
				current_char = char_list:item_at(i)
				if current_char:has_military_force() then
					local cqi = current_char:military_force():command_queue_index()
					cm:apply_effect_bundle_to_force("effect_bundle_force_siege_equipment_rebels", cqi, 0)
				end
			end
		end,
		true
	);
end

function show_how_to_play_event(faction_name, end_callback, delay)

	if not is_string(faction_name) then
		script_error("ERROR: show_how_to_play_event() called but supplied faction name [" .. tostring(faction_name) .. "] is not a string")
		return false
	end

	if end_callback and not is_function(end_callback) then
		script_error("ERROR: show_how_to_play_event() called but supplied end callback [" .. tostring(end_callback) .. "] is not a function")
		return false
	end;

	if delay and not is_number(delay) then
		script_error("ERROR: show_how_to_play_event() called but supplied end callback delay [" .. tostring(delay) .. "] is not a number")
		return false;
	end

	local title = "event_feed_strings_text_wh2_scripted_event_how_they_play_title"
	local primary_detail = "factions_screen_name_" .. faction_name
	local secondary_detail = "" 	-- table name, undescore, column (text), underscore, key
	local pic = nil
	delay = delay or 0

	if faction_name == achilles_faction then
		secondary_detail = "event_feed_strings_text_troy_main_event_feed_string_scripted_event_intro_phthia_secondary_detail"
		pic = 1018;
	elseif faction_name == "troy_amazons_trj_hippolyta" then
		secondary_detail = "event_feed_strings_text_troy_dlc1_event_feed_string_scripted_event_intro_hippolyta_secondary_detail"
		pic = 1025;
	elseif faction_name == "troy_amazons_trj_penthesilea" then
		secondary_detail = "event_feed_strings_text_troy_dlc1_event_feed_string_scripted_event_intro_penthesilea_secondary_detail"
		pic = 1026;
	elseif faction_name == "troy_main_dan_ithaca" then
		secondary_detail = "event_feed_strings_text_troy_main_event_feed_string_scripted_event_intro_ithaca_secondary_detail"
		pic = 1020;
	elseif faction_name == "troy_main_dan_mycenae" then
		secondary_detail = "event_feed_strings_text_troy_main_event_feed_string_scripted_event_intro_mycaena_secondary_detail"
		pic = 1017;
	elseif faction_name == "troy_main_dan_sparta" then
		secondary_detail = "event_feed_strings_text_troy_main_event_feed_string_scripted_event_intro_sparta_secondary_detail"
		pic = 1019;
	elseif faction_name == "troy_main_trj_dardania" then
		secondary_detail = "event_feed_strings_text_troy_main_event_feed_string_scripted_event_intro_dardania_secondary_detail"
		pic = 1024;
	elseif faction_name == "troy_main_trj_lycia" then
		secondary_detail = "event_feed_strings_text_troy_main_event_feed_string_scripted_event_intro_sarpedon_secondary_detail"
		pic = 1023;
	elseif faction_name == "troy_main_trj_paris" then
		secondary_detail = "event_feed_strings_text_troy_main_event_feed_string_scripted_event_intro_paris_secondary_detail"
		pic = 1022;
	elseif faction_name == "troy_main_trj_hector" then
		secondary_detail = "event_feed_strings_text_troy_main_event_feed_string_scripted_event_intro_hector_secondary_detail"
		pic = 1021;
	elseif faction_name == "troy_main_dan_salamis" then
		secondary_detail = "event_feed_strings_text_troy_adi_event_feed_string_scripted_event_intro_ajax_secondary_detail"
		pic = 1110;
	elseif faction_name == "troy_main_dan_argos" then 
		secondary_detail = "event_feed_strings_text_troy_adi_event_feed_string_scripted_event_intro_diomedes_secondary_detail"
		pic = 1111;
	elseif faction_name == "troy_rem_trj_thrace" then 
		secondary_detail = "event_feed_strings_text_troy_rem_event_feed_string_scripted_event_intro_rhesus_secondary_detail"
		pic = 2120;
	elseif faction_name == "troy_rem_horde_aethiopians" then 
		secondary_detail = "event_feed_strings_text_troy_rem_event_feed_string_scripted_event_intro_memnon_secondary_detail"
		pic = 2115;
	else
		script_error("ERROR: show_how_to_play_event() called but couldn't recognise supplied faction name [" .. faction_name .. "]")
		return false;
	end

	cm:show_message_event(
		faction_name,
		title,
		primary_detail,
		secondary_detail,
		true,
		pic,
		end_callback,
		delay,
		false
	)
end


-- trigger quests (data is set up in the respective campaign folder)
function set_up_rank_up_listener(quests, subtype, infotext)
	for i = 1, #quests do
		-- grab some local data for this quest record
		local current_quest_record = quests[i];

		local current_type = current_quest_record[1];
		local current_ancillary_key = current_quest_record[2];
		local current_mission_key = current_quest_record[3];
		local current_rank_req = current_quest_record[4];
		local current_mp_mission_key = current_quest_record[5];
		local current_advice_key = current_quest_record[6];
		local current_x = current_quest_record[7];
		local current_y = current_quest_record[8];
		local current_region_key = current_quest_record[9];
		local current_suppress_for_local_player_in_sp = current_quest_record[10];
		local current_intervention_name = false;
		local current_saved_name = false;

		if current_mission_key then
			current_intervention_name = "in_" .. current_mission_key;
			current_saved_name = current_mission_key .. "_issued";
		else
			-- ai only, we don't have a mission for the player
			current_saved_name = current_ancillary_key .. "_issued";
		end;

		out.design("[Quests] establishing rank up listener for char type [" .. subtype .. "] and rank [" .. current_rank_req .. "] for mission [" .. tostring(current_mission_key) .. "]");
		out.design("\tadvice key is " .. tostring(current_advice_key) .. ", x is " .. tostring(current_x) .. " and y is " .. tostring(current_y));

		-- pre-declare the intervention and trigger function, so that they exist in this scope as a local
		local current_intervention = false;
		local current_intervention_trigger = false;

		-- only establish the intervention properly in single-player mode, however
		if not cm:is_multiplayer() and current_intervention_name then
			out.design("\testablishing intervention as it's a singleplayer campaign");

			--------------------------------------------
			-- called when the intervention is triggered
			function current_intervention_trigger()
				out.design("[Quests] intervention triggering for [" .. current_mission_key .. "], character subtype [" .. subtype .. "]");

				-- save this value in order to not issue this quest multiple times
				cm:set_saved_value(current_saved_name, true);

				-- stop listener
				core:remove_listener(current_mission_key);

				-- set up a mission manager to trigger
				local mm = mission_manager:new(cm:get_local_faction_name(), current_mission_key);
				if current_type == "dilemma" then
					mm:set_is_dilemma_in_db();
					out.design("\tthis quest is a dilemma");
				elseif current_type == "incident" then
					mm:set_is_incident_in_db();
					out.design("\tthis quest is an incident");
				else
					mm:set_is_mission_in_db();
					out.design("\tthis quest is a mission");
				end;

				if core:is_advice_level_minimal() then
					out.design("\tjust issuing mission, advice level is minimal");

					-- advice is set to minimal, just trigger the mission
					mm:trigger(function() current_intervention:complete() end);
					return;
				end;

				-- decide whether to show infotext or not
				local infotext_to_show = false
				if not common.get_advice_history_string_seen("quests_infotext") then
					infotext_to_show = infotext;
					common.set_advice_history_string_seen("quests_infotext");
				end;

				if current_advice_key and current_x and current_y then
					out.design("\tscrolling the camera with advice");

					-- we have advice to deliver and a position
					current_intervention:scroll_camera_for_intervention(
						current_region_key,
						current_x,
						current_y,
						current_advice_key,
						infotext_to_show,
						mm,
						4
					);
				elseif current_advice_key then
					-- we have advice, but no position
					out.design("\tplaying advice with no camera movement");

					current_intervention:play_advice_for_intervention(
						current_advice_key,
						infotext_to_show,
						mm
					);
				elseif current_x and current_y then
					-- we have a position but no advice
					out.design("\tscrolling camera with no advice");

					local cam_x, cam_y, cam_d, cam_b, cam_h = cm:get_camera_position();

					local cutscene = campaign_cutscene:new(
						current_mission_key,
						4,
						function()
							-- trigger mission when cutscene finishes
							mm:trigger(
								function()
									-- restore shroud and complete when mission is accepted
									cm:restore_shroud_from_snapshot();
									current_intervention:complete()
								end
							);
						end
					);

					cutscene:set_skippable(true);
					cutscene:set_skip_camera(current_x, current_y, cam_d, cam_b, cam_h);
					cutscene:set_disable_settlement_labels(false);
					cutscene:set_dismiss_advice_on_end(false);
					cutscene:set_restore_shroud(false);

					-- make the target region visible if we have one
					if current_region_key then
						cutscene:action(function() cm:make_region_visible_in_shroud(cm:get_local_faction_name(), current_region_key) end, 0);
					end;
					cutscene:action(function() cm:scroll_camera_from_current(true, 4, {current_x, current_y, cam_d, cam_b, cam_h}) end, 0);

					cutscene:start();
				else
					-- we have no position or advice, just trigger
					out.design("\tno advice or position to scroll to, just issuing mission");

					mm:trigger(function() current_intervention:complete() end);
				end;
			end;
			--------------------------------------------
			--------------------------------------------

			-- declare the intervention itself
			current_intervention = intervention:new(
				current_intervention_name,							-- string name
				0,	 												-- cost
				function() current_intervention_trigger() end,		-- trigger callback
				BOOL_INTERVENTIONS_DEBUG	 						-- show debug output
			);
		end;

		-- establish listeners for this character rank-up event if the quest chain has not already been started
		if cm:get_saved_value(current_saved_name) then
			out.design("\tthis quest has already been triggered, not establishing listeners");
		else
			out.design("\tthis quest has not been triggered, establishing listeners");

			-- listen for the character ranking up
			core:add_listener(
				current_ancillary_key,
				"CharacterTurnStart",
				function(context)
					return context:character():character_subtype(subtype) and context:character():rank() >= current_rank_req
				end,
				function(context)
					local character = context:character();
					out.design("[Quests] Character [" .. cm:char_lookup_str(character) .. "] of subtype [" .. subtype .. "] has achieved rank [" .. current_rank_req .. "]");

					-- if the character is player controlled then begin the quest chain
					if character:faction():is_human() then
						if cm:is_multiplayer() then
							-- save this value in order to not issue this quest multiple times
							cm:set_saved_value(current_saved_name, true);	-- don't do this if the intervention is going to be triggered

							-- character is player-controlled and this is a multiplayer game, trigger the mission/dilemma etc
							if current_type == "mission" then
								if current_mp_mission_key then
									current_mission_key = current_mp_mission_key;
								end;

								out.design("\tcharacter is player controlled and this is an mp game, triggering mission " .. current_mission_key);
								cm:trigger_mission(character:faction():name(), current_mission_key, true);
							elseif current_type == "dilemma" then
								out.design("\tcharacter is player controlled and this is an mp game, triggering dilemma " .. current_mission_key);
								cm:trigger_dilemma(character:faction():name(), current_mission_key, true);
							elseif current_type == "incident" then
								out.design("\tcharacter is player controlled and this is an mp game, triggering incident " .. current_mission_key);
								cm:trigger_incident(character:faction():name(), current_mission_key, true);
							elseif current_type == "ai_only" then
								-- don't do anything
							else
								out.design("\tcouldn't determine mission type [" .. tostring(current_type) .. "] - see script error");
								script_error("ERROR: Tried to start a quest, but the event type [" .. tostring(current_type) .. " could not be parsed!");
							end;
						elseif current_mission_key then
							if current_suppress_for_local_player_in_sp then
								out.design("\tthis is a single-player campaign, and we've been told to suppress triggering of this event if the character belongs to the local player and this is the case - not triggering a message for the intervention");
							else
								-- character is player-controlled and this is a single-player game, sending a scriptevent that will trigger the intervention
								out.design("\tthis is a single-player campaign, triggering a message for the intervention");
								core:trigger_event("ScriptEventTriggerQuestChain", current_mission_key);
							end;
						end;
					else
						out.design("\tcharacter is not player-controlled, immediately giving them ancillary [" .. current_ancillary_key .. "]");

						-- save this value in order to not issue this quest multiple times
						cm:set_saved_value(current_saved_name, true);

						-- character is AI-controlled, give them the ancillary
						cm:force_add_ancillary(cm:char_lookup_str(character), current_ancillary_key);
					end;
				end,
				false
			);

			-- if it's a single-player game, then set up the intervention monitors
			if not cm:is_multiplayer() and current_intervention then
				-- listen for the scriptevent message, triggered from the monitor above if the player levels up a char on their turn
				current_intervention:add_trigger_condition(
					"ScriptEventTriggerQuestChain",
					function(context)
						return context.string == current_mission_key;
					end
				);

				current_intervention:start();
			end;
		end;
	end;
end;



function set_up_backup_mission(origin_mission, backup_mission, subtype)
	core:add_listener(
		origin_mission .. "_backup",
		"MissionGenerationFailed",
		function(context) return context:mission() == origin_mission end,
		function()
			out("Could not issue quest chain mission key [" .. origin_mission .. "] to faction owning agent subtype [" .. subtype .. "] - going to issue mission key [ " .. backup_mission .. "]");

			-- get the character's faction name, it might have changed if they've been confederated
			local faction_name = nil;
			local faction_list = cm:model():world():faction_list();

			for i = 0, faction_list:num_items() - 1 do
				local current_faction = faction_list:item_at(i);
				local char_list = current_faction:character_list();

				for j = 0, char_list:num_items() - 1 do
					local current_char = char_list:item_at(j);

					if current_char:character_subtype(subtype) then
						faction_name = current_char:faction():name();
						break;
					end;
				end;

				if faction_name then
					break;
				end;
			end;

			if faction_name then
				cm:trigger_mission(faction_name, backup_mission, true);
			end;
		end,
		false
	);
end;

function start_player_bankrupt_listeners()
	core:add_listener(
		"Troy_Player_Bankrupt",
		"PooledResourceShortageEvent",
		function(context)
			return context:faction():is_human()
		end,
		function(context)
			local faction = context:faction()
			local resource = context:resource()
			local resource_key = resource:key()
			local num_turns = resource:turns_of_shortage()
			local bundle
			if player_bankrupt_bundles[resource_key] and player_bankrupt_bundles[resource_key][num_turns] then
				bundle = player_bankrupt_bundles[resource_key][num_turns]
			elseif player_bankrupt_bundles[resource_key] and num_turns > #player_bankrupt_bundles[resource_key] then
				bundle = player_bankrupt_bundles[resource_key][#player_bankrupt_bundles[resource_key]]
			end
			out(bundle)
			if faction:has_effect_bundle(bundle) then
				return
			else
				cm:apply_effect_bundle(bundle, faction:name(), -1)
			end
		end,
		true
	)
	core:add_listener(
		"Troy_Player_Bankruptcy_Ended",
		"PooledResourceShortageEndedEvent",
		function(context)
			return context:faction():is_human()
		end,
		function(context)
			local faction = context:faction()
			local resource = context:resource()
			local resource_key = resource:key()
			local bundles_to_remove = player_bankrupt_bundles[resource_key]
			if is_table(bundles_to_remove) then
				for k,v in pairs(bundles_to_remove) do
					if faction:has_effect_bundle(v) then
						cm:remove_effect_bundle(v,faction:name())
					end
				end
			end
		end,
		true
	)
end


-- disabling universal background for Phar. Moved to DaVE via the faction_potential 
--[[
core:add_listener(
	"Give_universal_income",
	"FirstTickAfterNewCampaignStarted",
	true,
	function(context)
		local factions_list = context:model():world():faction_list()
		for i=0, factions_list:num_items() -1 do
			local curr_faction = factions_list:item_at(i)
			local curr_faction_name = curr_faction:name()

			if curr_faction_name == penthesilea_faction or curr_faction_name == "troy_rem_horde_aethiopians" then
				cm:apply_effect_bundle("effect_bundle_dlc1_horde_universal_background_income", curr_faction_name, -1)
			elseif curr_faction:is_major() then
				cm:apply_effect_bundle("effect_bundle_additional_universal_background_income", curr_faction_name, -1)
			else
				cm:apply_effect_bundle("effect_bundle_universal_background_income", curr_faction_name, -1)
			end

			--local extra_bundle = cm:create_new_custom_effect_bundle("effect_bundle_additional_universal_background_income")
			--extra_bundle:set_duration(0)

			--if not curr_faction:is_human() and curr_faction:is_major() or curr_faction_name == "troy_main_trj_troy" then

			--	local extra_bundle = cm:create_new_custom_effect_bundle("effect_bundle_additional_universal_background_income")
			--	extra_bundle:set_duration(0)

			--	local difficulty = cm:model():combined_difficulty_level()
			--	local bonus = 1000
			--	local exp_bonus = 250
			--	if difficulty == 0 then
			--		bonus = 2000
			--		exp_bonus = 300
			--	elseif difficulty == -1 then
			--		bonus = 3000
			--		exp_bonus = 350
			--	elseif difficulty == -2 then
			--		bonus = 4000
			--		exp_bonus = 400
			--	elseif difficulty == -3 then
			--		bonus = 5000
			--		exp_bonus = 450
			--	end
			--	extra_bundle:add_effect("troy_effect_economy_food_faction","faction_to_faction_own_unseen",bonus)
			--	if curr_faction_name == hippolyta_faction or curr_faction_name == penthesilea_faction then
			--		extra_bundle:add_effect("troy_effect_minimum_xp_gain_from_eligible_battle","faction_to_faction_own_unseen",exp_bonus)
			--	elseif curr_faction_name == "troy_main_trj_troy" then
			--		extra_bundle:add_effect("troy_effect_economy_food_faction","faction_to_faction_own_unseen",2500)
			--		extra_bundle:add_effect("troy_effect_event_add_bronze","faction_to_faction_own_unseen",300)
			--	end
			--	cm:apply_custom_effect_bundle_to_faction(extra_bundle,curr_faction)

			--end 
			cm:faction_economics_recalculate_background_income(curr_faction_name)
		end
	end,
	true
)
]]
player_bankrupt_bundles = {
	troy_food = {
		[1] = "effect_bundle_bankruptcy_food_1"
	},
	troy_wood = {
		[1] = "effect_bundle_bankruptcy_wood_1"
	},
	troy_stone = {
		[1] = "effect_bundle_bankruptcy_stone_1"
	},
	troy_bronze = {
		[1] = "effect_bundle_bankruptcy_bronze_1"
	},
	troy_gold = {
		[1] = "effect_bundle_bankruptcy_gold_1"
	}
}

-- Setup for marking regions qith access to mythological units and notifying the player when such region is acquired
mythological_unit_sets = {
	troy_myth_centaurs  = { "ui/skins/default/sp_icon_centaur.png", "city_info_bar_myth_centaurs",  "event_feed_strings_text_troy_main_event_feed_myth_units_giants_secondary_detail" },
	troy_mth_legacy_giants_only_for_ui_usage	= { "ui/skins/default/sp_icon_giant.png",		"city_info_bar_myth_giants",	"event_feed_strings_text_troy_main_event_feed_myth_units_giants_secondary_detail" },
	troy_myth_minotaurs = { "ui/skins/default/sp_icon_minotaur.png",	"city_info_bar_myth_minotaurs", "event_feed_strings_text_troy_main_event_feed_myth_units_minotaur_secondary_detail" },
	troy_myth_sirens = {"ui/skins/default/sp_icon_siren.png", 	   "city_info_bar_myth_sirens",	"event_feed_strings_text_troy_main_event_feed_myth_units_sirens_secondary_detail"},
	troy_myth_harpies = {"ui/skins/default/sp_icon_harpy.png", 	   "city_info_bar_myth_harpies",   "event_feed_strings_text_troy_main_event_feed_myth_units_harpies_secondary_detail"},
	troy_mth_sirens = {"ui/skins/default/sp_icon_siren.png", 	   "city_info_bar_myth_sirens",	"event_feed_strings_text_troy_main_event_feed_myth_units_sirens_secondary_detail"},
	troy_mth_harpy = {"ui/skins/default/sp_icon_harpy.png", 	   "city_info_bar_myth_harpies",   "event_feed_strings_text_troy_main_event_feed_myth_units_harpies_secondary_detail"},

}

mythological_building_slot = {
	troy_main_settlement_stone_sea_secondary_myth_minotaur = { "troy_myth_minotaurs", "ui/skins/default/sp_icon_minotaur.png",	"city_info_bar_myth_minotaurs",  "event_feed_strings_text_troy_main_event_feed_myth_units_minotaur_secondary_detail" },
	troy_main_special_knossos_secondary = { "troy_myth_minotaurs", "ui/skins/default/sp_icon_minotaur.png",						 "city_info_bar_myth_minotaurs",  "event_feed_strings_text_troy_main_event_feed_myth_units_minotaur_secondary_detail" },
	troy_main_settlement_major_sea_secondary_myth_cyclops = {"troy_myth_cyclops",	 "ui/skins/default/sp_icon_cyclops.png",	 "city_info_bar_myth_cyclops",	"event_feed_strings_text_troy_main_event_feed_myth_units_centaurs_secondary_detail" },
	troy_main_settlement_forest_sea_secondary_myth_corybantes = {"troy_myth_corybantes", "ui/skins/default/sp_icon_corybantes.png", "city_info_bar_myth_corybantes", "event_feed_strings_text_troy_main_event_feed_myth_units_corybantes_secondary_detail"},
	troy_main_settlement_stone_sea_secondary_myth_corybantes = {"troy_myth_corybantes", "ui/skins/default/sp_icon_corybantes.png",  "city_info_bar_myth_corybantes", "event_feed_strings_text_troy_main_event_feed_myth_units_corybantes_secondary_detail"},
	troy_main_settlement_major_secondary_myth_spartoi = {"troy_myth_spartoi", "ui/skins/default/sp_icon_spartoi.png", 	   	   		 "city_info_bar_myth_spartoi",	"event_feed_strings_text_troy_main_event_feed_myth_units_spartoi_secondary_detail"},
	troy_main_settlement_major_sea_secondary_myth_spartoi = {"troy_myth_spartoi", "ui/skins/default/sp_icon_spartoi.png", 	   		 "city_info_bar_myth_spartoi",	"event_feed_strings_text_troy_main_event_feed_myth_units_spartoi_secondary_detail"},
	troy_main_settlement_stone_sea_secondary_myth_seer = {"troy_myth_seer", "ui/skins/default/sp_icon_landmark_settlement.png",   		   		 "city_info_bar_important_settlement", 	  "event_feed_strings_text_troy_main_event_feed_myth_units_seer_secondary_detail" },
	troy_main_settlement_gold_secondary_myth_seer = {"troy_myth_seer", "ui/skins/default/sp_icon_landmark_settlement.png",   		   			 "city_info_bar_important_settlement", 	  "event_feed_strings_text_troy_main_event_feed_myth_units_seer_secondary_detail"},
	troy_main_settlement_bronze_sea_secondary_myth_gorgon = {"troy_myth_gorgon", "ui/skins/default/sp_icon_landmark_settlement.png",   		 "city_info_bar_important_settlement", 	  "event_feed_strings_text_troy_main_event_feed_myth_units_gorgon_secondary_detail"},
	troy_main_settlement_gold_sea_secondary_myth_gorgon = {"troy_myth_gorgon",   "ui/skins/default/sp_icon_landmark_settlement.png",   		 "city_info_bar_important_settlement",  	  "event_feed_strings_text_troy_main_event_feed_myth_units_gorgon_secondary_detail"}, 
	troy_main_settlement_forest_sea_secondary_myth_satyr = {"troy_myth_satyr", "ui/skins/default/sp_icon_landmark_settlement.png",   	   		 "city_info_bar_important_settlement", 	   "event_feed_strings_text_troy_main_event_feed_myth_units_satyr_secondary_detail"},
	troy_main_settlement_stone_secondary_myth_satyr = {"troy_myth_satyr", "ui/skins/default/sp_icon_landmark_settlement.png",   	   			 "city_info_bar_important_settlement", 	   "event_feed_strings_text_troy_main_event_feed_myth_units_satyr_secondary_detail"},
	troy_main_special_troy_primary = {"troy_myth_satyr", "ui/skins/default/sp_icon_landmark_settlement.png",   	   			 "city_info_bar_important_settlement", 	   "event_feed_strings_text_troy_main_event_feed_myth_important_settlement_secondary_detail"},
	troy_main_special_pylos_secondary_myth_centaurs = {"troy_myth_satyr", "ui/skins/default/sp_icon_landmark_settlement.png",   	   			 "city_info_bar_important_settlement", 	   "event_feed_strings_text_troy_main_event_feed_myth_important_settlement_secondary_detail"},
	troy_main_special_miletus_secondary = {"troy_myth_satyr", "ui/skins/default/sp_icon_landmark_settlement.png",   	   			 "city_info_bar_important_settlement", 	   "event_feed_strings_text_troy_main_event_feed_myth_important_settlement_secondary_detail"},
	troy_main_special_mycenae_secondary = {"troy_myth_satyr", "ui/skins/default/sp_icon_landmark_settlement.png",   	   			 "city_info_bar_important_settlement", 	   "event_feed_strings_text_troy_main_event_feed_myth_important_settlement_secondary_detail"},
	troy_main_settlement_forest_sea_secondary_myth_orion = {"troy_myth_satyr", "ui/skins/default/sp_icon_landmark_settlement.png",   	   			 "city_info_bar_important_settlement", 	   "event_feed_strings_text_troy_main_event_feed_myth_important_settlement_secondary_detail"},
	troy_main_settlement_forest_secondary_myth_orion = {"troy_myth_satyr", "ui/skins/default/sp_icon_landmark_settlement.png",   	   			 "city_info_bar_important_settlement", 	   "event_feed_strings_text_troy_main_event_feed_myth_important_settlement_secondary_detail"},
	troy_main_settlement_major_sea_secondary_myth_orion = {"troy_myth_satyr", "ui/skins/default/sp_icon_landmark_settlement.png",   	   			 "city_info_bar_important_settlement", 	   "event_feed_strings_text_troy_main_event_feed_myth_important_settlement_secondary_detail"},
	troy_hep_special_settlement_ios_secondary_myth_orion = {"troy_myth_satyr", "ui/skins/default/sp_icon_landmark_settlement.png",   	   			 "city_info_bar_important_settlement", 	   "event_feed_strings_text_troy_main_event_feed_myth_important_settlement_secondary_detail"},
	troy_hep_special_settlement_kos_secondary_myth_giant = {"troy_myth_satyr", "ui/skins/default/sp_icon_landmark_settlement.png",   	   			 "city_info_bar_important_settlement", 	   "event_feed_strings_text_troy_main_event_feed_myth_important_settlement_secondary_detail"},
	troy_hep_special_settlement_melos_secondary_myth_harpies = {"troy_myth_satyr", "ui/skins/default/sp_icon_landmark_settlement.png",   	   			 "city_info_bar_important_settlement", 	   "event_feed_strings_text_troy_main_event_feed_myth_important_settlement_secondary_detail"},
	troy_hep_special_settlement_poliochne_secondary = {"troy_myth_satyr", "ui/skins/default/sp_icon_landmark_settlement.png",   	   			 "city_info_bar_important_settlement", 	   "event_feed_strings_text_troy_main_event_feed_myth_important_settlement_secondary_detail"},
	troy_hep_special_settlement_thisbe_secondary = {"troy_myth_satyr", "ui/skins/default/sp_icon_landmark_settlement.png",   	   			 "city_info_bar_important_settlement", 	   "event_feed_strings_text_troy_main_event_feed_myth_important_settlement_secondary_detail"},
	troy_mth_special_settlement_dion_farm_secondary = {"troy_myth_satyr", "ui/skins/default/sp_icon_landmark_settlement.png",   	   			 "city_info_bar_important_settlement", 	   "event_feed_strings_text_troy_main_event_feed_myth_important_settlement_secondary_detail"},
}

mythical_unit_icons_for_odysseus = {
	myth_centaurs	= { "ui/skins/default/sp_icon_centaur.png", "city_info_bar_myth_centaurs",  "event_feed_strings_text_troy_main_event_feed_myth_units_giants_secondary_detail" },
	myth_sirens 	= {"ui/skins/default/sp_icon_siren.png", 	   "city_info_bar_myth_sirens",	"event_feed_strings_text_troy_main_event_feed_myth_units_sirens_secondary_detail"},
	myth_harpies	= {"ui/skins/default/sp_icon_harpy.png", 	   "city_info_bar_myth_harpies",   "event_feed_strings_text_troy_main_event_feed_myth_units_harpies_secondary_detail"},
	myth_giants		= { "ui/skins/default/sp_icon_giant.png",		"city_info_bar_myth_giants",	"event_feed_strings_text_troy_main_event_feed_myth_units_giants_secondary_detail" },
}

core:add_listener(
	"FirstTickAfterWorldCreated_mythological_unit_icons",
	"FirstTickAfterWorldCreated",
	true,
	function(context)
		local faction_name = cm:get_local_faction_name(true)
		if faction_name then 
			if not cm:get_faction(faction_name):is_allowed_to_capture_territory() then
				return -- Hordes do not see the mythological unit icons b/c they cannot build the correspondng buildings. They can only receive the units as capture bonuses.
			elseif cm:get_campaign_name() == "troy_historical" then
				return -- These icons should not appear in the historical campaign
			end
		end

		local region_list = context:world():region_manager():region_list();
		

		for i = 0, region_list:num_items() - 1 do
			local region = region_list:item_at(i);
			local settlement = region:settlement()
			local slot_list = region:slot_list()
			local region_name = region:name()
			
			if faction_name == "troy_main_dan_ithaca" and not settlement:is_port() then 
				for k = 0, slot_list:num_items() - 1 do
					local slot = slot_list:item_at(k)
					if slot:type() == "primary" then
						for b_set, b_details in pairs(mythical_unit_icons_for_odysseus) do
							if string.find(slot:template_key(), "ody_settlement") and string.find(slot:template_key(), b_set) then
								cm:set_custom_settlement_info_icon(region_name, "icon_" .. b_set, b_details[1], b_details[2])
								cm:set_custom_settlement_info_icon_visibility(region_name, "icon_" .. b_set, true)
							end
						end	
					end
				end
			else
				for set, details in pairs(mythological_unit_sets) do
					if settlement:can_possibly_build_units_from_set(set) then
						cm:set_custom_settlement_info_icon(region_name, "icon_" .. set, details[1], details[2])
						cm:set_custom_settlement_info_icon_visibility(region_name, "icon_" .. set, true)
					end
				end
				for k = 0, slot_list:num_items() - 1 do
					local slot = slot_list:item_at(k)
					for b_set, b_details in pairs(mythological_building_slot) do
						if slot:template_key() == b_set then
							cm:set_custom_settlement_info_icon(region_name, "icon_" .. b_details[1], b_details[2], b_details[3])
							cm:set_custom_settlement_info_icon_visibility(region_name, "icon_" .. b_details[1], true)
						end
					end	
				end
			end
		end
	end
)

core:add_listener(
	"RegionFactionChangeEvent_access_to_mythological_units",
	"RegionFactionChangeEvent",
	function(context)
		local reg = context:region()
		return reg:owning_faction():is_human()
	end,
	function(context)
		local region = context:region()
		local settlement = region:settlement()
		local faction_name = region:owning_faction():name()

		if faction_name == "troy_main_dan_ithaca" and not settlement:is_port() then 
			local slot_list = region:slot_list()
			for k = 0, slot_list:num_items() - 1 do
				local slot = slot_list:item_at(k)
				if slot:type() == "primary" then
					for b_set, b_details in pairs(mythical_unit_icons_for_odysseus) do
						if string.find(slot:template_key(), "ody_settlement") and string.find(slot:template_key(), b_set) and not (cm:get_campaign_name() == "troy_historical") then
							local title = "event_feed_strings_text_troy_main_event_feed_myth_units_unlock_title"
							local pic = 1040
							local primary_detail = "regions_onscreen_" .. region:name()
							local secondary_detail = b_details[3]

							cm:show_message_event(
								faction_name,
								title,
								primary_detail,
								secondary_detail,
								true,
								pic,
								end_callback,
								delay,
								false
							)
						end
					end	
				end
			end
		else
			for set, details in pairs(mythological_unit_sets) do
				if settlement:can_possibly_build_units_from_set(set) and not (cm:get_campaign_name() == "troy_historical") then
					local title = "event_feed_strings_text_troy_main_event_feed_myth_units_unlock_title"
					local pic = 1040
					local primary_detail = "regions_onscreen_" .. region:name()
					local secondary_detail = details[3]

					cm:show_message_event(
						faction_name,
						title,
						primary_detail,
						secondary_detail,
						true,
						pic,
						end_callback,
						delay,
						false
					)
				end
			end
		end
	end,
	true
)

-- These sholdn't be necessary anymore
-- myth_unit_regions = {
-- 	troy_main_euboea_chalcis = "event_feed_strings_text_troy_main_event_feed_myth_units_giants_secondary_detail",
-- 	troy_main_melamphylos_dolyche = "event_feed_strings_text_troy_main_event_feed_myth_units_giants_secondary_detail",
-- 	troy_main_phrygia_medra = "event_feed_strings_text_troy_main_event_feed_myth_units_giants_secondary_detail",
-- 	troy_main_messenia_tegea = "event_feed_strings_text_troy_main_event_feed_myth_units_centaurs_secondary_detail",
-- 	troy_main_magnesia_meliboea = "event_feed_strings_text_troy_main_event_feed_myth_units_centaurs_secondary_detail",
-- 	troy_main_isthmos_kaunos = "event_feed_strings_text_troy_main_event_feed_myth_units_centaurs_secondary_detail",
-- 	troy_main_thrinacia_trinacria = "event_feed_strings_text_troy_main_event_feed_myth_units_cyclops_secondary_detail",
-- 	troy_main_lemnos_myrina  = "event_feed_strings_text_troy_main_event_feed_myth_units_cyclops_secondary_detail",
-- 	troy_main_rhodes_ialysos = "event_feed_strings_text_troy_main_event_feed_myth_units_cyclops_secondary_detail",
-- 	troy_main_ida_knossos = "event_feed_strings_text_troy_main_event_feed_myth_units_minotaur_secondary_detail",
-- 	troy_main_cyclades_minoa = "event_feed_strings_text_troy_main_event_feed_myth_units_minotaur_secondary_detail"
-- }

core:add_listener(
	"Gods_and_Favour_populate_tooltips",
	"PanelOpenedCampaign",
	function(context)
		return context.string == "gods_and_favor"
	end,
	function(context)
		local lookup_prefix = "ui_text_replacements_localised_text_"
		-- local fill_favours_text = function(god_name, favours_ordered)
		-- 	local favours_text = ""
		-- 	for favour_index = 1, #favours_ordered do
		-- 		local favour = favours_ordered[favour_index]
		-- 		local god_favour = favour[god_name]

		-- 		if god_favour ~= nil then
		-- 			if god_favour.loc_key ~= nil and god_favour.value ~= nil then
		-- 				favours_text = favours_text .. common.get_localised_string(lookup_prefix .. god_favour.loc_key) .. tostring(god_favour.value) .. "\n"
		-- 			elseif strings_table.loc_key ~= nil then
		-- 				favours_text = favours_text .. common.get_localised_string(lookup_prefix .. god_favour.loc_key) .. "\n"
		-- 			end
		-- 		end
		-- 	end

		-- 	return favours_text
		-- end

		-- for god_index = 1, #god_names_ordered do
		-- 	-- local god_name = god_names_ordered[god_index]
		-- 	-- local tooltip_text = ""

		-- 	-- local gains_text = fill_favours_text(god_name, gains_ordered)
		-- 	-- if gains_text ~= "" then
		-- 	-- 	tooltip_text = tooltip_text .. common.get_localised_string(lookup_prefix .. gods_panel_tooltip_gain_title[god_name].loc_key) .. "\n" .. gains_text .. "\n"
		-- 	-- end

		-- 	-- local losses_text = fill_favours_text(god_name, losses_ordered)
		-- 	-- if losses_text ~= "" then
		-- 	-- 	tooltip_text = tooltip_text .. common.get_localised_string(lookup_prefix .. gods_panel_tooltip_loss_title[god_name].loc_key) .. "\n" .. losses_text .. "\n"
		-- 	-- end

		-- 	-- local god_uic = find_uicomponent(UIComponent(context.component), "gods_list", god_name, "god_icon")
		-- 	-- after new design, for now we don't have such component
		-- 	-- if god_uic then
		-- 		-- god_uic:SetTooltipText(tooltip_text, "From troy_campaign_setup.lua - concatenated from multiple sources", true)
		-- 	-- end
		-- end
	end,
	true
)

start_pos_armies_to_beat = {
	
	["troy_main_dan_achilles"] = {
		faction = "troy_main_dan_ellopians",
		--unit_list = "troy_spearmen,troy_spearmen,troy_spearmen,troy_spearmen,troy_achaean_stoneslingers,troy_achaean_spearmen,troy_light_swordsmen,troy_light_swordsmen",
		unit_list = {
			troy_historical = "troy_spearmen,troy_achaean_stoneslingers,troy_achaean_spearmen,troy_light_swordsmen",
			main_troy = "troy_spearmen,troy_achaean_stoneslingers,troy_achaean_spearmen,troy_light_swordsmen",
			troy_mythic = "troy_spearmen,troy_achaean_stoneslingers,troy_light_swordsmen,troy_mth_centaurs_spear_shield",
		},
		region = "troy_main_ellopia_histiaea",
		x_coordinate = 322,
		y_coordinate = 404
	},
	["troy_main_dan_mycenae"] = {
		faction = "troy_main_dan_tiryns",
		unit_list = {
			troy_historical = "troy_spearmen,troy_achaean_skirmishers,troy_trojan_slingers,troy_achaean_spearmen,troy_light_swordsmen",
			main_troy = "troy_spearmen,troy_achaean_skirmishers,troy_trojan_slingers,troy_achaean_spearmen,troy_light_swordsmen",
			troy_mythic = "troy_spearmen,troy_achaean_skirmishers,troy_trojan_slingers,troy_light_swordsmen,troy_mth_gen_myth_harpy_elite",
		},
		region = "troy_main_mycenaeca_mycenae",
		x_coordinate = 328,
		y_coordinate = 284
	},
	["troy_main_dan_ithaca"] = {
		faction = "troy_main_dan_teleboans",
		unit_list = {
			troy_historical = "troy_spearmen,troy_achaean_stoneslingers,troy_greek_militia,troy_islanders",
			main_troy = "troy_spearmen,troy_achaean_stoneslingers,troy_greek_militia,troy_islanders",
			troy_mythic = "troy_spearmen,troy_achaean_stoneslingers,troy_greek_militia,troy_mth_gen_myth_sirens",
		},
		region = "troy_main_cephallenia_same",
		x_coordinate = 142,
		y_coordinate = 317,
		subtype = "troy_archer_skirmisher",
		forename = "names_name_938201204"
	},
	["troy_main_dan_sparta"] = {
		faction = "troy_main_dan_sparta_separatists",
		unit_list = {
			troy_historical = "troy_achaean_spearmen,troy_achaean_skirmishers,troy_trojan_slingers,troy_laconian_militia,troy_light_swordsmen",
			main_troy = "troy_achaean_spearmen,troy_achaean_skirmishers,troy_trojan_slingers,troy_laconian_militia,troy_light_swordsmen",
			troy_mythic = "troy_achaean_spearmen,troy_achaean_skirmishers,troy_laconian_militia,troy_light_swordsmen,troy_mth_centaurs_sword_and_bow",
		},
		region = "troy_main_lacedaemon_boeae",
		x_coordinate = 330,
		y_coordinate = 205
	},
	["troy_main_trj_hector"] = {
		faction = "troy_main_dan_makaria",
		unit_list = {
			troy_historical = "troy_achaean_spearmen,troy_achaean_spearmen,troy_achaean_stoneslingers,troy_achaean_stoneslingers,troy_light_swordsmen,troy_achaean_skirmishers",
			main_troy = "troy_achaean_spearmen,troy_achaean_spearmen,troy_achaean_stoneslingers,troy_achaean_stoneslingers,troy_light_swordsmen,troy_achaean_skirmishers",
			troy_mythic = "troy_achaean_spearmen,troy_achaean_spearmen,troy_achaean_stoneslingers,troy_achaean_stoneslingers,troy_light_swordsmen,troy_mth_giant_spear_shield",
		},
		region = "troy_main_ide_gargara",
		x_coordinate = 587,
		y_coordinate = 506
	},
	["troy_main_trj_paris"] = {
		faction = "troy_main_dan_makaria",
		unit_list = {
			troy_historical = "troy_greek_militia,troy_greek_militia,troy_greek_militia",
			main_troy = "troy_greek_militia,troy_greek_militia,troy_greek_militia",
			troy_mythic = "troy_greek_militia,troy_greek_militia,troy_achaean_spearmen,troy_mth_giant_spear_shield,troy_mth_giant_axe_bow",
		},
		region = "troy_main_troas_hamaxitos",
		x_coordinate = 545,
		y_coordinate = 495,
		subtype = "troy_archer_skirmisher",
		forename = "names_name_941693320",
	},
	["troy_main_trj_dardania"] = {
		faction = "troy_main_dan_apaesos",
		unit_list = {
			troy_historical = "troy_spearmen,troy_spearmen,troy_trojan_slingers,troy_light_swordsmen",
			main_troy = "troy_spearmen,troy_spearmen,troy_trojan_slingers,troy_light_swordsmen",
			troy_mythic = "troy_spearmen,troy_spearmen,troy_light_swordsmen,troy_mth_centaurs_sword_and_javelin",
		},
		region = "troy_main_dardania_arisbe",
		x_coordinate = 569,
		y_coordinate = 560
	},
	["troy_main_trj_lycia"] = {
		faction = "troy_main_dan_rhodes",
		unit_list = {
			troy_historical = "troy_spearmen,troy_achaean_skirmishers,troy_greek_militia,troy_light_swordsmen",
			main_troy = "troy_spearmen,troy_achaean_skirmishers,troy_greek_militia,troy_light_swordsmen",
			troy_mythic = "troy_spearmen,troy_achaean_skirmishers,troy_greek_militia,troy_mth_giant_axe_jav",
		},
		region = "troy_main_lycia_telmessos",
		x_coordinate = 812,
		y_coordinate = 254
	},
	["troy_amazons_trj_hippolyta"] = {
		faction = "troy_main_trj_maeonians_tml", 
		unit_list = {
			troy_historical = "troy_large_axemen,troy_anatolian_swords,troy_dardanian_stoneslingers,troy_coastal_club_fighters",
			main_troy = "troy_large_axemen,troy_anatolian_swords,troy_dardanian_stoneslingers,troy_coastal_club_fighters",
			troy_mythic = "troy_large_axemen,troy_anatolian_swords,troy_dardanian_stoneslingers,troy_mth_gen_myth_harpy,troy_mth_gen_myth_harpy",
		},
		region = "troy_main_maeandros_anthea",
		x_coordinate = 691,
		y_coordinate = 366
	},
	["troy_amazons_trj_penthesilea"] = {
		faction = "troy_main_trj_thyni",
		unit_list = {
			troy_historical = "troy_trojan_militia,troy_trojan_militia,troy_spearmen,troy_phrygian_warriors,troy_trojan_slingers",
			main_troy = "troy_trojan_militia,troy_trojan_militia,troy_spearmen,troy_phrygian_warriors,troy_trojan_slingers",
			troy_mythic = "troy_trojan_militia,troy_trojan_militia,troy_phrygian_warriors,troy_trojan_slingers,troy_mth_centaurs_spear_shield",
		},
		region = "troy_main_thynia_derkos",
		x_coordinate = 719,
		y_coordinate = 684
	},
	["troy_main_dan_argos"] = {
		faction = "troy_main_dan_corinthians",
		unit_list = {
			troy_historical = "troy_achaean_spearmen,troy_achaean_spearmen,troy_light_swordsmen,troy_achaean_stoneslingers",
			main_troy = "troy_achaean_spearmen,troy_achaean_spearmen,troy_light_swordsmen,troy_achaean_stoneslingers",
			troy_mythic = "troy_achaean_spearmen,troy_achaean_spearmen,troy_achaean_stoneslingers,troy_mth_giant_axe_bow",
		},
		region = "troy_main_argolis_erchomenos",
		x_coordinate = 298,
		y_coordinate = 288
	},
	["troy_main_dan_salamis"] = {
		faction = "troy_main_dan_epidayrus", 
		unit_list = {
			troy_historical = "troy_spearmen,troy_spearmen,troy_light_swordsmen,troy_light_swordsmen,troy_achaean_stoneslingers,troy_achaean_stoneslingers",
			main_troy = "troy_spearmen,troy_spearmen,troy_light_swordsmen,troy_light_swordsmen,troy_achaean_stoneslingers,troy_achaean_stoneslingers",
			troy_mythic = "troy_spearmen,troy_spearmen,troy_light_swordsmen,troy_light_swordsmen,troy_achaean_stoneslingers,troy_mth_giant_spear_shield",
		},
		region = "troy_main_megaris_salamis",
		x_coordinate = 362,
		y_coordinate = 313
	},
	["troy_rem_trj_thrace"] = {
		faction = "troy_main_trj_agriophones",
		unit_list = {
		
			troy_historical = "troy_trojan_spears,troy_trojan_militia,troy_trojan_militia,troy_trojan_archers,troy_trojan_archers",
			main_troy = "troy_trojan_spears,troy_trojan_militia,troy_trojan_militia,troy_trojan_archers,troy_trojan_archers",
			troy_mythic = "troy_mth_centaurs_spear_shield,troy_trojan_militia,troy_trojan_militia,troy_trojan_archers,troy_trojan_archers",

		},
		region = "troy_main_sintice_heraclea_sintica",
		x_coordinate = 318,
		y_coordinate = 613,
		subtype = "troy_warlord_utility",
		forename = "names_name_292150268"
	},
	["troy_rem_horde_aethiopians"] = {
		faction = "troy_main_dan_rhodes",
		unit_list = {
			troy_historical = "troy_achaean_spearmen,troy_greek_militia,troy_spearmen,troy_spearmen,troy_achaean_stoneslingers,troy_achaean_stoneslingers",
			main_troy = "troy_achaean_spearmen,troy_greek_militia,troy_spearmen,troy_spearmen,troy_achaean_stoneslingers,troy_achaean_stoneslingers",
			troy_mythic = "troy_achaean_spearmen,troy_greek_militia,troy_mth_giant_spear_shield,troy_spearmen,troy_achaean_stoneslingers,troy_achaean_stoneslingers",
			
		},
		region = "troy_main_rhodes_lindos",
		x_coordinate = 734,
		y_coordinate = 200
	}
}

thebes_named_army_config = {
	faction = "troy_main_dan_boeotians",
	unit_list = {
		troy_historical = "troy_shielded_spearmen,troy_shielded_spearmen,troy_veteran_club_warriors,troy_veteran_club_warriors,troy_heavy_thessaly_javelinmen,troy_heavy_thessaly_javelinmen",
		main_troy = "troy_shielded_spearmen,troy_shielded_spearmen,troy_veteran_club_warriors,troy_veteran_club_warriors,troy_heavy_thessaly_javelinmen,troy_heavy_thessaly_javelinmen",
		troy_mythic = "troy_shielded_spearmen,troy_shielded_spearmen,troy_veteran_club_warriors,troy_veteran_club_warriors,troy_heavy_thessaly_javelinmen,troy_heavy_thessaly_javelinmen",
	},
	region = "troy_main_boeotia_thebes",
	x_coordinate = 349,
	y_coordinate = 352,
	subtype = "troy_fighter_disruptor",
	forename = "names_name_659086372",
}

core:add_listener(
	"NewCampaignStarted_start_pos_armies_to_beat",
	"NewCampaignStarted",
	function(context)
		return not core:svr_load_bool("sbool_player_selected_first_turn_intro_on_frontend") or cm:is_multiplayer()
	end,
	function(context)
		local faction_list = context:model():world():faction_list()
		for i = 0, faction_list:num_items() - 1 do
			if faction_list:item_at(i):is_human() then
				spawn_start_pos_army_to_beat(faction_list:item_at(i))
			end
		end
		--thebes_named_army()
	end,
	false
)


function spawn_start_pos_army_to_beat(faction)
	local faction_name = faction:name()
	local campaign_name = cm:get_campaign_name()
	out("FACTION NAME " .. faction_name)
	if start_pos_armies_to_beat[faction_name] and start_pos_armies_to_beat[faction_name].subtype and start_pos_armies_to_beat[faction_name].forename then
		cm:create_force_with_general(
			start_pos_armies_to_beat[faction_name].faction,
			start_pos_armies_to_beat[faction_name].unit_list[campaign_name],
			start_pos_armies_to_beat[faction_name].region,
			start_pos_armies_to_beat[faction_name].x_coordinate,
			start_pos_armies_to_beat[faction_name].y_coordinate,
			"general",
			start_pos_armies_to_beat[faction_name].subtype,
			start_pos_armies_to_beat[faction_name].forename,
			"",
			"",
			"",
			false,
			function(cqi)
				if cqi then 
					local character = cm:get_character_by_cqi(cqi)
					cm:disable_movement_for_character("character_cqi:" .. tostring(cqi))
					if character and not character:is_null_interface() then
						cm:set_force_has_retreated_this_turn(character)
					end
					start_pos_armies_to_beat[faction_name].cqi = cqi
					core:add_listener(
						"enable_movement_start_pos_army", 
						"FactionTurnStart", 
						function(context)
							return context:faction():name() == faction_name and (cm:model():turn_number() == 2)
						end, 
						function(context)
							cm:enable_movement_for_character("character_cqi:" .. tostring(cqi))
						end, 
						false
					)
					if campaign_name == "troy_historical" then 
						bodyguard_as_ancillary_setup:add_bodyguard_as_ancillary(nil, character)
					end
				end 
			end
		)
	else

		if start_pos_armies_to_beat[faction_name] then
			cm:create_force(
				start_pos_armies_to_beat[faction_name].faction,
				start_pos_armies_to_beat[faction_name].unit_list[campaign_name],
				start_pos_armies_to_beat[faction_name].region,
				start_pos_armies_to_beat[faction_name].x_coordinate,
				start_pos_armies_to_beat[faction_name].y_coordinate,
				true,
				function(cqi)
					if cqi then 
						local character = cm:get_character_by_cqi(cqi)
						cm:disable_movement_for_character("character_cqi:" .. tostring(cqi))
						if character and not character:is_null_interface() then
							cm:set_force_has_retreated_this_turn(character)
						end
						if character:faction():name() == "troy_main_dan_sparta_separatists" then
							cm:apply_effect_bundle_to_characters_force("effect_bundle_for_start_pos_army_dummy",cqi,0)
						end
						start_pos_armies_to_beat[faction_name].cqi = cqi
						core:add_listener(
							"enable_movement_start_pos_army", 
							"FactionTurnStart", 
							function(context)
								return context:faction():name() == faction_name and (cm:model():turn_number() == 2)
							end, 
							function(context)
								cm:enable_movement_for_character("character_cqi:" .. tostring(cqi))
							end, 
							false
						)
						if campaign_name == "troy_historical" then
							if bodyguard_as_ancillary_setup then
								bodyguard_as_ancillary_setup:add_bodyguard_as_ancillary(nil, character)
							end
						end
					end 
				end,
				false
			)
		end
	end
	
end

function thebes_named_army()
	local campaign_name = cm:get_campaign_name()
	if thebes_named_army_config and is_table(thebes_named_army_config) then
		cm:create_force_with_general(
			thebes_named_army_config.faction,
			thebes_named_army_config.unit_list[campaign_name],
			thebes_named_army_config.region,
			thebes_named_army_config.x_coordinate,
			thebes_named_army_config.y_coordinate,
			"general",
			thebes_named_army_config.subtype,
			thebes_named_army_config.forename,
			"",
			"",
			"",
			false,
			function(cqi)
				if cqi then
					cm:join_garrison("character_cqi:" .. tostring(cqi), "settlement:"..thebes_named_army_config.region)
					cm:disable_movement_for_character("character_cqi:" .. tostring(cqi))
				end 
				if cm:get_campaign_name() == "troy_historical" then
					if bodyguard_as_ancillary_setup then
						bodyguard_as_ancillary_setup:add_bodyguard_as_ancillary(nil, cm:get_character_by_cqi(cqi))
					end
				end
			end
		)
	else
		script_error("function thebes_named_army() tried to access thebes_named_army_config but was unable. Check if thebes_named_army_config is setup properly")
		return
	end
end

function start_story_dilemma_listeners()

	core:add_listener(
		"troy_story_dilemma_initial_trigger",
		"FactionTurnStart",
		function(context)
			local faction = context:faction()
			if not faction:is_human() or cm:model():turn_number() > story_dilemma_max_trigger_turn then
				return false
			else
				local effect_bundles = faction:effect_bundles()
				for i=0, effect_bundles:num_items() -1 do
					local current_key = effect_bundles:item_at(i):key()
					if  string.find(current_key, "effect_bundle_strategic_threat") and
						(string.find(current_key, "_3") or string.find(current_key, "_4") or string.find(current_key, "_5") or string.find(current_key, "_6") or string.find(current_key, "_7"))
					then
						return true
					end
				end
			end

		end,
		function(context)

			if story_dilemma_initial_trigger_done then
				return
			end

			local faction = context:faction()
			local factions_at_war_with = faction:factions_at_war_with() 
			local player_culture = faction:culture()
			if player_culture == "troy_ama_clt_hordes" or player_culture == "troy_rem_clt_thraco_phrygians" or player_culture == "troy_rem_clt_hordes_aethiopians" then
				player_culture = "troy_main_clt_trojans"
			end

			for i = 0, factions_at_war_with:num_items() -1 do
				if 	factions_at_war_with:item_at(i):culture() == player_culture and
					(factions_at_war_with:item_at(i):is_major() or story_dilemma_faithful_ally_factions[player_culture][factions_at_war_with:item_at(i):name()])
				then
					return
				end
			end

			story_dilemma_initial_trigger_done = true
			cm:trigger_dilemma(faction:name(), story_dilemma_initial_key[player_culture])
		end,
		false
	)

	core:add_listener(
		"troy_story_dilemma_choice_third",
		"DilemmaChoiceMadeEvent",
		function(context)
			return (context:dilemma() == story_dilemma_initial_key[context:faction():culture()]) and story_dilemma_initial_trigger_done and (context:choice() == 2)
		end,
		function(context)
			story_dilemma_secondary_trigger_turn = cm:model():turn_number() + story_dilemma_secondary_trigger_delay_turns
		end,
		false
	)

	core:add_listener(
		"troy_story_dilemma_choice_log_player_choice",
		"DilemmaChoiceMadeEvent",
		function(context)
			local dilemma = context:dilemma()
			return ((dilemma == story_dilemma_initial_key[context:faction():culture()]) or (dilemma == story_dilemma_secondary_key[context:faction():culture()])) and context:choice() == 0
		end,
		function(context)
			local faction = context:faction()
			local player_culture = faction:culture()
			if player_culture == "troy_ama_clt_hordes" or player_culture == "troy_rem_clt_thraco_phrygians" or player_culture == "troy_rem_clt_hordes_aethiopians" then
				player_culture = "troy_main_clt_trojans"
			end
			local factions_list = cm:model():world():faction_list()
			for i=0, factions_list:num_items() - 1 do
				local curr_faction = factions_list:item_at(i)
				if curr_faction:culture() == player_culture and 
					(curr_faction:is_major() or story_dilemma_faithful_ally_factions[player_culture][curr_faction:name()])
				then
					cm:cai_strategic_stance_manager_block_all_stances_but_that_specified_towards_target_faction(
						curr_faction:name(),
						faction:name(),
						"CAI_STRATEGIC_STANCE_BEST_FRIENDS"
					)
				elseif curr_faction:culture() ~= player_culture and curr_faction:is_major() then
					local same_cult_factions = curr_faction:factions_of_same_culture()
					for j=0, same_cult_factions:num_items() -1 do
						local curr_cult_faction = same_cult_factions:item_at(j)
						if curr_cult_faction:is_major() then
							cm:cai_strategic_stance_manager_block_all_stances_but_that_specified_towards_target_faction(
								curr_faction:name(),
								curr_cult_faction:name(),
								"CAI_STRATEGIC_STANCE_BEST_FRIENDS"
							)
						end
					end
				end
			end
			story_dilemma_player_chose_story = true
		end,
		false
	)

	core:add_listener(
		"troy_story_dilemma_attacking_faithful_ally",
		"NegativeDiplomaticEvent",
		function(context)
			local faction = context:character():faction()
			return story_dilemma_player_chose_story and faction:is_human() and faction == context:proposer() and context:is_war()
		end, 
		function(context)
			local faction = context:character():faction()
			local player_culture = faction:culture()
			if player_culture == "troy_ama_clt_hordes" or player_culture == "troy_rem_clt_thraco_phrygians" or player_culture == "troy_rem_clt_hordes_aethiopians" then
				player_culture = "troy_main_clt_trojans"
			end
			local factions_list = cm:model():world():faction_list()
			for i=0, factions_list:num_items() - 1 do
				local curr_faction = factions_list:item_at(i)
				if curr_faction:culture() == player_culture and
					(curr_faction:is_major() or story_dilemma_faithful_ally_factions[player_culture][curr_faction:name()])
				then
					cm:cai_strategic_stance_manager_block_all_stances_but_that_specified_towards_target_faction(
						curr_faction:name(),
						faction:name(),
						"CAI_STRATEGIC_STANCE_BITTER_ENEMIES"
					)
				end
			end
		end, 
		false
	)

	core:add_listener(
		"troy_story_dilemma_secondary_trigger",
		"FactionTurnStart",
		function(context)
			local faction = context:faction()
			if not faction:is_human() then
				return false
			else
				local effect_bundles = faction:effect_bundles()
				for i=0, effect_bundles:num_items() -1 do
					local current_key = effect_bundles:item_at(i):key()
					if  string.find(current_key, "effect_bundle_strategic_threat") and
						(string.find(current_key, "_3") or string.find(current_key, "_4") or string.find(current_key, "_5") or string.find(current_key, "_6") or string.find(current_key, "_7"))
					then
						return cm:model():turn_number() >= story_dilemma_secondary_trigger_turn
					end
				end
			end

		end,
		function(context)

			if story_dilemma_secondary_trigger_done then
				return
			end

			local faction = context:faction()
			local factions_at_war_with = faction:factions_at_war_with() 
			local player_culture = faction:culture()
			if player_culture == "troy_ama_clt_hordes" or player_culture == "troy_rem_clt_thraco_phrygians" or player_culture == "troy_rem_clt_hordes_aethiopians" then
				player_culture = "troy_main_clt_trojans"
			end

			for i = 0, factions_at_war_with:num_items() -1 do
				if 	factions_at_war_with:item_at(i):culture() == player_culture and
					(factions_at_war_with:item_at(i):is_major() or story_dilemma_faithful_ally_factions[player_culture][factions_at_war_with:item_at(i):name()])
				then
					return
				end
			end

			story_dilemma_secondary_trigger_done = true
			cm:trigger_dilemma(faction:name(), story_dilemma_secondary_key[player_culture])
		end,
		false
	)
end

cm:add_saving_game_callback(
	function(context)
		cm:save_named_value("STORY_DILEMMA_INITIAL_TRIGGER"	,story_dilemma_initial_trigger_done,context)
		cm:save_named_value("STORY_DILEMMA_SECONDARY_TRIGGER",story_dilemma_secondary_trigger_done,context)
		cm:save_named_value("STORY_DILEMMA_SECONDARY_TRIGGER_TURN",story_dilemma_secondary_trigger_turn,context)
		cm:save_named_value("STORY_DILEMMA_PLAYER_CHOICE",story_dilemma_player_chose_story,context)
	end
)

cm:add_loading_game_callback(
	function(context)
		story_dilemma_initial_trigger_done = cm:load_named_value("STORY_DILEMMA_INITIAL_TRIGGER",story_dilemma_initial_trigger_done,context)
		story_dilemma_secondary_trigger_done = cm:load_named_value("STORY_DILEMMA_SECONDARY_TRIGGER",story_dilemma_secondary_trigger_done,context)
		story_dilemma_secondary_trigger_turn = cm:load_named_value("STORY_DILEMMA_SECONDARY_TRIGGER_TURN",story_dilemma_secondary_trigger_turn,context)
		story_dilemma_player_chose_story = cm:load_named_value("STORY_DILEMMA_PLAYER_CHOICE",story_dilemma_player_chose_story,context)
	end
)

core:add_listener(
	"Troy_city_garrison_replenishment",
	"BattleCompleted",
	true,
	function(context)
		local battle = context:pending_battle()

		if not (battle:has_region() and battle:region():name() == troy_city_region_key) then
			return
		end

		local secondary_attackers = battle:secondary_attackers()
		for i = 0, secondary_attackers:num_items() - 1 do
			local char = secondary_attackers:item_at(i)
			if not char:is_null_interface() and char:has_military_force() then
				local military_force = char:military_force()
				if military_force:is_armed_citizenry() then
					cm:replenish_units(cm:char_lookup_str(char:command_queue_index()), troy_city_post_battle_replenishment)
					return
				end
			end
		end

		local secondary_defenders = battle:secondary_defenders()
		for i = 0, secondary_defenders:num_items() - 1 do
			local char = secondary_defenders:item_at(i)
			if not char:is_null_interface() and char:has_military_force() then
				local military_force = char:military_force()
				if military_force:is_armed_citizenry() then
					cm:replenish_units(cm:char_lookup_str(char:command_queue_index()), troy_city_post_battle_replenishment)
					return
				end
			end
		end

		local attacker = battle:attacker()
		if battle:has_attacker() and not attacker:is_null_interface() then
			local attacker_military_force = attacker:military_force()
			if attacker_military_force:is_armed_citizenry() then
				cm:replenish_units(cm:char_lookup_str(attacker:command_queue_index()), troy_city_post_battle_replenishment)
				return
			end
		end

		local defender = battle:defender()
		if battle:has_defender() and not defender:is_null_interface() then
			local defender_military_force = defender:military_force()
			if defender_military_force:is_armed_citizenry() then
				cm:replenish_units(cm:char_lookup_str(defender:command_queue_index()), troy_city_post_battle_replenishment)
				return
			end
		end

	end,
	true
)

core:add_listener (
	"PenthesileaMomentum_FirstTickAfterWorldCreated_UI",
	"FirstTickAfterWorldCreated",
	true,
	function(context)
		cm:set_custom_settlement_info_icon(troy_city_region_key, "troy_replenishment_bonus", "UI/skins/default/sp_icon_troy_garrison.png", "city_info_bar_troy_replenisment_bonus")
		CampaignUI.UpdateSettlementEffectIcons()
	end,
	false
)

-- This is not ideal, but it will have to do
-- The vassalize occupation option does not check if the equivalent diplomatic action is available, so time to lock it via the UI
core:add_listener(
	"battle_against_antagonist_no_vassalization",
	"PanelOpenedCampaign",
	function(context) 
		if antagonist then 
			return antagonist.current ~= "" and context.string == "popup_pre_battle"
		else
			return false
		end
	end,
	function(context)
		local has_antagonist = false
		local pb = cm:model():pending_battle()
		if pb:has_defender() and pb:defender_faction():name() == antagonist.current then
			has_antagonist = true
		elseif pb:has_attacker() and pb:attacker_faction():name() == antagonist.current then
			has_antagonist = true
		end
		cm:override_ui("disable_postbattle_subjugation_button", has_antagonist)
	end,
	true
)

-- Once again, this is far from ideal, but you gotta do what you gotta do
core:add_listener(
	"remove_excess_ai_food",
	"FactionTurnEnd",
	function(context)
		return not context:faction():is_human() and not context:faction():is_rebel()
	end,
	function(context)
		local fac = context:faction()
		local food_amount = fac:pooled_resource("troy_food"):value()
		local cap
		if fac:is_major() then 
			cap = 60000
		else
			cap = 30000
		end
		if food_amount > cap then
			local amount_to_remove = (food_amount * 0.05) * (-1)
			cm:faction_add_pooled_resource(fac:name(),"troy_food", "troy_resource_factor_faction",amount_to_remove)
		end
	end,
	true
)
--------------------------------------------------------------
----------------- Stealing the Palladium ----------------------
--------------------------------------------------------------

	
function trigger_steal_the_palladium_mission(faction, troy_region)
	local mission_key = "troy_adi_mission_stealing_the_palladium"
	local payload_1 = "text_display {  lookup dummy_troy_adi_palladium_troy_debuff;}"
	local payload_2 = "text_display { lookup dummy_troy_adi_palladium_ancillary_payload; }"

	local paladium_ancillary_key = "troy_adi_anc_item_palladium"
	local troy_debuff_bundle_key = "troy_adi_effect_bundle_palladium_stolen"
	
	local MOVE_FL_TO_TROY = "mission_text_text_troy_adi_scripted_mission_move_faction_leader_to_troy"

	local mission = mission_manager:new(faction:name(), mission_key,  function()
		cm:add_ancillary_to_faction(faction:name(), paladium_ancillary_key, true)
		cm:apply_effect_bundle_to_region(troy_debuff_bundle_key, troy_region:name(), -1)
		troy_adi_palladium_vars.palladium_stolen_by_faction = faction:name()
		troy_adi_palladium_vars.palladium_stolen = true
	end )
	
	out("--------> Spawning mission (" .. mission_key .. ") for faction: (" .. faction:name() .. ")")

	mission:add_new_scripted_objective(
		MOVE_FL_TO_TROY,
		"CharacterFinishedMovingEvent",
		function(context)
			local character = context:character()
			if character:faction():name() == faction:name() and character:is_faction_leader() then 
				if character:region() == troy_region then 
					return true
				end
			end
		end,
		"ScriptedObjectiveStealPalladiumMoveFactionLeader",
		true,
		true
	)
	-- abort the mission if the player has captured Troy.
	mission:add_scripted_objective_failure_condition(
		"RegionFactionChangeEvent",
		function(context)
			local context_region = context:region()
			return context_region == troy_region and context_region:owning_faction() == faction
		end
	)

	mission:set_mission_issuer("CLAN_ELDERS")
	mission:add_payload(payload_1)
	mission:add_new_objective("MOVE_TO_REGION", true)
	mission:add_condition("region " .. troy_region:name())
	mission:add_condition("agent_subtype troy_agent_spy")
	mission:add_payload(payload_2)
	mission:set_should_cancel_before_issuing(false)
	if not mission.is_registered then 
		mission:register()
	end

	core:remove_listener("troy_adi_stealing_the_palladium_mission_trigger_listener")
	troy_adi_palladium_vars.stealing_the_palldium_triggered = true

	return mission, mission_key
	
end

function stealing_the_palladium_listeners()
	local local_faction = cm:get_faction(cm:get_local_faction_name(true))
	local troy_region = cm:get_region("troy_main_ilion_troy")
	if not troy_adi_palladium_vars.stealing_the_palldium_triggered then 
		core:add_listener(
			"troy_adi_stealing_the_palladium_mission_trigger_listener",
			"FactionTurnStart",
			function(context)
				local faction = context:faction()
				local char_list = faction:character_list()
				local troy_faction = cm:get_faction("troy_main_trj_troy")
				local zoleia_region = cm:get_region("troy_main_ide_zeleia")

				if troy_faction and zoleia_region and not troy_faction:is_null_interface() and not troy_faction:is_dead() then 
					if faction:is_human() and faction:culture() == "troy_main_clt_danaans" and faction:at_war_with(troy_faction) then 
						for i = 0, char_list:num_items() - 1 do
							local curr_char = char_list:item_at(i)
							if curr_char:has_region() and curr_char:character_type("general") and curr_char:region() == zoleia_region then 
								return true
							end
						end
					end
				end
			end,

			function(context)
				local faction = context:faction()
				local mission, mission_key = trigger_steal_the_palladium_mission(faction, troy_region)
				local x = troy_region:settlement():logical_position_x()
				local y = troy_region:settlement():logical_position_y()

				mission:trigger()
				cm:set_scripted_mission_position(mission_key, "ScriptedObjectiveStealPalladiumMoveFactionLeader", x, y)
			end,
			true
		)
	else
		trigger_steal_the_palladium_mission(local_faction, troy_region)
	end
end

core:add_listener(
	"troy_adi_stealing_the_palladium_troy_debuff",
	"RegionFactionChangeEvent",
	function(context)
		local region = context:region()
		return troy_adi_palladium_vars.palladium_stolen and region:name() == troy_adi_palladium_vars.troy_region_key and region:owning_faction():name() ~= troy_adi_palladium_vars.palladium_stolen_by_faction
	end,

	function(context)
		cm:apply_effect_bundle_to_region(troy_adi_palladium_vars.palladium_stolen_effect_bundle, troy_adi_palladium_vars.troy_region_key, -1)
	end,
	true
)

cm:add_saving_game_callback(
	function(context)
		cm:save_named_value("STEALING_THE_PALLADIUM_TRIGGER", troy_adi_palladium_vars, context)
	end
)

cm:add_loading_game_callback(
	function(context)
		troy_adi_palladium_vars = cm:load_named_value("STEALING_THE_PALLADIUM_TRIGGER", troy_adi_palladium_vars, context)
	end
)